### ISSUE TITLE
Escribir protocolo para la generación de respaldos de activos de información #organización apc

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1006]
Ruta:
C:\Dropbox (LANCIS)\ORGANIZACION_APC\apc_iso\protocolos

7 de noviembre a las 10:30 am. reunión para comenzar a escribir el protocolo

**Comment by Nayita** [comment]
Minuta de la reunión del 7 de noviembre de 2018

Después de revisar lo escrito en el protocolo de organización de activos de información respecto a respaldo de información y probar el software Acronis para respaldo automatizado de información se acordó lo siguiente:

- Revisar con Paola los tipos de esquemas para decidir el esquema de respaldo que se utilizará de acuerdo a los proyectos.

Los esquemas son:

1. Esquema de versión única: versión completa y la sobreescribe cada vez.

2. Esquema de cadena de versiones: cadena de versiones completas e incrementales. elimina las versiones anteriores a un mes.

3. Esquema incremental: Versión incremental, almacena sólo los cambios.

4. Esquema diferencial: versión diferencial, almacena los cambios que han ocurrido desde la última versión completa.

- No hacer un protocolo nuevo, sino completar con la información del uso del Acronis y la periodicidad de los respaldos el protocolo de organización de activos de información.

- Hacer un manual con videos acerca del uso del Acronis.

- Solicitar el uso exclusivo de una computadora para respaldo automatizados de la información del Dropbox.

**Comment by edithvilla** [comment]
El día 8 de noviembre de 2018 se comentó con Paola los esquemas de respaldo que tiene el programa de Acronis, la indicación que dio fue escribir los criterios de selección de los esquemas para poder decidir el criterio para cada carpeta del dropbox

**Comment by edithvilla** [comment]
Agregué en la parte de los esquemas las carpetas de MEGADAPT, PAPIIT, CONSOLIDACIÓN Y SOFTWARE.

@vichdzgeo por favor puedes colocar como ejemplo en los esquemas las carpetas de las cuales eres responsable. El manuscrito está en:
https://github.com/lancis-apc/planeacion-colaborativa/blob/master/docs/protocolo_org_activ_info/protocolo_org_activ_info.md

este es el archivo que se está modificando

**Comment by Nayita** [comment]
Minuta de reunión 05-12-2018

Se estableció el tipo de esquemas de respaldo para las carpetas de activos de información a cargo de l@s responsables.
Con esto se concluye el protocolo.

Queda pendiente el video-manual de uso

**Comment by Nayita** [comment]
Elaboración de video del manual de uso del programa Acronis:
Al iniciar con el video se encontró con características propias de los esquema de respaldo que no habían sido considerados o entendidos con tanta claridad. Por lo tanto, se consideró hacer pruebas antes de definir los esquemas y con base en los resultados se reasignarán las carpetas a los distintos esquemas. Finalmente se elaborarán los videos en esta semana.

**Comment by Nayita** [comment]
@vichdzgeo Pon la tabla que hiciste aquí en el issue. Gracias

**Comment by vichdzgeo** [comment]
## Tabla comparativa de los modos existentes para las copias de seguridad (respaldos) en Acronis
![image](https://user-images.githubusercontent.com/38017509/50846411-afca2b00-1334-11e9-99ac-128c37b092e4.png)

**Comment by Nayita** [comment]
@vichdzgeo  subir la imagen de la tabla a la carpeta protocolo_org_activ_info que está en la sig. ruta
https://github.com/lancis-apc/planeacion-colaborativa/docs/protocolo_org_activ_info

**Comment by vichdzgeo** [comment]
@Nayita  el archivo ha sido agregado a la carpeta especificada.

**Comment by vichdzgeo** [comment]
@Nayita  se termino el video de respaldos, modo diferencial, podrías revisarlo para ver la manera en que podamos mejorarlo?

Ruta: \CARPETAS_TRABAJO\vhernandez\videos\salida\respaldos_modo_diferencial\respaldos_modo_diferencial.mp4

**Comment by edithvilla** [comment]
Observaciones del video:
1. Falta un título al inicio después del logo
2. Falta una descripción de qué es un respaldo de Modo diferencial y con qué programa se está haciendo el respaldo 
3. Correcciones en los párrafos que aparecen:
a. Elegir la carpeta de origen, Seleccionar la carpeta (archivos) que se necesita respaldar
b. Seleccionar el día de la semana y la hora en la que el software realizará la copia de seguridad, Seleccionar la temporalidad, el día de la semana y la hora en la que el software realizará la copia de seguridad.
c. Programación del Esquema o modo diferencial, Programación del esquema de la copia de seguridad de la carpeta
d. Para programar el apagado de equipo cuando termine de realizar la copia de seguridad, ir a la pestaña de Avanzado > clic en la opción "Equipo apagado" y palomear la casilla de "Apagar el equipo después de completar la copia de seguridad",   Para programar apagar el equipo después del respaldo se hace en la la pestaña Avanzado > Equipo apagado > Seleccionar "Apagar el equipo después de completar la copia de seguridad"

- En la sección de opciones de copia de seguridad de archivos, hay redundancia 
- Revisar faltas de ortografía 
- Cortar el video a partir del minuto 2:55

**Comment by Nayita** [comment]
Se da por terminado esta actividad. La elaboración del video se pasa al issue #1010
