### ISSUE TITLE
Convertir comandos de grass a versión 7.4 para nueva versión sigplanning #svacc

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#1007]
@vichdzgeo y @edithvilla nos dirán la ubicación final de resultados. La ubicación temporal del insumo (a moverse) es: /CARPETAS_TRABAJO/pgpriego/plenumsoft/sigplan_comando_grass.docx

**Comment by paola-gp** [comment]
documentación: https://grass.osgeo.org/grass64/manuals/index.html

**Comment by edithvilla** [comment]
El documento "sigplan_comando_grass.docx" ya lo copié en un archivo de google drive, también ya se los compartí

**Comment by edithvilla** [comment]
Lista de comandos (versión 6.4.1) para revisar
Edith:
1. d.vect
2. d.erase
3. d.out.png
4. r.remove
5. r.info

Instrucción: revisar y documentar (en la tabla de google drive) de cada comando  los cambio en las banderas y parámetros para versión 7.4

**Comment by vichdzgeo** [comment]
#Location para trabajar con grass 7.4
Ruta de trabajo: \SIG\desarrollo\sig_grass\nc_spm_08_grass7

**Comment by paola-gp** [comment]
Entregado a plenumsoft el jueves 15/11/18

**Comment by edithvilla** [comment]
El archivo que se entregó a plenumsoft se encuentra en la siguiente ruta:

\SOFTWARE\sigplan\entregas\sigplan_comando_grass_15nov2018.xlsx

al nombre del archivo se le agregó la fecha de entrega.

También ya quedó actualizado el readme.txt de la carpeta de "sigplan"
