### ISSUE TITLE
Crear figuras articulo environmental modelling #svacc

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#1009]
software está en /SOFTWARE/significance\significance_prototipo/ejecutable

en /Proyects/1 o 2 están las imágenes, verificar con @serranoycandela 

### Confirmación de ruta de las imagenes
las imagenes a utilizar son las que se encuentran en Proyects/1/f

**Comment by vichdzgeo** [comment]
## creación de un archivo en ilustrator que contenga los elementos gráficos de la plataforma

ruta de trabajo: CARPETAS DE TRABAJO\pgpriego\articulos\envmod\figuras

Se creo una carpeta en la ruta de trabajo llamada " elementos graficos_Carpeta" en la cual contiene el archivo "elementos graficos.ai"

**Comment by vichdzgeo** [comment]
### Actualización de archivos:

Para la figura de mapas la ultima versión es: figura_mapas_v3_300.tif
prueba de impresión de esta imagen: prueba_impresion_3.pdf

para elementos gráficos:

la figura se encuentra en /elementos graficos_Carpeta/elementos graficosv2-01.tif

**Comment by vichdzgeo** [comment]
Actualización de archivos:
Para la figura de mapas la ultima versión es: figura_mapas_v4_500.tif
prueba de impresión de esta imagen: figura_mapas__v4_prueba_impresion.pdf

para elementos gráficos:

la figura se encuentra en /elementos graficos_Carpeta/elementos graficosv2-01.tif
