### ISSUE TITLE
Elaborar exámenes y videos de protocolos #organización-apc

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#1010]
Actividades:
Elaborar exámenes en googleclassroom de todos los protocolos
Hacer videos del uso de GitHub y Dropbox

Los videos terminados estarán disponibles en la página de DitHub y en el dropbox en la siguiente ruta: CAPACITACION/cursos_no_formales

**Comment by Nayita** [comment]
El examen diagnóstico estará compuesto con preguntas de los siguientes documentos:
Procedimientos:
Organización general
Verificación de productos
Activos de información
Protocolos:
Organización de activos de información
Manejo de información sig
Generación de gráficas y mapas
Logística para reuniones y/o talleres externos
Recepción y entrega de activos de información
Manejo de bases de datos

**Comment by Nayita** [comment]
@edithvilla  para que lo pongas

**Comment by vichdzgeo** [comment]
## capacitar en el uso de camtasia para la creación de videos

carpeta de trabajo: C:\Dropbox (LANCIS)\CARPETAS_TRABAJO\vhernandez\videos

**Comment by edithvilla** [comment]
Video de instalación del Dropbox en la computadora (versión 1):

/CAPACITACION/cursos_no_formales/videos/dropbox/Dropbox/Dropbox.mp4

**Comment by Nayita** [comment]
Video de uso del GitHub está en la siguiente ruta \CAPACITACION\cursos_no_formales\videos\uso_github\uso_github.mp4

**Comment by Nayita** [comment]
@vichdzgeo 
Pon en esta ruta toda la información para que podamos modificar el video del Acronis y para que podamos usar la plantilla \CAPACITACION\cursos_no_formales\videos\

**Comment by vichdzgeo** [comment]
> @vichdzgeo
> Pon en esta ruta toda la información para que podamos modificar el video del Acronis y para que podamos usar la plantilla \CAPACITACION\cursos_no_formales\videos\

Archivos subidos en la carpeta solicitada:

plantilla de introducción:
plantilla_v_1920_1080_v1.zip
Modo diferencial:
plantilla_v_1920_1080_v1.zip

**Comment by vichdzgeo** [comment]
@edithvilla  el archivo modo_diferecial_edicion.mp4 fue subido  en la ruta de trabajo de este issue

**Comment by Nayita** [comment]
Corregir videos de respaldo, GitHub y Dropbox

**Comment by edithvilla** [comment]
se cierra hasta nuevo aviso
