### ISSUE TITLE
Coordinar actividades de becarios y técnicos #FOMIX, PAPIIT, CONSOLIDACIÓN

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1012]
Ruta: \SIG\desarrollo\sig_becarios\procesamiento
Área de estudio: Estado de Yucatán

Actividades:
1. Definir las actividades para becarios 
   Demanda específica YUC-2018-04-01

- [x]  Subsistema Natural: CC [#9](https://github.com/lancis-apc/espejos-lancis/issues/9) espejos-lancis

- [ ]  Subsistema Socioeconómico:  GT

- [ ] Subsistema Productivo: ?

2. Revisar los insumos que se encuentran en el proyecto de Pacífico Norte @vichdzgeo, @edithvilla indicará la ruta de estos insumos.

**Comment by edithvilla** [comment]
@vichdzgeo las capa geográficas que se ocuparon para la parte de vulnerabilidad en el Pacífico Norte se encuentran en el disco duro externo donde se encuentran el proyecto de Pacífico Norte y en el disco la ruta es: 
D:\Pacifico_Norte_Vuln

**Comment by Nayita** [comment]
@edithvilla  va ruta CONSOLIDACION\con_informes\insumos

**Comment by edithvilla** [comment]
@paola-gp esta es la ruta donde se encuentran los contratos de la personas que estamos contratadas 

CONSOLIDACION\con_informes\insumos

**Comment by edithvilla** [comment]
@vichdzgeo revisa los programas de trabajo de los técnicos de Mérida.
Los programa de trabajo se encuentran dentro de cada carpeta de los técnicos

/CONSOLIDACION/con_informes/comprobables_auditoria/probles/reporte_javier_robles.pdf

/CONSOLIDACION/con_informes/comprobables_auditoria/ccruz/...pdf

**Comment by edithvilla** [comment]
@vichdzgeo @yosunemiquela 

Nos reuniremos con los técnicos de Mérida para hacer checklist de los productos y revisar los programas de trabajo

las reuniones quedan así:

Jueves 7 de febrero a las 11 am con Javier Roblres y Carolina 
Lunes 11 de febrero a las 12 am con Carlos Cruz

**Comment by edithvilla** [comment]
Se realizó la junta con dos de los técnicos de Mérida, y se llegaron a los siguientes acuerdo:
1. Registrarán cada capa que trabajen en un issue, para poder tener una mejor comunicación
2. Se le asignaron las siguientes capas a Caro: estatal, localidades, colonias y manzanas
3. Se harán reuniones semanales para dar seguimiento a las tareas
