### ISSUE TITLE
Impartir curso de capacitación para LANCIS Mérida en cómputo académico y documentación de procedimientos en Qgis 2.18 #lancis

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/planeacion-colaborativa#1017]
## Curso de capacitación en el uso y tratamiento de información geográfica a partir de la creación de scripts en python y qgis 2.18

@paola-gp @edithvilla @Nayita

**Comment by vichdzgeo** [comment]
ruta del programa de trabajo: 
\CARPETAS_TRABAJO\vhernandez\capacitaciones\python_qgis\programa_trabajo_merida2019.xlsx

**Comment by paola-gp** [comment]
## Requisitos:

1. Que lleven su equipo de cómputo
2. Conocimientos básicos de SIG
3. Deberían tener instalado anaconda3 y QGIS 2.18

- https://www.anaconda.com/download/
- http://download.osgeo.org/qgis/windows/    VERSION 2.18.27

## Syllabus

**Comment by vichdzgeo** [comment]
Programa de trabajo:
![image](https://user-images.githubusercontent.com/38017509/51276228-c5c19680-1999-11e9-8f7b-63217ba977a5.png)

**Comment by Nayita** [comment]
@paola-gp y @vichdzgeo   la carpeta del curso está en la siguiente ruta CAPACITACION/cursos_no_formales/curso_python_gis_2_18

**Comment by paola-gp** [comment]
Quiz para diagnóstico en el uso del protocolos:

https://docs.google.com/forms/d/1jsfN_xKGKq1lOUOqS4vmultUrOzR_G-ch4xOnXmTM-A/viewform?edit_requested=true

**Comment by paola-gp** [comment]
en ADMIN\admin_apc\admin_viaticos\facturas\mer_22_26_ene_2019 se ubican las facturas. 
en ADMIN\admin_apc\admin_viaticos\pases_abordar\merida_22_26_ene_2019 se ubican los pases de abordar

**Comment by paola-gp** [comment]
@edithvilla: preparar constancias del curso

**Comment by paola-gp** [comment]
@serranoycandela, @rgarcia-herrera y @vichdzgeo: favor de enviar dos preguntas de opción múltiple cada uno para que podamos emitir constancias a los participantes del curso. 

Con respecto a los viáticos este es el total que se debe reembolsar a cada persona:

Reembolso 
--
Fidel | $       1,818.54
Paola | $       5,436.88
Rodrigo | $          485.50
Víctor | $       1,089.61
Total  | $       8,830.53

En cuanto @paola-gp cambie el cheque, se les dará su reembolso correspondiente. Cualquier detalle del presupuesto se puede consultar en ADMIN\admin_apc\admin_viaticos\facturas\mer_22_26_ene_2019
