### ISSUE TITLE
Preparar presentación en anfiteatro para reunión con el gob. de la cdmx #general

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1018]
Ruta: 

\PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_24ene2019\

En esta carpeta están las carpetas de:

insumos, se encuentran los slides de la plataforma de diputados, packard, Tec de Monterrey
logistica, aquí se encuentra la lista de asistencia, falta el título de la presentación
plataforma, el script combinado de la plataforma de Packard y Tec de Monterrey

Actividades:

- [x] Sincronizar dropbox en el anfiteatro

- [x] Revisar con Luis las presentaciones para poder decidir cuál se va a presentar

- [x] Imprimir lista de asistencia

- [x] Unificar los script de la presentación de Packard y Tec

**Comment by edithvilla** [comment]
1. En la carpeta donde se encuentra el código de la plataforma que se ocupa en el anfiteatro se encuentra desordenada. 
2. No está indicado cual es el código que se ocupa para la plataforma (hay dos versiones)
3. La presentación que se dio al Dr. Molina del Tec de Monterrey se encuentra fuera de protocolo, ya que la carpeta no se encuentra en el dropbox

**Comment by edithvilla** [comment]
@dpedroza74 el formato de la minuta se encuentra en la siguiente ruta:

\PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_24ene2019\logistica

FRR-SGC VER. 1.docx

**Comment by edithvilla** [comment]
Presentación dada

**Comment by Nayita** [comment]
El audio de la presentación quedó en la siguiente ruta PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_24ene2019\logistica\audio\audio_lancis_gobcdmx_24ene2019

**Comment by Nayita** [comment]
@dpedroza74 te envío la ruta para la colocación de la minuta PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_24ene2019\logistica

**Comment by edithvilla** [comment]
La organización de la carpeta de la presentación quedó de acuerdo a protocolo:

\PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_24ene2019

 - insumos, en esta carpeta se encuentran los slides de las presentaciones que se dieron en la reunión de Packard y Tec. de Monterrey
 - logistica, se encuentra el audio de la presentación, la lista de asistencia y la minuta
 - plataforma, se encuentra la carpeta que contiene los slides de la presentación, el guion para la plataforma y el archivo de power point y pdf con la presentación
 - procesamiento, se encuentran las slides que se agregaron a las presentación
