### ISSUE TITLE
Realizar lista de aplicaciones web y plataformas #organización #general

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1019]
La lista de aplicaciones web se registrarán aquí para después incorporarlas a la página del github del Área de Planeación Colaborativa:
# Plataformas
## https://lancisapc.wixsite.com/plataformas

@paola-gp poner en este issue las direcciones de las páginas web que tu creaste con las aplicaciones

**Comment by edithvilla** [comment]
La aplicación de Red de desalojo en secas y lluvias se elimina de la página de github

**Comment by edithvilla** [comment]
Lista de aplicaciones web:

1. SIGplanning
2. SIGnificance
3. Laboratorio Binacional
4. Funciones de valor
5. Parallel coordinates por colonias
6. Parallel coordinates por ageb
7.. Encharcamientos
8. Infraestructura de desalojo
9. Facturación

**Comment by paola-gp** [comment]
Necesito los links de 7 y 8. Estoy agregando 9. SIGplanning en desarrollo, 10. Versatile, 11. servicios LANCIS, 12. Protocolos LANCIS,

**Comment by paola-gp** [comment]
@aleestrada @iaga @serranoycandela @dpedroza74 @Nayita @edithvilla @yosunemiquela 

En la siguiente página encontrarán todos los enlaces a las plataformas y páginas que usamos para las presentaciones. Si nos está haciendo falta alguno, favor de reportarlo en este issue. 

# Plataformas
## https://lancisapc.wixsite.com/plataformas:

en el issue #849 encontrarán el acceso a SIGnificance y plataforma de aptitud

**Comment by Nayita** [comment]
@paola-gp 
Ya está la página de aplicaciones puesta en la página de lancis-apc en Github para que se pueda abrir desde ahí también. Quedó en el rubro de páginas de uso interno

**Comment by paola-gp** [comment]
@Nayita: revisar la última versión de la página de plataformas para agregar el URL de SIGclassifier en la página de protocolos.

**Comment by edithvilla** [comment]
queda listo
