### ISSUE TITLE
Preparar presentación en anfiteatro SEMARNAT-ONU-MA #general

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1025]
Ruta:

\PRESENTACIONES\pr_lancis\pr_lancis_pnuma_19feb2019

En esta carpeta están las carpetas de:

- insumos, se encuentran los slides de la presentación que se dio al gobierno de la Ciudad de México
- plataforma, el script 
- procesamiento, se encuentran todos los insumos para la plataforma

Actividades:

* [x]  Sincronizar dropbox en el anfiteatro @edithvilla 
* [x]  Revisar con Luis las presentaciones para poder decidir cuál se va a presentar @edithvilla @Nayita 
* [x]  Imprimir lista de asistencia @edithvilla 
- [x] Preparar el script @edithvilla 
- [x] Preparar los slides  @Nayita 
- [x] Corregir gráficas @yosunemiquela colocar las nuevas imágenes en \PRESENTACIONES\pr_lancis\pr_lancis_pnuma_19feb2019\insumos

**Comment by yosunemiquela** [comment]
ya quedaron las gráficas de sesmo en la siguiente ruta:
\PRESENTACIONES\pr_lancis\pr_lancis_pnud_19feb2019\insumos

**Comment by edithvilla** [comment]
@paola-gp 
esta es la ruta:
\PRESENTACIONES\pr_lancis\pr_lancis_pnuma_19feb2019\plataforma\guion_pr_lancis_pnuma_19feb2019

**Comment by edithvilla** [comment]
Se realizó la presentación con éxito, solo se necesita cambiar el guión con las series de tiempo

**Comment by edithvilla** [comment]
Ya está el guión listo
