### ISSUE TITLE
Realizar encuesta sobre temas de seminarios #general

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1029]
Realizar encuesta sobre seminarios en surveymonkey, 

este issue es una actividad y se puede integrar un issue #753

**Comment by edithvilla** [comment]
La encuesta se realizó en Doodle para tener una mayor posibilidad de captar los horarios que prefiere la comunidad

**Comment by edithvilla** [comment]
### Temas para seminario 

1. Facilitación en modelo multicriterio y funciones de valor
2. Python
3. QGIS
4. QGIS-Python
5. R
6. GRASS

**Comment by paola-gp** [comment]
Tablas dinámicas en Excel
Recopilación de datos en INEGI
Procedimiento para la obtención de datos vía transparencia y acceso a la información
Generación de plantillas para atlas y mapas en QGIS
Generación de estilos y edición de mapas en QGIS
Generación de gráficas para presentaciones en el anfiteatro
Generación de presentaciones para el anfiteatro
Facilitación básica
Facilitación acoplada a modelación multicriterio y funciones de valor
Ejercicios de modelos multicriterio
Como correr códigos de python desde Atom en Windows
Github y uso de repositorios compartidos
