### ISSUE TITLE
Buscar información para la presentación de ASEA #GENERAL

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#1034]
Buscar en la página de ASEA el proceso de evaluación de impacto ambiental de proyectos energéticos. 
Buscar la disponibilidad de los proyectos y los resolutivos.

El servicio social bajará estos proyectos.

La ruta donde quedarán estos proyectos será: PRESENTACIONES/pr_lancis/pr_lancis_asea_04abr2019/insumos

**Comment by Nayita** [comment]
@paola-gp 
El documento de criterios de evaluación de impacto ambiental ASEA quedó en la siguiente ruta: CARPETAS_TRABAJO/pgpriego/criterios_impacto_asea

**Comment by Nayita** [comment]
@edithvilla 
Liga para la gaceta ASEA del mes de marzo
https://www.gob.mx/cms/uploads/attachment/file/447171/Gaceta_11_2019.pdf

**Comment by Nayita** [comment]
Trámites para la evaluación de impacto ambiental en la ASEA:
MIA
Estudio de riesgo ambiental
ETJ-CUS (si es el caso)
Estudio de riesgo social

**Comment by Nayita** [comment]
Trámites ambientales ASEA
Aviso de no requerimiento de autorización en materia de impacto ambiental para actividades del sector hidrocarburos

ASEA-00-015-A

Autorización de MIA Particular del sector hidrocarburos, no incluye actividad altamente riesgosa

ASEA-00-015-B

Autorización de la MIA Regional del sector hidrocarburos, incluye actividades altamente riesgosas

ASEA-00-015-C

Autorización de la MIA Particular del sector hidrocarburos, incluye actividades altamente riesgosas

ASEA-00-024

Autorización de la MIA Regional del sector hidrocarburos, no incluye actividades altamente riesgosas

ASEA-00-017

Aviso de Cambio de Titularidad de la Autorización de Impacto Ambiental para actividades del sector hidrocarburos

ASEA-00-018

Aviso de Desistimiento de la Autorización en Materia de Impacto Ambiental para actividades del sector hidrocarburos

ASEA-00-030

Programa para la prevención de accidentes para actividades del sector hidrocarburos

ASEA-00-032

Presentación del estudio de riesgo ambiental para empresas que realizan actividades altamente riesgosas del sector hidrocarburos

ASEA-00-038

Solicitud de exención de la presentación de la Manifestación de Impacto Ambiental para actividades del sector hidrocarburos

ASEA-00-039

Modificaciones de la Obra, Actividad o Plazos y Términos Establecidos a Proyectos Autorizados en Materia de Impacto Ambiental para Actividades del sector hidrocarburos

ASEA-00-041

Recepción, evaluación y resolución del informe preventivo para actividades del sector hidrocarburos

**Comment by paola-gp** [comment]
Finalizada la presentación con ASEA
