### ISSUE TITLE
Preparar reunión ASEA anfiteatro 4 abril #general 

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#1035]
la ubicación de la presentación es: PRESENTACIONES\pr_lancis/pr_lancis_asea_04abr2019

**Comment by paola-gp** [comment]
@vichdzgeo: en insumos/timeseries/ poner el mp4 de las imágenes de satélite  y en /insumos/sig la capa de estados de la república mexicana.

**Comment by paola-gp** [comment]
@edithvilla poner vías férreas en insumos/sig

**Comment by edithvilla** [comment]
@paola-gp ya está la capa de vías férreas donde me indicaste

**Comment by paola-gp** [comment]
@CorinaCantero: limpiar tabla de permisos petrolíferos para parallel coordinates.

**Comment by paola-gp** [comment]
@Nayita: localizar el parallel coordinates que se hizo para la fundación packard de indicadores de EIA

**Comment by paola-gp** [comment]
## Generación de insumos de funciones de valor para ejemplo de SIGindex
  #### Distancia a localidades 
1. Máscara del Estado de Yucatán: **_r.mask.py raster=mascara_yuc_**      
2. Cálculo de distancias: **_r.buffer -z input=ifv_localidad_a_yuc_v1@PERMANENT output=ifv_d_localidad_yuc distances=360,720,1080,1440,1800,2160,2520,2880,3240,3600,3960 units=meters --overwrite_**

**Comment by Nayita** [comment]
Se buscó el parallel coordinates que se hizo de indicadores de EIA. Esto se hizo para un examen de candidatura. Se buscó en el browser de la computadora del Anfiteatro donde se presentó el examen pero no se encontró.

**Comment by Nayita** [comment]
Ya está la estructura de carpetas para las presentaciones. La ruta es la siguiente: PRESENTACIONES\pr_lancis\pr_lancis_asea_04abr2019
Ya está en la carpeta de plataforma/slides los primeros slides de Cananea presentadas para la presentación del tren maya.
En la carpeta de plataforma también ya está la plantilla para el guion

**Comment by CorinaCantero** [comment]
URL de mapa Parallel Coordinates de permisos petrolíferos: http://pc.magrat.mine.nu/parallel_coordinates_maps/3c5769f4af7ae1a2a4f501d223f6bb3c

**Comment by paola-gp** [comment]
@CorinaCantero: en la carpeta  SOFTWARE\sigplan\datos_prueba\sigfunction\yucatan están las versiones que se van a subir a la plataforma SIGindex para la presentación. Se utilizó la versión de USV que al día de hoy estaba en la carpeta sigfomix/procesamiento/asea  Si no es la versión con las últimas modificaciones, cambiarla y si ya es la última, indicar a que clase de USV corresponde cada categoría numérica en el mapa.

**Comment by paola-gp** [comment]
@CorinaCantero: mejorar el parallel:

- [ ] Poniendo solo la primer letra de cada columna en mayúsculas. 
- [ ] Reubicar con lo que ahora es TOTAL como la primer columna  y cambiar el nombre a Tot_Edo
- [ ] En las penúltima columna agregar la inversión. La inversión convertirla a millones de pesos (como se muestra en el archivo "permisospetroliferos.xlsx" original con una cifra decimal. 
- [ ] En la última columna agregar la capacidad. La capacidad convertirla a miles de litros  (como se muestra en el archivo "permisospetroliferos.xlsx" original sin cifras decimales.

**Comment by CorinaCantero** [comment]
@paola-gp todas las capas que están en la carpeta SIG\desarrollo\sig_fomix\procesamiento\asea\salida están actualizadas con las recomendaciones que me diste. 
Y el significado de las categorías numéricas está en:  SIG\desarrollo\sig_fomix\procesamiento\asea\capas
en archivos nombrados cat_
Capa de ríos no hay porque no hay corrientes superficiales en el estado.

**Comment by paola-gp** [comment]
@edithvilla: para FV de vegetación con SIGfunctionD


Categorías | id | FV | Categorías que incluye
-- | -- | -- | --
Acuacultura | 1 | 0.00 |  
Agricultura | 2 | 0.00 | Toda la agricultura
Cuerpo de agua | 3 | 0.00 |  
Sin vegetación | 4 | 0.00 |  
Silvicultura | 5 | 0.00 | Bosque cultivado, palmar inducido
Manglar | 6 | 1.00 |  
Pastizal | 7 | 0.25 | Todos los pastizales
Sabana | 8 | 0.75 |  
Vegetación secundaria | 9 | 0.40 | Todas las vegetaciones secundarias
Selva baja | 10 | 1.00 |  
Selva mediana | 11 | 1.00 |  
Vegetación dunas costeras | 12 | 1.00 |  
Otras | 13 | 0.50 | Tular, Petén, hidrófila, hipsófila
Urbano | 14 | 0.00 |

**Comment by CorinaCantero** [comment]
URL con correcciones: http://pc.magrat.mine.nu/parallel_coordinates_maps/56bb3552b822e100325bf29273cab75b

**Comment by paola-gp** [comment]
@vichdzgeo: avisar por este medio a @CorinaCantero cuando esté listo el script para cambiar de vector a raster

**Comment by vichdzgeo** [comment]
## Script tipo entero para cambiar de vector a raster

ruta: /SIG/desarrollo/sig_fomix/procesamiento

### se agregan dos script, deben implementar el script tipo byte, si este no satisface las necesadades de tipo entero que requieren, entonces ocupar el segundo script 

- rasterizar_vector_extent_tipo_byte_yuc.py

**Comment by CorinaCantero** [comment]
Gracias, funcionó el primero
Las capas raster Byte - Entero natural, quedan en: SIG\desarrollo\sig_fomix\procesamiento\asea\salida\entero

**Comment by paola-gp** [comment]
@edithvilla: ya están de nuevo las capas listas para sigfunction en SOFTWARE\sigplan\datos_prueba\sigfunction\yucatan

**Comment by paola-gp** [comment]
@CorinaCantero: Crear parallel coordinates con base en mapa SOFTWARE\sigplan\datos_prueba\significance\jalisco/resultados16IVCAT, con los datos input.csv.

**Comment by Nayita** [comment]
@paola-gp 
Listas carpetas con slides solicitadas. La ruta es la siguiente: PRESENTACIONES\pr_lancis\pr_lancis_asea_04abr2019\plataforma\slides
Las carpetas son: oipa, slides_megadapt, slides_tortuga
En estas carpetas slides_megadapt y slides_tortuga  están los slides de las presentaciones de SACMEX y la de tortuga completa por si quieren escoger otras diapositivas.

**Comment by CorinaCantero** [comment]
URL parallel coordinates Jalisco:
http://pc.magrat.mine.nu/parallel_coordinates_maps/39caf0278e93c151645bbd43f1848cdd

**Comment by paola-gp** [comment]
@CorinaCantero: por favor revisa los valores del parallel coordinates de Jalisco. Todos están normalizados de origen.

**Comment by CorinaCantero** [comment]
@paola-gp ¿así está bien?, solo cambié unos valores que no había copiado bien y debían estar en decimales. http://pc.magrat.mine.nu/parallel_coordinates_maps/bdfeae8b10c1359bc5d954bdb22bdc97

**Comment by CorinaCantero** [comment]
URL parallel coordinates Jalisco con correcciones:
http://pc.magrat.mine.nu/parallel_coordinates_maps/88f5e46714a8ab6482e5aa18ac0a4b11

**Comment by paola-gp** [comment]
@vichdzgeo: aquí poner ubicación de video obtenido con google earth engine

**Comment by vichdzgeo** [comment]
@paola-gp 
Coloque dos videos, espero te sean de utilidad 
ruta: 
PRESENTACIONES/pr_lancis/pr_lancis_asea_04abr2019/insumos/timeseries

**Comment by Nayita** [comment]
La presentación en pptx y pdf en la siguiente ruta: PRESENTACIONES\pr_lancis\pr_lancis_asea_04abr2019\plataforma\pr_lancis_asea_04abr2019

**Comment by Nayita** [comment]
Se cierra el issue
