### ISSUE TITLE
Preparar reunión SACMEX anfiteatro 10 de abril #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1038]
### Actividades para la preparación de la reunión con SACMEX el día 10 de abril a las 12:00 pm.

Ruta: /PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_10abr2019

1. Coordenadas paralelas, @CorinaCantero 
  **insumos**  \PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_10abr2019\insumos
- [x] AGEB ID
- [x] Índice de vulnerabilidad por inundaciones @serranoycandela 
- [x] Índice de vulnerabilidad por escasez  @aleestrada @iaga 
- [x] Presión social                                      @aleestrada @iaga 
- [x] Tamaño de la población                      @aleestrada @iaga 
- [x] Número de unidades económicas          @edithvilla  @aleestrada @iaga 

2. Preparación de Slides  @Nayita @edithvilla

**Comment by edithvilla** [comment]
@aleestrada ya está la capa de unidades económicas en la ruta: 

\PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_10abr2019\insumos\unidades_economicas

**Comment by edithvilla** [comment]
@Nayita ya tengo las carpetas de "slides_megadapt" y "slides_onu_megadapt" en la siguiente ruta:

\PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_10abr2019\insumos

**Comment by edithvilla** [comment]
ya están listos los slides en la siguiente ruta:
C:\Dropbox (LANCIS)\PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_10abr2019\plataforma\slides

**Comment by aleestrada** [comment]
Se colocó en la carpeta de insumos, una carpeta con el nombre **"cord_par_escasez"** en ella se encuentran los insumos para las coordenadas paralelas de presión social, el shape se llama **"pc_sacmex_pres_soc"**:

- Índice de presión social ---> Pres_soc
- Índice de escasez ---> Escasez
- Población por AGEB para 2017 ---> Pob_2017
- Densidad de Unidades Económicas (hectarea) ---> U_econ

**Comment by serranoycandela** [comment]
Parallel de Inundaciones/Precipitación
http://pc.magrat.mine.nu/parallel_coordinates_maps/da50ec3f759e761023f808ff8e621e7d

**Comment by CorinaCantero** [comment]
Parallel de presión social:
http://pc.magrat.mine.nu/parallel_coordinates_maps/57403b6ea1318329bf8c3c4c194b55e5

**Comment by aleestrada** [comment]
Se colocó en la carpeta de insumos, una carpeta con el nombre "cord_par_escasez" en ella se encuentran los insumos para las coordenadas paralelas de presión social, el shape se llama "pc_sacmex_ind_escasez"

**Comment by paola-gp** [comment]
@vichdzgeo  \PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_10abr2019\insumos

**Comment by CorinaCantero** [comment]
Parallel escasez:
http://pc.magrat.mine.nu/parallel_coordinates_maps/85cb34fbb193877d5f2e84b1c918dcd0

**Comment by paola-gp** [comment]
Se pusieron en los favoritos de chrome de la sala de inmersión las ligas a los cuatro parallel coordinates

**Comment by paola-gp** [comment]
@aleestrada @iaga modificar el parallel coordinates de pc_sacmex_pres_soc con la escasez y presión social normalizada (dividirla entre el valor máximo)

**Comment by paola-gp** [comment]
@aleestrada revisar el AGEB con la mayor población para ver si hay algún error

**Comment by paola-gp** [comment]
@serranoycandela: se presenta Parallel de Encharcamientos/Precipitación
http://pc.magrat.mine.nu/parallel_coordinates_maps/7c930a9e6348dfff037faac6d5383025
el shape base sin quitar ageb_id es:
Dropbox/SIG/desarrollo/sig_megadapt/procesamiento/fuzzy_inunda/parallel/agebs_cdmx_s_preci_encharca.shp

pero hay que quitar capacidad, encharcamientos, inundaciones y normalizar V_encharca (dividirla entre el máximo)

**Comment by paola-gp** [comment]
@CorinaCantero: rehacer el parallel de escasez con base en las modificaciones de @aleestrada

**Comment by serranoycandela** [comment]
Listo
Parallel de Encharcamientos/Precipitación
http://pc.magrat.mine.nu/parallel_coordinates_maps/33d272b4513e1452942e1759090a7fd6
el shape base sin quitar ageb_id es:
Dropbox/SIG/desarrollo/sig_megadapt/procesamiento/fuzzy_inunda/parallel/agebs_cdmx_s_preci_encharca.shp

**Comment by paola-gp** [comment]
@edithvilla y @Nayita la slide sl_4 tiene errores de traducción importantes que hay que corregir. La slide sl_10_03 debe decir "presupuesto **máximo**"

**Comment by paola-gp** [comment]
@edithvilla y @serranoycandela: los parallel coordinates de encharcamientos va en la pantalla 4, la de drenaje http://patung.mine.nu/~evilla/tributarias/tramos_tributarios.html en la 5 y la de escasez en la 6.

**Comment by aleestrada** [comment]
Se modificó el parallel coordinates de pc_sacmex_pres_soc con la escasez y presión social normalizada (dividirla entre el valor máximo).

Se realizó lo mismo para el parallel coordinates pc_sacmex_ind_escasez.

La modificación se realizó en los archivos wgs84.


De igual forma se verificó la población máxima, que se encuentra en el ageb 6815, este ageb corresponde al Reclusorio Oriente, es debido a esto que tiene tanta población.

**Comment by CorinaCantero** [comment]
Parallels con correcciones:
Escasez: http://pc.magrat.mine.nu/parallel_coordinates_maps/d8bc82fe2721a16c63c8f93c0b0bd964
Presión social: http://pc.magrat.mine.nu/parallel_coordinates_maps/cce3971e5adf2af15e2d741292df0931

**Comment by edithvilla** [comment]
ya se encuentra la lista de asistencia de la reunión en la siguiente ruta: 
\PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_10abr2019\logistica

**Comment by Nayita** [comment]
La presentación final está en la siguiente ruta: PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_10abr2019\plataforma
La minuta y el audio de la reunión está en la siguiente ruta: PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_10abr2019\logistica

Se cierra el issue
