### ISSUE TITLE
Participar en el Taller Plan Integral de sustentabilidad # general

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1041]
Participar en el "Taller Plan Integral de sustentabilidad"

Lunes 22 de abr de 2019 10am - 2pm

@paola-gp ya está creada la carpeta: curso_coodinacion_sustentabilidad en la siguiente ruta:

CAPACITACION/cursos_no_formales/curso_coordinacion_sustentabilidad

**Comment by paola-gp** [comment]
Meta planeada por Luis y Paola:
Destinar óptimamente los recursos humanos, financieros y técnicos para las tareas sustantivas del lanzamiento de la coordinación

Meta planteada por CUS
Definir las directrices generales para incorporar y fortalecer el tema de la sustentabiblida de las tareas sustantivas de la universidad: incluyendo la gestión de los espacios de la universidad y la vinculación en contexto nacional e internacional

**Comment by edithvilla** [comment]
Taller concluido
