### ISSUE TITLE
Preparar presentación para el gobierno de la CDMX 25 de abril#general

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#1042]
La presentación y  todos los insumos quedaran en la siguiente ruta: presentaciones/pr_lancis/pr_lancis_gobcdmx_25abr2019

Actividades

- [x] Poner insumos para la presentación
- [x] Escoger slides y elaborar slides si es el caso
- [x] Elaborar presentación y guión

**Comment by Nayita** [comment]
Listos los insumos:

slides_asea
slides_gobcdmx
slides_sacmex_10abr
slides_sacmex_20feb

En cada carpeta están los pptx de las presentaciones correspondientes.

En procesamiento ya están en pptx los mapas enviados por Yosune

**Comment by yosunemiquela** [comment]
Los shapefiles para generar los mapas están en la siguiente ruta:

work/PRESENTACIONES/pr_lancis/pr_lancis_gobcdmx_25abr2019/insumos
@serranoycandela

**Comment by edithvilla** [comment]
### suelo de conservación

C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\sleuth\Suelo de conservación

**Comment by edithvilla** [comment]
@vichdzgeo @CorinaCantero 

### modelo de crecimiento

/SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/urbanizacion_escorrentia/Experimentos

**Comment by edithvilla** [comment]
El guión en pptx se encuentra en el archivo:

pr_lancis_gobcdmx_25abr2019.pptx

ruta: \PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_25abr2019\procesamiento

**Comment by Nayita** [comment]
Listos slides hechos y numerados conforme a guion en plataforma. La ruta es la siguiente: \PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_25abr2019\plataforma\slides

**Comment by Nayita** [comment]
Listos los slides nuevos y correcciones. La ruta es la siguiente: \PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_25abr2019\plataforma\slides

**Comment by edithvilla** [comment]
Ya se encuentra escaneada la lista de asistencia en la siguiente ruta:

\PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_25abr2019\logistica

**Comment by edithvilla** [comment]
Queda pendiente la eliminación de la cuenta del dropbox de la máquina del anfiteatro por que dejó de funcionar la aplicación de creston

**Comment by Nayita** [comment]
Concluida la elaboración de la presentación en pptx y pdf. Ruta: \PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_25abr2019\plataforma\
Concluida la minuta. Ruta: \PRESENTACIONES\pr_lancis\pr_lancis_gobcdmx_25abr2019\logistica

**Comment by edithvilla** [comment]
@Nayita 

esta es la liga del escenario tendencial

http://patung.mine.nu/~fidel/boundary_object/crecimiento_urbano/crecimiento_urbano_bau.html

y esta del escenario sin restricciones

http://patung.mine.nu/~fidel/boundary_object/crecimiento_urbano/crecimiento_urbano_ex_0.html

**Comment by Nayita** [comment]
Lista el slide del 2016. 
El anfiteatro está fuera de uso por problemas técnicos. No se pudieron tomar los recortes de pantalla del escenario tendencial y sin restricciones.
Fidel ayudará para hacer el truco y poder tomarlas para completar la presentación.

**Comment by edithvilla** [comment]
Ligas con las imágenes del año 2016 de los escenarios

http://patung.mine.nu/~fidel/boundary_object/crecimiento_urbano/crecimiento_urbano_bau_60.html
http://patung.mine.nu/~fidel/boundary_object/crecimiento_urbano/crecimiento_urbano_ex_0_60.html

**Comment by Nayita** [comment]
Lista la presentación final y el pdf
