### ISSUE TITLE
Hacer listado de protocolos aplicables a MEGADAPT#MEGADAPT

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#1043]
El listado terminado estará disponible en este issue.

**Comment by Nayita** [comment]
Listado de protocolos aplicables al proyecto MEGADAPT

•	Protocolo de asignación de responsabilidades en proyectos colaborativos
•	Protocolo de organización de activos de información
•	Protocolo de generación de gráficas y mapas con salida en HTML
•	Protocolo para el manejo de la información geográfica
•	Protocolo para el manejo de bases de datos
•	Protocolo de logística
•	Protocolo de recepción y entrega de activos de información
•	Protocolo de uso de repositorios documentales

**Comment by EsmeraldaOsejo** [comment]
¡Perfecto! Muchas gracias @Nayita
