### ISSUE TITLE
Preparar reunión para el gobierno de la cdmx el día 28jun2019 #general

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1055]
@paola-gp ya está creada la carpeta para la presentación para el gobierno:

ruta: /PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019

está creada la estructura para presentación en anfiteatro
/insumos
/logistica
/plataforma
/procesamiento

**Comment by Nayita** [comment]
Listos los todos los documentos en insumos

**Comment by Nayita** [comment]
Revisar organización del gobierno de la CDMX todas las dependencias de la administración pública, incluyendo la Secretaría de Gestión Integral de Riesgos y Protección Civil, y las alcaldías.

El consejo de resiliencia  también está conformado por el titular de la coordinación nacional de protección civil del gobierno federal. Importante dar una revisión rápida a eso

**Comment by Nayita** [comment]
@CorinaCantero 
También será necesario revisar los órganos desconcentrados y  organismos descentralizados

**Comment by Nayita** [comment]
Listo el documento de puntos importantes de los siguientes documentos: Consejo de Resiliencia, Ley de GIRPC y Plan de Gobierno 2019-20124. Ruta: PRESENTACIONES\pr_lancis\pr_lancis_sgirpc_28jun2019\insumos\resumen_consejo_resiliencia

**Comment by Nayita** [comment]
Michelle Montijo trabaja en la DGVS-SEDEMA

**Comment by Nayita** [comment]
Listos conceptos solicitados:

El Marco de Sendai para la Reducción del Riesgo de Desastres 2015-2030 fue aprobado en la Tercera Conferencia Mundial de las Naciones Unidas sobre la Reducción del Riesgo de Desastres, celebrada del 14 al 18 de marzo de 2015 en Sendai, Miyagi (Japón).

Nueva Agenda Urbana es una guía para orientar los esfuerzos en materia de desarrollo de las ciudades para una amplia gama de actores (estados, líderes urbanos y regionales, donantes, programas de las Naciones Unidas, academia, la sociedad civil, entre otros) para los próximos 20 años.
La Nueva Agenda Urbana (NAU) busca promover ciudades más incluyentes, compactas y conectadas mediante la planificación y diseño urbano, gobernanza y legislación urbana, y la economía urbana. Procura crear un vínculo de refuerzo recíproco entre urbanización y desarrollo.
La Nueva Agenda Urbana se aprobó en la Conferencia de las Naciones Unidas sobre la Vivienda y el Desarrollo Urbano Sostenible (Hábitat III) celebrada en Quito, Ecuador, el 20 de octubre de 2016. La Asamblea General de las Naciones Unidas refrendó la Nueva Agenda Urbana en su sexagésimo octava sesión plenaria de su septuagésimo primer período de sesiones, el 23 de diciembre de 2016.

**Comment by Nayita** [comment]
El objetivo del Consejo de Resiliencia es impulsar la integración y elaboración de instrumentos y proyectos innovadores para la construcción de Resiliencia en la Ciudad de México y su Zona Metropolitana.

**Comment by Nayita** [comment]
Listo el documento desde ayer. Ruta: PRESENTACIONES\pr_lancis\pr_lancis_sgirpc_28jun2019\insumos\resumen_docu_resiliencia

También están en insumos los archivos pdf del Marco de Sendai y la Nueva Agenda Urbana.

**Comment by paola-gp** [comment]
Parallel coordinates @yosunemiquela 
P1. Cuenca 
P2. Cuenca agregada de JA

1. Área de la cuenca
2. % de cobertura forestal original
3. % de cobertura agrícola original
4. % de cobertura urbana original
5.% de crecimiento urbano
6. % de cobertura forestal afectada
7. % cobertura agrícola afectada
8 % de cambio en la respuesta hidrológica
9. Población afectada (solo en el segundo parallel)

**Comment by paola-gp** [comment]
Parallel coordinates @serranoycandela 

Shapefile con:

Numero de intervenciones SACMEX
Vulnerabilidad
Tamaño de la población
Pobreza (cinco categorías)

**Comment by paola-gp** [comment]
@yosunemiquela: generar figura de alta resolución con los resultados de wrf.

**Comment by Nayita** [comment]
Lista la presentación en plantilla en la siguiente ruta:  C:\Dropbox (LANCIS)\PRESENTACIONES\pr_lancis\pr_lancis_sgirpc_28jun2019\procesamiento\presentacionv1_plantilla

**Comment by aleestrada** [comment]
@iaga

**Comment by aleestrada** [comment]
Se agregó en la siguiente ruta:

/PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/coordenadas_paralelas

La capa con los datos de población y nivel de pobreza para el año 2015 a nivel ageb.

**Comment by iaga** [comment]
Se agregaron en la ruta:

/PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/escasez

Las capas:

|Capa|Origen|Descripción|
|--|--|--|
reportes_falta_agua_ageb_2017|\SIG\desarrollo\sig_megadapt\entregables\reportes_falta_agua|Frecuencia de reportes o quejas para el año 2017
tp_dsa_agebs_cdmx_v3|\SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\insumos\dias_sagua|Días sin agua o tiempo de respuesta de la queja para el año 2017

**Comment by Nayita** [comment]
Lista presentación en plantilla con todas las diapositivas no terminadas

**Comment by yosunemiquela** [comment]
Ya está la figura de alta resolución con los resultados de wrf.
ruta: /PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/diferencias_temp_wrf.png
@paola-gp

**Comment by yosunemiquela** [comment]
Ya está el shape para P1. Cuencas coordenadas paralelas

ruta: /PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/insumos/coordenadas_paralelas
/cuencas
@paola-gp 
Campos:

1. ID (id de la cuenca)
2. area (km2)
4. urbano2014: Representa el porcentaje de área urbana dentro de cada cuenca en 2014.
5. urbano2060: Representa el porcentaje de área urbana dentro de cada cuenca en 2060.
4. dif_urbano: Es la diferencia % de urbano2060 - urbano2014
5. agrico2014: Representa el porcentaje de área agricola dentro de cada cuenca en 2014. 
6. agrico2060: Representa el porcentaje de área agricola dentro de cada cuenca en 2060.
7. dif_agrico: Es la diferencia de agrico2060 - agrico2014
8. bosque2014: Representa el porcentaje de área forestal dentro de cada cuenca en 2014.
9. bosque2060: Representa el porcentaje de área forestal dentro de cada cuenca en 2060. 
10. dif_bosque: Es la diferencia % de bosque2060 - bosque2014
11. escorre2014: escorrentía (millones de m3) en 2014
12: escorre2060: escorrentía (millones de m3) en 2060
13. dif_escorre: Es la diferencia de escorre2060 - escorre2014 (millones de m3)

NB. Para el número 13 se decidió simplemente presentar los resultados en t{erminos de la diferencia en millones de m3 ya que algunas cuencias tenían porcentajes de cambio de 9000%. Consideramos es más sencillo traducir el resultado en términos absolutos.

**Comment by paola-gp** [comment]
> Ya está la figura de alta resolución con los resultados de wrf.
> ruta: /PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/diferencias_temp_wrf.png

@yosunemiquela:  ya se agregó a la presentación con el título: Modelo de pronóstico atmosférico. Se debería agregar algo mas a la diapositiva?

**Comment by paola-gp** [comment]
> ruta: /PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/insumos/coordenadas_paralelas
> /cuencas

@vichdzgeo aquí están los datos

**Comment by paola-gp** [comment]
@yosunemiquela: no estamos pudiendo crear el parallel coordinates porque hay celdas vacías. 

> Ya está el shape para P1. Cuencas coordenadas paralelas
> 
> ruta: /PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/insumos/coordenadas_paralelas
> /cuencas

**Comment by yosunemiquela** [comment]
Ya quedó el nuevo shape  para P1. Cuencas coordenadas paralelas
con los cambios acordados (rellenar espacios vacíos con 0 y añadir una columna del procentaje de cambio en escorrentía (además del cálculo de la diferencia).

ruta: /PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/insumos/coordenadas_paralelas
/cuencasV2
@paola-gp

**Comment by iaga** [comment]
@Nayita Se agregaron a la ruta: 

presentaciones/pr_lancis/pr_lancis_sgirpc_28jun2019/procesamiento/vuln_escasez

los siguientes archivos:

- vuln_escasez_poblacion.csv
- vuln_escasez_pobreza.csv
- vuln_escasez_cdmx

Nota: "inicial", "aumentado" y "máximo" hacen referencia al presupuesto asignado.

**Comment by vichdzgeo** [comment]
## Parallel Coordinates Actualizados

Los datos se encuentran en la siguiente ruta:
PRESENTACIONES\pr_lancis\pr_lancis_sgirpc_28jun2019\insumos\coordenadas_paralelas\cuencas_actualizadas

Se tienen cuatro propuestas conforme a la visualización 

- parallel_lb_14_60_log_final 
  - El campo Tasa_esco se calculó con ->  (  log10(  "escorre206"  )  -  log10(  "escorre201"  )   )  * 100 
- parallel_lb_14_60_dif_final
 -  El campo Dif_esco se calculó con -> "escorre206"  -  "escorre201" 
- parallel_lb_2014_final
 - El campo Por_esco se calculó con ->  (  ( "escorre206"  -  "escorre201" )   /    ( "escorre201"  )  ) *100
- parallel_lb_2060_final
 - El campo Por_esco se calculó con ->  (  ( "escorre206"  -  "escorre201" )   /    ( "escorre206"  )  ) *100

parallel_lb_14_60_log_final 

http://pc.magrat.mine.nu/parallel_coordinates_maps/943aeda90dfc9e7cced82370230f9a6f

parallel_lb_14_60_dif_final

http://pc.magrat.mine.nu/parallel_coordinates_maps/9444eacbe6215c67e24a33c2689237db

parallel_lb_2014_final

http://pc.magrat.mine.nu/parallel_coordinates_maps/7b4a4a762964dbc524c67a624a49c8dd

parallel_lb_2060_final

http://pc.magrat.mine.nu/parallel_coordinates_maps/fd0731e5bee3614b93a2644ce000b95b

@aleestrada @paola-gp @iaga @edithvilla

**Comment by yosunemiquela** [comment]
Ya quedó la nueva figura con la falta ortogáfica corregida. La ruta:

PRESENTACIONES/pr_lancis/pr_lancis_sgirpc_28jun2019/insumos/figuras/diferencias_temp_wrf_V2
@paola-gp

**Comment by Nayita** [comment]
Listas las gráficas de presupuesto "inicial", "aumentado" y "máximo"  de  los  siguientes archivos:

vuln_escasez_poblacion.csv
vuln_escasez_pobreza.csv

Ruta:
presentaciones/pr_lancis/pr_lancis_sgirpc_28jun2019/procesamiento/vuln_escasez

**Comment by serranoycandela** [comment]
Hice un parallel coordinates con los datos de vulnerabilidad que rescaté de una presentación antigua

http://pc.magrat.mine.nu/parallel_coordinates_maps/d5d701641a43eb1f93b552a78409a6cc 

la verdad creo que así no ayuda mucho a entender nada ni luce el parallel.

por otro lado hice tres mapas contando población en cada categoría de vulnerabilidad

Enfoque en nueva infraestructura
![vulnera_new_infra](https://user-images.githubusercontent.com/12860576/60298347-ed753d00-98ef-11e9-8136-c8faf4b4494b.png)

Enfoque en mantenimiento
![vulnera_mantenimiento](https://user-images.githubusercontent.com/12860576/60298369-0251d080-98f0-11e9-8729-8ecdcc680589.png)

Enfoque en atención ciudadana
![vulnera_atencion_ciudadana](https://user-images.githubusercontent.com/12860576/60298409-1269b000-98f0-11e9-8f98-859813437088.png)

**Comment by serranoycandela** [comment]
ok segunda versión de esos mapas

Enfoque en nueva infraestructura
![vulnera_nueva_infraestructura](https://user-images.githubusercontent.com/12860576/60300226-23b4bb80-98f4-11e9-89bb-1e79cdc45672.png)

Enfoque en mantenimiento
![vulnera_mantenimiento](https://user-images.githubusercontent.com/12860576/60300246-3202d780-98f4-11e9-8e64-25b9da915ffa.png)

Enfoque en atención ciudadana
![vulnera_atencion_ciudadana](https://user-images.githubusercontent.com/12860576/60300275-41822080-98f4-11e9-9512-c1acbdb11308.png)

**Comment by serranoycandela** [comment]
tercer versión 

Enfoque en nueva infraestructura
![vulnera_nueva_infraestructura2](https://user-images.githubusercontent.com/12860576/60305870-bc066c80-9903-11e9-927d-e3b5b413741d.png)

Enfoque en mantenimiento
![vulnera_mantenimiento2](https://user-images.githubusercontent.com/12860576/60305888-cb85b580-9903-11e9-8d6c-6f4588b7e443.png)

Enfoque en atención ciudadana
![vulnera_atencion_ciudadana2](https://user-images.githubusercontent.com/12860576/60305907-d9d3d180-9903-11e9-9b22-fd3c3a6e63d2.png)

**Comment by edithvilla** [comment]
Ya está escaneada la lista de asistencia:

\PRESENTACIONES\pr_lancis\pr_lancis_sgirpc_28jun2019\logistica

asistencia_sgirpc_28jun2019.pdf

**Comment by Nayita** [comment]
Lista la presentación de acuerdo al guion y su respectivo pdf, así como presentación para distribución. Ruta: PRESENTACIONES\pr_lancis\pr_lancis_sgirpc_28jun2019\plataforma

pr_lancis_sgirpc_28jun2019.pptx
pr_lancis_sgirpc_28jun2019.pdf
pr_lancis_sgirpc_28jun2019_vdistrib.pptx
pr_lancis_sgirpc_28jun2019_vdistrib.pdf

**Comment by edithvilla** [comment]
Ya está lista la figura:

\PRESENTACIONES\pr_lancis\pr_lancis_sgirpc_28jun2019\insumos\figuras
Sistema_inf_y_transparencia Aeropuerto_jun2019_vdistribucion.png

**Comment by Nayita** [comment]
Enviada la presentación de distribución al personal de la SGIRPC

**Comment by Nayita** [comment]
Lista la presentación en pdf y pptx y la versión de la distribución en la siguiente ruta: 
\PRESENTACIONES\pr_lancis\pr_lancis_sgirpc_28jun2019\plataforma.
Archivos:
pr_lancis_sgirpc_28jun2019.pdf
pr_lancis_sgirpc_28jun2019.pptx
pr_lancis_sgirpc_28jun2019_vdistrib.pdf
pr_lancis_sgirpc_28jun2019_vdistrib.pptx
