### ISSUE TITLE
Mejorar el mapa para la figura de un artículo #MEGADAPT

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#1057]
El mapa y la figura quedarán en la siguiente ruta: 
\PUBLICACIONES\preparacion_articulo\social_mobilization_2019\figuras

Actividades:

1. Quitar el nombre de las alcaldías
2. Señalar sólo la alcaldía de Coyoacán e Iztapalapa
3. Hacer tres categorías con sus colores correspondientes para consumo de agua
4. Poner círculos para protestas dentro de las alcaldías. Dentro de los círculos poner el número de protestas.

**Comment by Nayita** [comment]
Etiquetas del mapa:
Water consuption (lts./person day)
Number of protests in the media (2011-2015)

**Comment by edithvilla** [comment]
Primera versión, falta que el encargado la apruebe

![image](https://user-images.githubusercontent.com/25182051/61735151-f9b2b580-ad48-11e9-8b45-9924ef3aca3b.png)

**Comment by edithvilla** [comment]
Se hicieron correcciones en la figura (24 de junio, 2019):

![image](https://user-images.githubusercontent.com/25182051/61888452-1f66c880-aec9-11e9-9eb1-daa4c89fea58.png)

**Comment by edithvilla** [comment]
Se aprobó la figura

**Comment by edithvilla** [comment]
@CorinaCantero 

ruta de mapas y proyecto en qgis: \PUBLICACIONES\preparacion_articulo\social_mobilization_2019\figuras\insumos

en esta ruta voy a colocar los mapas y el proyecto de qgis

ya figura ya creada se coloca aquí:

\PUBLICACIONES\preparacion_articulo\social_mobilization_2019\figuras

puedes sincronizar esta carpeta: figuras

**Comment by edithvilla** [comment]
@Nayita por favor colocar la figura insumo en:

\PUBLICACIONES\preparacion_articulo\social_mobilization_2019\figuras

**Comment by edithvilla** [comment]
Esta es la figura que hay que hacer de cero:

![image](https://user-images.githubusercontent.com/25182051/62157583-23348980-b2d3-11e9-9289-4c00a1c567bc.png)

**Comment by Nayita** [comment]
Lista la figura en el lugar indicado se llama fi_mapa_v1

**Comment by edithvilla** [comment]
@CorinaCantero 

ruta de capas para la figura:

\PUBLICACIONES\preparacion_articulo\social_mobilization_2019\figuras\insumos\shapes\AZP


capas:
1. Cuerpos de Agua Actualizado
2. Canales Actualizado
3. AZP_Pueblos_y_Colonias

\PUBLICACIONES\preparacion_articulo\social_mobilization_2019\figuras\insumos

Zonas_productivas_2013

**Comment by CorinaCantero** [comment]
En la siguiente ubicación están 4 opciones para la nueva versión de la figura: 
PUBLICACIONES\preparacion_articulo\social_mobilization_2019\figuras
-fi_mapa_sincdmx   que va junto con  -fi_cdmx
-fi_mapa_v1
-fi_mapa_v2
-fi_mapa_v3

**Comment by edithvilla** [comment]
los insumos de esta figura se encuentran también respaldados en la siguiente ruta:
\MEGADAPT\mega_insumos\julio_2019\beth_tellman

**Comment by edithvilla** [comment]
Se aceptó la figura:

fi_mapa_v3

![image](https://user-images.githubusercontent.com/25182051/62314048-d1693c00-b457-11e9-9d5a-dc595a97aedd.png)

**Comment by edithvilla** [comment]
Todo lo referente a la figura: fi_mapa_v3 se cambia de ruta:

\PUBLICACIONES\preparacion_articulo\ecology&society_2019

El título del artículo es:

Loss and social-ecological transformation: Pathways of change in Xochimilco, Mexico

Revista: Journal Ecology and Society
