### ISSUE TITLE
Preparar reunión de megadapt para el 20 de septiembre #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1064]
Carpeta para la presentación
ruta: /PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_20sep2019

### Logística 

- [x] Lista de asistencia

- [x] Minuta

**Comment by berthahdz** [comment]
> Carpeta para la presentación
> ruta: /PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_20sep2019
> 
> Logística
> 
> * [x]  Lista de asistencia
> * [x]  Minuta

Hola @edithvilla .... no entiendo.... dónde descargar los archivos que dices que ya subiste o cómo funcionar?? gracias

**Comment by berthahdz** [comment]
Tener listo la base de datos social/económica para mostrar las gráficas en la presentación: ir puliendo los indicadores @aleestrada @iaga

**Comment by berthahdz** [comment]
Diseño de la presentación @paola-gp no pude agregar a Fidel

**Comment by berthahdz** [comment]
Tod@s: Sesión de preparación y ensayo de la presentación en la Sala de Inmersión-17,18 y 19 de septiembre- favor de tener la información necesaria. Gracias!

**Comment by paola-gp** [comment]
@serranoycandela

**Comment by berthahdz** [comment]
Operación de pantallas: Me dijeron que todos recibieron capacitación pero falta asignar quién se encargaría de eso, tu tienes idea @paola-gp ? Gracias!

**Comment by edithvilla** [comment]
@berthahdz te acabo de compartir la carpeta del dropbox para que puedas tener acceso a los archivos.

Te compartí la carpeta "pr_megadapt_gobcdmx_20sep2019"

**Comment by paola-gp** [comment]
@berthahdz: sugiero que se enlisten todas las actividades necesarias para la presentación: 
logística en un solo comentario, integración de la presentación en otro, generación de insumos para la presentación en otro.  Una vez que se tenga todo, se puede repartir conforme a responsabilidades ya establecidas, eficiencia y experiencia. un solo item por comentario hace muy difícil después dar seguimiento a las necesidades y faltantes.

**Comment by edithvilla** [comment]
@berthahdz 

Atendiendo tu solicitud verbal sobre las fotos que aparecen en la presentación que se dio a los diputados, te comento que no tenemos los archivos originales de las fotos. Lo que puedo compartirte es la presentación en power point en donde las imágenes están insertadas en una diapositiva y de ahí  las puedas tomar.

la presentación esta en la siguiente ruta:

/PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_20sep2019/insumos

archivo: 

Congreso_ Megolopolis_HE_megadapt_jul15.pptx

**Comment by aleestrada** [comment]
@Nayita y @edithvilla 
podrían por favor ayudarnos a pasar las dispositivas del archivo: pr_megadapt_20sept_adicionales que se encuentran en la dirección: \PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\insumos  
al estilo de slides para la presentación en el anfiteatro. Gracias

**Comment by Nayita** [comment]
@aleestrada 
No me dijiste el nombre del archivo pero supongo que es pptx que tiene la fecha de la presentación

**Comment by Nayita** [comment]
@aleestrada 
Listas las cuatro slides solicitadas. Ruta: PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_20sep2019/procesamiento/pr_megadapt_20sept_adicionales

Las puse ahí para que no hubiera confusión con los slides que ya tienen en la carpeta de plataforma

**Comment by edithvilla** [comment]
@aleestrada 

ya están listas las imágenes del modelo multicriterio de abastecimiento y desalojo. Los cambios se realizaron con base en el modelo que se utilizó para el artículo de sesmo

ruta: /presentaciones/pr_megadapt/pr_megadapt_gobcdmx_20sep2019/insumos

archivos: 
F_Multicriterio_SacmexAbastecimiento_sesmo_17sep2019.png
F_Multicriterio_SacmexDesalojo_sesmo_17sep2019.png


Los archivos de illustrator se encuentran en:
\DISENO\diseno_2019\megadapt_iai\Informe SACMEX

**Comment by aleestrada** [comment]
@Nayita por favor podrías convertir las diapositivas de la presentación a imágenes:
\PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\insumos\pr_megadapt_20sept

También pidió Luis que revises que todas tengan el mismo tipo y tamaño de letra, que se revise que las imágenes queden más o menos del mismo tamaño.

Hay una diapositiva, (la núm 27) que encontré la diapositiva ya en imagen (la que aparece está mal, pero es para que te des una idea), pero no pude localizarla en  ppt por si es necesario modificarla, ¿podrías también ayudarnos a localizarla si es que se requiere modificar, por favor?

**Comment by Nayita** [comment]
@aleestrada hago las siguientes precisiones a lo que me solicitas:

- Hay dos diapositivas iniciales con el mismo nombre. La diferencia son los logos y ya se hicieron esos slides por lo que no veo necesario hacerlos.

- Hay varias diapositivas que ya son slides. Esos ya no se tienen que hacer slides. Se utilizan los slides originales

- Sólo se hacen slides las diapositivas modificadas o creadas desde cero

- Por protocolo debieron utilizar la plantilla de presentaciones. Así no debería de haber errores en la tipografía

- Importante solicitar ayuda para que no se trabaje doble innecesariamente

**Comment by Nayita** [comment]
@aleestrada 
Listos los slides de las diapositivas corregidas. Ruta: C:\Dropbox (LANCIS)\PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\procesamiento\pr_sgirpc_19sep2019

**Comment by Nayita** [comment]
@aleestrada @yosunemiquela 
Diapositiva de Yosune de resultados ya está en plataforma y es la sl_100.png. Ruta:PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\plataforma\slides

**Comment by Nayita** [comment]
@aleestrada 
Listas las correcciones de las diapositivas. Ya en plataforma sustituidas con la numeración correspondiente

**Comment by Nayita** [comment]
@aleestrada 
Lista la diapositiva con el título de Dinámica. Ya está puesta en la siguiente ruta: PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\plataforma\slides
el archivo se llama sl_pantalla3_dinamica_03.png

**Comment by Nayita** [comment]
@aleestrada 
Lista slide sl_89 con las correcciones indicadas. Ruta:PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\plataforma\slides

**Comment by edithvilla** [comment]
@Nayita 

se necesita hacer los slides para las diapositivas: 14, 15 y 16 del archivo del power point: pr_sgirpc_19sep2019.pptx
el archivo está en la siguiente ruta: \PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\procesamiento

nombrar los archivos como sl_101, sl_102, sl_103 o utilizar un número que no se tengan

**Comment by Nayita** [comment]
@edithvilla @aleestrada 
Listas las diapositivas ya en plataforma. Se nombraron con los números que se señalaron sl_101, sl_102, sl_103. Ruta: PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\plataforma\slides

**Comment by aleestrada** [comment]
La presentación consta de tres partes:

 1) La primera está contruida con una serie de slides y un guión: en ella se presentó una introducción y la parte teórica del modelo MEGADAPT. Se ubica en: \PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\plataforma\guion_megadapt_20sept2019hallie

 2) La segunda parte se realizó utilizando la plataforma de tableau: en ella se presentaron gráficas y mapas de los principales resultados del modelo (https://github.com/sostenibilidad-unam/SHV/issues/151). Se ubica en:
\SIG\desarrollo\sig_megadapt\procesamiento\tableau\workbooks\finales_hallie

3) La tercera parte está contruida con una serie de slides y un guión: en ella se presentaron las preguntas con las preguntas que sirvieron como cierre de la presentación y como enlace con las siguientes presentaciones. Se ubica en: \PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\plataforma\guion_megadapt_20sept2019_preguntas

**Comment by Nayita** [comment]
@aleestrada 
Lista la presentación en pptx. Revísala y da tu visto bueno. La ruta: PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\plataforma
Archivo: pr_megadapt_gobcdmx_20sep2019.pptx

**Comment by Nayita** [comment]
Lista la presentación en pptx y pdf en la siguiente ruta: PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_20sep2019\plataforma.
Archivos: pr_megadapt_gobcdmx_20sep2019.pptx
               pr_megadapt_gobcdmx_20sep2019.pdf
