### ISSUE TITLE
Preparar reunión de Indicadores/MEGADAPT para el 11 de octubre #MEGADAPT

### ISSUE THREAD

**Issue by berthahdz** [lancis-apc/planeacion-colaborativa#1067]
@edithvilla @Nayita alguna puede enviarme el "machote" con los logos para hacer una invitación formal al evento. gracias!

**Comment by berthahdz** [comment]
Rainwater harvesting scenario
a. Programming
b. Outputs scarcity, flooding) in relation to indicators of interest to them and us (poverty, population density, unidades económicas, niveles de escolaridad) 
 @serranoycandela @yosunemiquela @aleestrada

**Comment by berthahdz** [comment]
Visualizations
a. Geographic distribution of vulnerability changes
b. Output variables in relation to indicators of interest (socio-economic) tables/graphs
c. Examples of how to illustrate results in context of resilience 
@aleestrada @iaga

**Comment by berthahdz** [comment]
Revisar Política de Resiliencia y Plan de Sostenibilidad Hídrico @heakin

**Comment by berthahdz** [comment]
Coordinar Agenda - with César
Varibles Modelos Mentales para dinámica del taller -with Hallie 
Recopilar intereses (indicadores) -by email- 
Resultados cuestionarios -survey monkey- 
Invitación formal -Rev Luis
Nota informativa -Rev Luis
@berthahdz @luis-supremo

**Comment by edithvilla** [comment]
@berthahdz no contamos con un "machote" de invitación formal. ¿Qué logos necesitas?

ya creamos la carpeta para la presentación la ruta es la siguiente:

/PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_11oct2019

en cuanto me indique que logos necesitas, lo colocaré en la siguiente ruta:

/PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_11oct2019/insumos

**Comment by berthahdz** [comment]
> @berthahdz no contamos con un "machote" de invitación formal. ¿Qué logos necesitas?
> 
> ya creamos la carpeta para la presentación la ruta es la siguiente:
> 
> /PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_11oct2019
> 
> en cuanto me indique que logos necesitas, lo colocaré en la siguiente ruta:
> 
> /PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_11oct2019/insumos

No tengo acceso al dropbox, me pudes dar... recuerda que no tengo espacio asi que tengo que entrar con un link que me permita descargar y subir cosas ...... 

Me puedes indicar tambien la ruta para subir diapositivas para que las vayan transformando para las pantallas /Hallie ya envio 2. Gracias!

**Comment by Nayita** [comment]
@berthahdz 
La ruta para subir diapositivas es la siguiente: /PRESENTACIONES/pr_megadapt/pr_megadapt_gobcdmx_11oct2019/procesamiento
Se te compartirá la carpeta de esta presentación y la carpeta de la presentación anterior por si necesitas algún insumo de ahí

**Comment by berthahdz** [comment]
Pueden rastrear todas las diapositivas que tenga Luis sobre indicadores @edithvilla @Nayita gracias! es para que armemos la introduccion. Gracias

**Comment by berthahdz** [comment]
Transformar slides que vienen de los participantes. (Primera parte de la reunión) -Deadline para los participantes 9 de octubre- pero es posible que nos la den ese mismo día :/ .... @edithvilla @Nayita 
Gracias!

**Comment by Nayita** [comment]
@berthahdz 
Se consultó con Luis acerca de las diapositivas de indicadores y nos dijo que ya todas están muy vistas. Por lo que él hará unas diapositivas nuevas.
Por lo que comentas de los slides de los participantes te envío el protocolo para que leas los requerimientos de las diapositivas y los tiempos y se los comuniques. Por protocolo eso significaría que la entrega tiene que ser mañana 8 de octubre:
https://lancis-apc.github.io/planeacion-colaborativa/protocolo_servicioanfiteatro_ext.html

Te adjuntamos en insumos la plantilla de la presentación que usamos para anfiteatro para que la distribuyas. Por aquello del tipo de letra y para que toda la presentación se vea unificada.

Por la operación de la plataforma es IMPOSIBLE que nos den las diapositivas el mismo día de la presentación. Si se da el caso, esa persona conectará su computadora y expondrá sus diapositivas en una de las pantallas.

**Comment by Nayita** [comment]
@berthahdz 
Te ennvío el protocolo de logística para que veas como procedemos en presentaciones en Anfiteatro y tomes en cuenta varias cuestiones importantes. Espero te sirva: https://lancis-apc.github.io/planeacion-colaborativa/protocolo_logistica.html

**Comment by Nayita** [comment]
Listas las diapositivas enviadas. Ruta: \PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_11oct2019\plataforma\slides

**Comment by Nayita** [comment]
Listas las diapositivas de la presentación enviada. Ruta: \PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_11oct2019\plataforma\slides
@edithvilla 
El nombre de la dinámica si es el que le puso Bertha. Ya dieron el vo. bo. las chicas. Te lo escribo aquí para que puedas hacer la diapositiva: **Modelo de captación de agua de lluvia**

**Comment by edithvilla** [comment]
- La presentación que mandó SACMEX están en plantilla y ya están incorporadas y procesadas para anfiteatro
- La presentación que mandó SGIRPC no está en el formato de la plantilla para anfiteatro, se le cambió el tamaño de las diapositivas y se le hicieron ajustes

**Comment by Nayita** [comment]
### Aviso

La lista de asistencia escaneada se encuentra en la siguiente ruta: C:\Dropbox (LANCIS)\PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_11oct2019\logistica\FRA_SGC VER 1_11oct2019

**Comment by Nayita** [comment]
@iaga 

Ruta para poner las imágenes de lo presentado desde tableu: PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_11oct2019\procesamiento

**Comment by iaga** [comment]
@Nayita listo, se ubicaron las imágenes de tableau, por pantalla y en el orden que se presentaron en la ruta indicada. Además, se agregó una imagen que Hallie presentó asociada a los clusters de los modelos mentales.

**Comment by Nayita** [comment]
### Nota

En espera de las imágenes de Bertha para terminar de conformar la presentación

**Comment by Nayita** [comment]
### Aviso
Lista la presentación en pptx y pdf en la siguiente ruta: \PRESENTACIONES\pr_megadapt\pr_megadapt_gobcdmx_11oct2019\plataforma
Archivo pr_megadapt_gobcdmx_11oct2019
