### ISSUE TITLE
Realizar e imprimir reconocimientos/constancias de participación #organizacion

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#1070]
Esta es la ruta donde se encuentran las plantillas de los reconocimiento y contancias de participación:

ruta: /ORGANIZACION_APC/apc_plantillas/plantillas_constancias

la contancias que se han realizado para los cursos se encuentran en la siguiente ruta (la plantilla se tomó de la ruta ya mencionada):

Ruta: CAPACITACION/cursos_formales/constancias

**Comment by edithvilla** [comment]
### Reconocimiento de instructor
@serranoycandela 

Para generar la plantilla del reconocimiento necesito que me proporciones:

- Nombre completo y tu grado académico

- Nombre de los cursos que impartiste

**Comment by serranoycandela** [comment]
M. en G. Fidel Serrano Candela

fueron 3
1)   Coordiné el Taller de capacitación para calibrar el modelo de crecimiento urbano SLEUTH mediante el paralelismo en el cluster de supercomputo (La Paz 5 al 8 de noviembre 2018)	
2)   Impartí el curso Automatización de tareas geográficas en Qgis  (Mérida 22 al 26 enero 2019)
3)    Coordiné el Taller de seguimiento de la calibración del modelo SLEUTH para Baja California Sur (La Paz 26 y 27 de Septiembre del 2019)

**Comment by edithvilla** [comment]
![image](https://user-images.githubusercontent.com/25182051/66336381-9295ad80-e902-11e9-86d5-cee3ce8da45b.png)

![image](https://user-images.githubusercontent.com/25182051/66336401-9cb7ac00-e902-11e9-871b-3d4cba3ade41.png)

![image](https://user-images.githubusercontent.com/25182051/66336434-a9d49b00-e902-11e9-8432-b6e11db7cf48.png)

**Comment by edithvilla** [comment]
@Nayita las plantillas de los reconocimientos y constancias se encuentra en la siguiente ruta:

CAPACITACION/cursos_formales/constancias

son archivos de power point

**Comment by edithvilla** [comment]
Reconocimientos listos, firmados, escaneados y entregados

**Comment by edithvilla** [comment]
Se utilizó la plantilla de las constancias para hacer las del 
"Taller de calibración del modelo SLEUTH en clusters de supercómputo. Parte I y Parte II"
 para los participantes de La Paz

**Comment by edithvilla** [comment]
@yosunemiquela 

Ya están impresas las constancias, solo falta la firma del responsable del proyecto. En cuanto están firmadas las escaneo para también estén en formato digital
