### ISSUE TITLE
Localizar las figuras que se necesiten para ilustrar el Paper transdisciplina#MEGADAPT

### ISSUE THREAD

**Issue by berthahdz** [lancis-apc/planeacion-colaborativa#1071]
### Actividades

- [x] Buscar las siguientes figuras originales: a) Megadapt approach y b) Megadapt Model 

- [x] Enviarlas a Bertha por correo

**Comment by berthahdz** [comment]
Buscar y enviar @Nayita  2 figuras más: 

Gráfica de Interacciones actualizada hasta 2019. Versión en Inglés 

Y la figura que mostró Paola hace rato en la sesión. Versión en Inglés 

Enviar por email a Bertha. Gracias.

**Comment by Nayita** [comment]
@berthahdz 

La gráfica del modelo de megadapt no está traducida. Te envío la versión en español para que la traduzcas y te la genero con la traducción que tu me indiques.
