### ISSUE TITLE
Preparar logística para presentación de MEGADAPT 29 de noviembre#megadapt

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#1074]
### Actividades

- [x] Crear carpeta con subcarpetas para la presentación

- [x] Poner en listas de asistencia y minuta. Ruta: PRESENTACIONES/pr_megadapt/pr_megadapt_29nov2019/logistica @berthahdz ya está para impresión. 

La ruta de la carpeta principal es el siguiente: PRESENTACIONES/pr_megadapt/pr_megadapt_29nov2019
@vichdzgeo @iaga @aleestrada @serranoycandela

**Comment by Nayita** [comment]
@berthahdz 
Ruta de la presentación para que pongas lo de la agenda: \PRESENTACIONES\pr_megadapt\pr_megadapt_29nov2019\procesamiento

**Comment by iaga** [comment]
@Nayita error mío, la imagen p2_2_ineq que mencionamos en la presentación, no formará parte de las diapositivas. Incluí en la carpeta de procesamiento la imagen asociada a la vulnerabilidad con el índice de escasez

**Comment by Nayita** [comment]
### Aviso

La lista de asistencia escaneada está en la siguiente ruta: \PRESENTACIONES\pr_megadapt\pr_megadapt_29nov2019\logistica\FRA-SGC VER 1.pdf

**Comment by Nayita** [comment]
### Aviso
La lista de la última reunión con personal del gobierno de la CDMX (26nov2019) está en la siguiente ruta: \CDMX\cdmx_reuniones\logistica\FRA-SGC VER 1_26nov2019

Las listas de capacitación  individual están en la siguiente ruta: CDMX\cdmx_capacitacion\logistica\FRA-SGC VER 1_12nov2019

**Comment by iaga** [comment]
@Nayita la documentación con las imágenes que se presentaron en las pantallas se encuentra en el issue: https://github.com/sostenibilidad-unam/SHV/issues/162, por favor ayudame a verificar qué insumos faltan en la carpeta banco de datos

**Comment by Nayita** [comment]
@iaga No se encontró en la ruta que indicaste los siguientes insumos:  cc_extreme_flooding_count y escorrentia_total_por_escenario. Todos los demás insumos se encuentran en la ruta indicada.
@serranoycandela indicar la ruta de donde se encuentran estos insumos.

**Comment by iaga** [comment]
@Nayita listas las imágenes presentadas en tableau. Se ubicaron en la carpeta indicada: \PRESENTACIONES\pr_megadapt\pr_megadapt_29nov2019\procesamiento\
Se encuentran numeradas por el número de pantalla: px y por el orden en que aparecieron: dx. Por ejemplo, para la pantalla 1, imagen 1:
p1_d1_escorrentia.png

**Comment by Nayita** [comment]
### Aviso
Listas las presentaciones en pptx y pdf. Ruta: PRESENTACIONES\pr_megadapt\pr_megadapt_29nov2019\plataforma
Archivos:
pr_megadapt_29nov2019
