### ISSUE TITLE
Hacer diagnóstico del SIG enviado para prepropuesta del ordenamiento pacífico centro sur #ADMIN

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#1077]
### Actividades

- [x] Descargar capas del SIG

- [x] Colocarlas en carpetas en el Dropbox

- [x] Registrar en base de datos la condición que presentan las capas

Los insumos se obtendrán de la liga enviada por correo electrónico. Las capas descargadas quedarán en la siguiente ruta: ADMIN\admin_propuestas\semarnat\oe_pacifico_cs\sig

La base de datos se hará en un archivo de google drive

**Comment by CorinaCantero** [comment]
Se terminó de extraer la información geográfica de las carpetas:
CARACTERIZACIÓN/Componente_Natural
CARACTERIZACIÓN/Gobernanza
DIAGNÓSTICO/Aptitud_conflictos
PLANTILLA_BASE (primeras ocho carpetas hasta Gratícula)

**Comment by CorinaCantero** [comment]
Ya está lista la base de datos con las capas de información geográfica disponibles en: 
ADMIN\admin_propuestas\semarnat\oe_pacifico_cs\sig\catalogo_oe_pacifico_cs
@vichdzgeo puedes agregar ahí si las capas tienen metadatos, por favor.

**Comment by Nayita** [comment]
### Aviso

Concluidas las descargas de las siguientes capas:

- CARACTERIZACIÓN/Componente socioeconómico (sin capas)

- DIAGNÓSTICO/Impactos y amenazas

- DIAGNÓSTICO/Áreas para preservar, proteger o restaurar

- DIAGNÓSTICO/Gobernanza

- PLANTILLA_BASE (últimas 8 capas a partir de Guatemala)

- Talleres sectoriales/amilcar_ordenamiento

**Comment by vichdzgeo** [comment]
se revisarón un total de 114 archivos shapefile

a continuación se muestra una gráfica del procentaje de capas que presenta cierto problema 

![image](https://user-images.githubusercontent.com/38017509/72776431-d2de1a80-3bd7-11ea-8a9d-76392b945516.png)
