### ISSUE TITLE
Planear simposio SVACC 12 y 13 de marzo #MEGADAPT #SVACC

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#1081]
### Actividades

- [x] Apartar el Anfiteatro para la preparación de la presentación

- [x] Revisar la agenda de Mérida

- [x] Incluir invitados

**Comment by Nayita** [comment]
### Aviso
@paola-gp @aleestrada @iaga apartado el Anfiteatro del 9 al 13 de marzo de 9:00 a 20:00 hrs.

**Comment by Nayita** [comment]
### Actividades

- [ ] Verificar el funcionamiento de la computadora del Anfiteatro y de la plataforma de  presentaciones

### Aviso

La computadora tardó en ser reconocida por el Creston en primera instancia. Se necesitó reiniciar el Creston y la computadora para que encendiera con normalidad. Rodrigo ya está notificado de esta situación.
La computadora y la plataforma funciona sin ningún problema. La computadora hizo las actualizaciones correspondientes

**Comment by Nayita** [comment]
### Actividades

- [ ] Hacer lista de participantes

- [ ] Hacer identificadores de participantes

- [ ] Hacer listado de logística

- [ ] Verificar si se hace página web

- [ ] Verificar el funcionamiento del equipo (cañón, cámara de video, grabadoras)

- [ ] Imprimir las listas de asistencias

- [ ] Revisar e imprimir los formatos de autorización de grabación y fotografías

- [ ] Contratar el servicio para el coffee break

- [ ] Preparar información para la prensa

**Comment by paola-gp** [comment]
@CorinaCantero: Los insumos para la nueva página de internet están en: SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020

**Comment by Nayita** [comment]
## 2. Hacer identificadores de participantes

- Hay 61 gafetes. 

-Tres paquetes de etiquetas de colores

**Comment by paola-gp** [comment]
###  9. Preparar información para la prensa 

Solicitar resumen de reunión para gaceta unam a Luis @rociobrito

**Comment by CorinaCantero** [comment]
### AVISO

Está terminada la página web para el simposio: https://lancisapc.wixsite.com/simposiosvacc

**Comment by paola-gp** [comment]
4. página web

@CorinaCantero: actualizar agenda en página de internet (insumos en carpeta de trabajo)

**Comment by Nayita** [comment]
### 5. Solicitar cañón HD, cámara de video y grabadoras y verificar su funcionamiento
Lista la solicitud de la cámara de video y el tripié. @CorinaCantero se encargará de recogerlo, usar y entregar la cámara y el tripié.

El cañón lo prestará @yosunemiquela. En espera del formato de solicitud.

**Comment by Nayita** [comment]
### 5. Solicitar cañón HD, cámara de video y grabadoras y verificar su funcionamiento 

- [ ] Elaborar solicitud de préstamo del proyector.

@yosunemiquela 
Revisar el machote y dar el vo.bo.
Ruta: \SVACC\svcc_simposio_12-13mar2020\logistica\solicitud_proyector_lancis.docx

**Comment by paola-gp** [comment]
### 11. Asignar roles de logística durante el simposio 
#### Estos son los roles asignados
1. Seguimiento con el personal de gaceta UNAM: @rociobrito 
2. Supervisión del servicio de café y alimentos: @rociobrito 
3. Fotografías del evento: @rociobrito 
4. Video de cada una se las presentaciones y sesiones: @CorinaCantero 
5. Registro: @Nayita y @TatianaMerino
6. Tomar notas de la plenaria: @yosunemiquela, @TatianaMerino 
7. Manejo y resguardo de presentaciones en /SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020/presentaciones : @iaga 
8. Maestra de ceremonias: @paola-gp 
9. Material y equipo: @Nayita y @paola-gp 
10. Confirmación de asistentes: @berthahdz

**Comment by paola-gp** [comment]
### AVISO
#### 10. Preparar presentaciones del APC

@iaga @aleestrada @serranoycandela @yosunemiquela: pueden poner ahí los insumos finales

La ruta de las presentaciones de megadapt para el simposio son:

##### Presentación política 9:50 am: /SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020/pr_megadapt_12_mar_2020/pr_megadapt_12_mar_2020_9_50am

##### Presentación técnica 3:00 pm:
/SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020/pr_megadapt_12_mar_2020/pr_megadapt_12_mar_2020_3pm

**Comment by Nayita** [comment]
### AVISO
Toda la información de logística que estaba en la ruta: SVACC/svcc_simposio_12-13mar2020/logistica, cambió a la ruta: /SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020/logistica

**Comment by iaga** [comment]
@Nayita se ubicó la imagen **dinamicas_adaptativas_escenario.png** en la ruta para la presentación política. Por favor, agregarla a la presentación y poner como título: Vulnerabilidad promedio (Escasez) y cambiar las leyendas de Con competencia y sin competencia en power point para que las letras sean más grandes.

**Comment by Nayita** [comment]
### Aviso
Listas de asistencia escaneadas en la siguiente ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\logistica

Audios descargados en la siguiente ruta: \SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\logistica\audio

**Comment by Nayita** [comment]
### Aviso
Hecho el arreglo de nombres de las presentaciones y la copia de las presentaciones de MEGADAPT a la siguiente ruta: /PRESENTACIONES/pr_megadapt/pr_megadapt_12mar2020

**Comment by TatianaMerino** [comment]
Los comentarios resultantes del simposio, que surgieron durante la plenaria, con relación a MEGADAPT se encuentran en la siguiente ruta: SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020/plenaria

**Comment by Nayita** [comment]
Concluido
