### ISSUE TITLE
Preparar informe SDI 2020 #SVACC

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#1082]
El entregable quedará en el respositorio:  /SVACC/svcc_informe_sdi_2020 e incluirá los siguientes productos. Favor de poner una copia de éstos en las siguientes subcarpetas: 

- [x] @yosunemiquela: informe Papiit con anexos si es que existen en /papiit

- [x] @Nayita: informe de IAI con anexos si es que existen en /iai_megadapt

- [x] @CorinaCantero: programa, presentaciones en /presentacion_binacional

- [x] @paola-gp: informe presentación binacional en /presentacion_binacional

- [ ] @rociobrito: compilación de fotografías de la presentación binacional en /presentacion_binacional

- [ ] @paola-gp: informe gestión interna en /gestion_activos

- [x] @dpedroza74 y @ofegarcia: avances informe fomix en /fomix

- [ ] @paola-gp: preparación el simposio de megadapt en /simposio_binacional2020

- [x] @vichdzgeo: páginas de presentación de resultados de proyectos varios en issue

**Comment by Nayita** [comment]
### Aviso
Se puso el informe final de IAI en el lugar indicado. No tiene anexos.

**Comment by yosunemiquela** [comment]
Se integró el informe PAPIIT a la ruta indicada. Como anexos se añadió el primer manual. Otros productos (manuscritos y plataforma de visualización geoespacial) se mencionan en el informe.

**Comment by paola-gp** [comment]
Informe SVACC
@iaga favor de poner en /papiit del respositorio al que se hace mención en este issue los informes de papiit del posdoc y scripts
@iaga y @aleestrada: favor de poner y avisar lo que les pida Luis poner en el respositorio de este informe.

**Comment by dpedroza74** [comment]
Subí informes de las actividades que hemos realizado en el proyecto FOMIX

**Comment by iaga** [comment]
## PAPIIT


### Informes posdoc:
Ruta: SVACC/svcc_informe_sdi_2020/investigacion/papiit
Responsable: @iaga 
#### Archivos:
- informe_posdoc_ene_jul_2019.pdf

#### Scripts:

**Comment by paola-gp** [comment]
### Informe SVACC scripts

@vichdzgeo: /SVACC/svcc_informe_sdi_2020/activos/scripts/python_qgis

**Comment by iaga** [comment]
## MEGADAPT

Ruta: SVACC/svcc_informe_sdi_2020/investigacion/megadapt

#### Scripts:
- Reversión de rango: script_rank_reversal.html

**Comment by iaga** [comment]
@paola-gp listo, papiit se encuentra en el comentario: https://github.com/lancis-apc/planeacion-colaborativa/issues/1082#issuecomment-587587624

**Comment by paola-gp** [comment]
### Presentaciones LANCIS 2019 en:
/SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/otras_presentaciones

- [ ] @Nayita

**Comment by Nayita** [comment]
### Aviso
@paola-gp Listos los pdfs de las presentaciones en el lugar indicado

**Comment by paola-gp** [comment]
informe entregado y copia de CD en expediente
