### ISSUE TITLE
Actualizar páginas de los dos encuentros académicos de SVACC #SVACC

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#1090]
1.  Recibir una capacitación de no mas de media hora del uso de WIX por parte de @CorinaCantero
2. Revisar las dos páginas y modificar las adecuaciones con base en lo que sucedió realmente (agenda, participantes, etc.) @Nayita y @rociobrito 
3. 	Crear una copia de https://www.lancis-svacc.org/  @rociobrito 
4. 	Crear una copia de https://lancisapc.wixsite.com/simposiosvacc @rociobrito 
5. Agregar una sección de (1) presentaciones, (2) reseña de participantes (número de participantes, gráficas de participantes por tipo de afiliación) y fotos (no más de 10). @rociobrito 
6. 	En la sección de presentaciones crear enlaces de Dropbox directamente a cada una de las presentaciones (a dos años) @Nayita

**Comment by CorinaCantero** [comment]
### Aviso

Link simposio Mérida: https://www.lancis-svacc.org/
Link simposio Marzo 2020: https://lancisapc.wixsite.com/simposiosvacc

**Comment by rociobrito** [comment]
@paola-gp @Nayita Paola no veo las actualizaciones que comentaste en la reunión... acerca de las dudas de Nadia

**Comment by paola-gp** [comment]
@rociobrito 

1. Guardar dos copias de las páginas para tener un respaldo. 
2. Trabajar en una de las copias hasta que se se esté listo para la publicación. 
3. Crear una sección de presentaciones en cada una de las copias y diseñar una lista por sección del simposio y póner los nombres de las presentaciones (en cuanto estén los enlaces generados por Nadia, generar los hipervínculos)
4. Crear una sección de fotografías y ubicar un máximo de 9 fotografías de todo el evento, para cada uno de los encuentros. 
5. Crear una sección de participantes en la página del simposio y poner los insumos que proveerá @Nayita

**Comment by paola-gp** [comment]
@rociobrito 
6. Publicar en un sitio temporal para revisar las modificaciones
7. En cuanto esté aprobadas las modificaciones publicar en los enlaces originales.

**Comment by Nayita** [comment]
### Actividades

@rociobrito 

Actualizaciones de la página de Mérida
- [ ] En la parte de la ceremonia de clausura, quitar las fotos del gobernador de Yucatán y de William Lee. 

- [ ] Poner en su lugar las fotos de Luis Bojórquez, Hallie, Bernardo Cisneros, Xavier Chiappa y Bello Bolio

- [ ] Sustituir los programas en inglés y español y el programa de la página que está en inglés. Ruta: SVACC/svcc_10-14jun/insumos_pag_actualizacion

Archivos: 
programa_final_esp.pdf
final_program_2_v1

**Comment by Nayita** [comment]
### Actividades

@rociobrito 

- [ ] Quitar de participantes la semblanza de William Lee Alardín, Constantino Macías y Alec Torres

- [ ] Hacer gráfica de participantes por filiación. Envío el archivo depurado de las listas de asistencia por participantes por filiación. Ruta: SVACC/svcc_10-14jun/insumos_pag_actualizacion
Archivo: asist_inaug_svacc_11a13jun2019.docx
Ejemplo de gráfica. Ruta: IAI/iai_procesamiento/bd_talleres_reuniones
Archivo: bd_registroeventosad_may2019

**Comment by Nayita** [comment]
### Actividades

@rociobrito 

Simposio

- [ ] Quitar del programa el día 13. Sólo dejar el día 12.

- [ ] Cambiar el programa del día 12 por programa actualizado. Ruta: SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020/insumo_pag_actualizacion
Archivo: programa_final_v1.pdf

**Comment by Nayita** [comment]
### Actividades 

@rociobrito 

Simposio

- [ ]  Copiar las semblanzas de los siguientes participantes de la página de Mérida. 

      -  Luis Bojórquez, Patrick Reed, Sarah Freeman, Edmundo Molina y Yosune Miquelajauregui 

- [ ]  Integrar las semblanzas que faltan de los archivos colocados en los insumos. Ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion

Archivos:
ficha_adrian_fdz.docx
ficha_hector_cañada.docx
ficha_ricardo_torres.docx

- [ ]  Hacer gráfica de participantes por filiación. Envío el archivo depurado de las listas de asistencia por participantes por filiación. Ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion\listas_participantes_filiacion.docx

**Comment by Nayita** [comment]
### Actividades

@rociobrito 

- [ ] Agregar la lista de presentaciones para la página de Mérida para colocar ahí los vínculos. Ruta:
\SVACC\svcc_10-14jun\insumos_pag_actualizacion

Archivo: lista_presentaciones.docx

- [ ] Agregar la lista de presentaciones para la página de Simposio para colocar ahí los vínculos. Ruta:
\SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion

Archivo: lista_presentaciones.docx

**Comment by rociobrito** [comment]
PÁGINA VERSIÓN EN INGLÉS

Cambios que ya están listos:
1. Tarea: En la parte de la ceremonia de clausura, quitar las fotos del gobernador de Yucatán y de William Lee.
2. Tarea: Poner en su lugar las fotos de Luis Bojórquez, Hallie, Bernardo Cisneros, Xavier Chiappa y Bello Bolio
3. Tarea: "Sustituir los programas en inglés y español y el programa de la página que está en inglés. Ruta: SVACC/svcc_10-14jun/insumos_pag_actualizacion"
Archivos:
programa_final_esp.pdf
final_program_2_v1
4. Tarea: Quitar de participantes la semblanza de William Lee Alardín, Constantino Macías y Alec Torres
5. Tarea: Agregar la lista de presentaciones para la página de Mérida para colocar ahí los vínculos. Ruta:
\SVACC\svcc_10-14jun\insumos_pag_actualizacion
Archivo: lista_presentaciones.docx

Notas:
* El programa en inglés tenía sin traducir en la casilla de "Opening plenary" la frase "Construcción de capacidades SVACC", la traduje como "SVACC capacity building" y generé un nuevo PDF que subí a la página 
* Modifiqué el texto del título "Final program" a "Program"
* Modifiqué el texto del botón "English_program", quité el guión bajo 
* Modifiqué el link del botón "English_program" al PDF actualizado
* Modifiqué el texto del botón "Programa_español", quité el guión bajo y puse "Programa en español"
* OJO: el programa final en español no está en archivo Word en el Dropbox, no lo puedo modificar, al final del PDF se creó una segunda hoja por unas palabras que son el final de un párrafo de la hoja 1, creo que se puede dejar en una sola hoja...

PÁGINA VERSIÓN EN ESPAÑOL
* Traduje algunos textos de las fotos de "Ceremonia de clausura"
* Modifiqué el título "Programa final" por "Programa"

**Comment by Nayita** [comment]
@rociobrito 

Ruta del programa en español de Mérida: \SVACC\svcc_10-14jun\insumos_pag_actualizacion\programa_final_esp.docx

**Comment by paola-gp** [comment]
@rociobrito: Podrías actualizar las páginas originales para ya poder distribuirlas a  los solicitantes?

Link simposio Mérida: https://www.lancis-svacc.org/
Link simposio Marzo 2020: https://lancisapc.wixsite.com/simposiosvacc

**Comment by rociobrito** [comment]
@paola espero tenerlas hoy listas

**Comment by Nayita** [comment]
### Aviso
@rociobrito 

Listas las listas de las presentaciones en orden de presentación y por día de presentación.

Ruta simposio: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion\lista_presentaciones.docx

Ruta Mérida:
\SVACC\svcc_10-14jun\insumos_pag_actualizacion\lista_presentaciones.docx

**Comment by Nayita** [comment]
### Aviso
@rociobrito 

Algunas fotos de participantes de la página de Mérida están en la siguiente ruta: SVACC/svcc_10-14jun/insumos. 

Algunas están sueltas en la carpeta y otras pegadas en las semblanzas. El resto se pueden obtener de la página web anterior.

**Comment by Nayita** [comment]
### Aviso

@rociobrito 

Listas las semblanzas faltantes.  
Ruta de las semblanzas faltantes:SVACC\svcc_10-14jun\insumos_pag_actualizacion\semblanzas_faltantes.docx

**NOTA**
En la página 2  están las semblanzas en español con fotografía

**Comment by rociobrito** [comment]
> ### Actividades
> @rociobrito
> 
> Simposio
> 
> * [ ]   Copiar las semblanzas de los siguientes participantes de la página de Mérida.
> * Luis Bojórquez, Patrick Reed, Sarah Freeman, Edmundo Molina y Yosune Miquelajauregui
> * [ ]   Integrar las semblanzas que faltan de los archivos colocados en los insumos. Ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion
> 
> Archivos:
> ficha_adrian_fdz.docx
> ficha_hector_cañada.docx
> ficha_ricardo_torres.docx
> 
> * [ ]   Hacer gráfica de participantes por filiación. Envío el archivo depurado de las listas de asistencia por participantes por filiación. Ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion\listas_participantes_filiacion.docx
> 
> ### Nota importante
> Agregué al archivo de lista de participantes de Mérida a los participantes de LANCIS que no estaban para que se tome en cuenta si es que ya hiciste la gráfica.

@Nayita no hay que copiar la semblanza de Hallie? no faltan más?

**Comment by Nayita** [comment]
@rociobrito 
En proceso la semblanza de Hallie

**Comment by Nayita** [comment]
@rociobrito 

Lista semblanza de Hallie en la siguiente ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion\semblanzas_faltantes.docx

**Comment by rociobrito** [comment]
@Nayita  faltaría la de Felipe de SACMEX

**Comment by Nayita** [comment]
@rociobrito 

Previa consulta con Paola se determinó que sólo se ponía la de Héctor debido a que Felipe presentó en su nombre por enfermedad.

**Comment by rociobrito** [comment]
> ### Actividades
> @rociobrito
> 
> * [x]  Quitar de participantes la semblanza de William Lee Alardín, Constantino Macías y Alec Torres
> * [ ]  Hacer gráfica de participantes por filiación. Envío el archivo depurado de las listas de asistencia por participantes por filiación. Ruta: SVACC/svcc_10-14jun/insumos_pag_actualizacion
>   Archivo: asist_inaug_svacc_11a13jun2019.docx
>   Ejemplo de gráfica. Ruta: IAI/iai_procesamiento/bd_talleres_reuniones
>   Archivo: bd_registroeventosad_may2019

@Nayita @paola-gp  ¿me podrías mandar solo el ejemplo de la gráfica en un Excel? hay muchas gráficas en ese documento....  Gracias.

**Comment by Nayita** [comment]
@rociobrito 
Ejemplo solicitado en la siguiente ruta:\SVACC\svcc_10-14jun\insumos_pag_actualizacion\ejemplo_grafica.xlsx
En el archivo hay tres hojas con ejemplos de gráficas de barras con sus datos. Se puede usar los mismos colores para estas gráficas sencillas

**Comment by rociobrito** [comment]
> ### Actividades
> @rociobrito
> 
> Simposio
> 
> * [x]   Copiar las semblanzas de los siguientes participantes de la página de Mérida.
> * Luis Bojórquez, Patrick Reed, Sarah Freeman, Edmundo Molina y Yosune Miquelajauregui
> * [x]   Integrar las semblanzas que faltan de los archivos colocados en los insumos. Ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion
> 
> Archivos:
> ficha_adrian_fdz.docx
> ficha_hector_cañada.docx
> ficha_ricardo_torres.docx
> 
> * [ ]   Hacer gráfica de participantes por filiación. Envío el archivo depurado de las listas de asistencia por participantes por filiación. Ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion\listas_participantes_filiacion.docx
> 
> ### Nota importante
> Agregué al archivo de lista de participantes de Mérida a los participantes de LANCIS que no estaban para que se tome en cuenta si es que ya hiciste la gráfica.

@paola-gp @Nayita  Nadia, la lista de asistencia del simposio no está correcta, Cesar Abarca tiene como procedencia SEDEMA en lugar de SGIRPC ¿la podrías revisar por favor para hacer la gráfica? Gracias

**Comment by Nayita** [comment]
@rociobrito 
Revisada la lista y no se encontró el error que se mencionó. En concreto, César Abarca registró DGR o sea Dirección General de Resilencia. Aidé Franco que está en el renglón de arriba si es de SEDEMA. 

Se sugiere descargar el archivo para desplegar correctamente el archivo.

**Comment by Nayita** [comment]
@paola-gp 
Revisar gráficas para aprobación. Ruta: \SVACC\svcc_10-14jun\insumos_pag_actualizacion\graficas
Archivos: gr_participant_merida_es.png
               gr_participant_merida_in.png
               gr_partipant_simposio.png

**Comment by Nayita** [comment]
@rociobrito 

Ruta de lista de asistencia de SIMPOSIO:
SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020/logistica

Archivo:
list_asist.pdf

**Comment by Nayita** [comment]
@rociobrito 

- Lista la presentación en pdf en el dropbox. Ruta: SVACC/svcc_informe_sdi_2020/encuentros_academicos_transdisciplinarios/simposio_svacc2020/presentaciones

Archivo: systems_analysis_great_acceleration.pdf

- Listo el vínculo en dropbox.

- Actualizado el archivo de listado de presentaciones con este vínculo. Ruta: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion\lista_presentaciones.docx

**Comment by rociobrito** [comment]
> ### Aviso
> @rociobrito
> 
> Listas las listas de las presentaciones en orden de presentación y por día de presentación.
> 
> Ruta simposio: SVACC\svcc_informe_sdi_2020\encuentros_academicos_transdisciplinarios\simposio_svacc2020\insumo_pag_actualizacion\lista_presentaciones.docx
> 
> Ruta Mérida:
> \SVACC\svcc_10-14jun\insumos_pag_actualizacion\lista_presentaciones.docx

@Nayita @paola-gp 

Luis me pidió que ponga la foto de cada ponente, de cada presentación que se hizo en Mérida en la página. Incluir en la lista, a un lado de cada presentación quien expuso para poder subir las fotos.

**Comment by Nayita** [comment]
### Aviso
@rociobrito 

En el archivo lista_presentaciones.docx se encuentran los nombres de los expositores. Sólo en tres presentaciones ´donde hay un listado de participantes, se especificó quién expuso presencialmente.

**Comment by rociobrito** [comment]
@Nayita 
En esa lista se encuentran los nombres de los autores de la presentación, pero no quien expuso, lo que se necesita es saber quien expuso cada presentación

**Comment by rociobrito** [comment]
@Nayita @paola-gp 
Luis prefiere que los textos de las presentaciones se puedan leer pero no compartir/bajar ¿es posible que solo se visualice? ¿lo puedes programar así con el link a Dropbox?

**Comment by paola-gp** [comment]
@rociobrito: No es posible.
