### ISSUE TITLE
Analizar datos tinker 

### ISSUE THREAD

**Issue by TatianaMerino** [lancis-apc/planeacion-colaborativa#1103]
Objetivos: 
- Explorar los datos
- Obtener gráficas comunicativas

Insumos:
- Bases de datos de cooperativa Holbox
- Bases de datos de cooperativa Chiquilá

Ruta de trabajo: CARPETAS_TRABAJO/igrave/tinker

Los resultados servirán de insumos para el modelo de vulnerabilidad del sector pesquero lancis-apc/espejos-lancis#119 lancis-apc/espejos-lancis#134

**Comment by TatianaMerino** [comment]
@serranoycandela @iaga @dpedroza74 
Ruta de trabajo: 
\CARPETAS_TRABAJO\tmerino\tinker\pivot_excel\dashboards\correcciones

En esta carpeta están:
- Los **Dummies** con las correcciones y sugerencias revisadas 
- La **foto del registro** de la cooperativa para SAGARPA
Estarán: 
- Los dashboards corregidos 

Gráfica de tendencia sugerida por temporada con filtro de pescadores: 
![image](https://user-images.githubusercontent.com/57197109/118053835-d9535100-b34a-11eb-8416-27130e07d2df.png)

**Comment by TatianaMerino** [comment]
VEDAS 
![image](https://user-images.githubusercontent.com/57197109/118414071-33645700-b668-11eb-8e63-4d293bbeb433.png)

**Comment by TatianaMerino** [comment]
Listas las actualizaciones del **dashboard de arribos** 
CARPETAS_TRABAJO/tmerino/tinker/pivot_excel/dashboards/correcciones/arribos_cabocatoche_v2.xlsx

Pendientes:

- [ ] simulación de datos a largo plazo @iaga 
- [ ] Acomodo de dashboard con la simulación @TatianaMerino

**Comment by iaga** [comment]
@TatianaMerino 

Listos los datos de los últimos años, se modificó el archivo **arribos_cabocatoche_v2.xlsx**. Es necesario revisar la parte de la actualización de los dashboards.

**Comment by TatianaMerino** [comment]
## Datos dummy 

Las tablas se anclaron a:  CARPETAS_TRABAJO\tmerino\tinker\pivot_excel\base_datos_tinker.xslx

Pendientes: 
- [ ] Hacer los datos dummy de captura mensual. Dashboard: captura_conexion.xslx @iaga 
- [ ] Acomodar el dashboard final de arribos. Archivo: prueba_conexion.xslx @TatianaMerino 
- [ ] Acomodar el dashboard final de captura mensual ya con los datos dummy @TatianaMerino

**Comment by iaga** [comment]
@TatianaMerino listos los dummys de captura mensual, se realizaron dos filtros: 1) última temporada, 2) últimas cuatro temporadas

**Comment by TatianaMerino** [comment]
Registro de arribos @serranoycandela @iaga 
CARPETAS_TRABAJO\tmerino\tinker\pivot_excel\dashboards\registro_arribos_fs.xlxm

Pendientes:

- [ ] Ajustar los nombres de los campos a los del dashboard
- [ ] Agregar columna de mes y columna de año 
- [ ] Describir el procedimiento para habilitar la función de calendario
- [ ] Revisar con Daniela el registro (preguntar sobre si los números de permisos son por especie o por socio)
- [ ] Unir el dashboard al registro en formato xlsm 
- [ ] Filtrar la base de datos del registro para obtener los últimos años 
- [ ] Acomodar el dashboard final

**Comment by TatianaMerino** [comment]
## Registro de captura de socios

Anotaciones: 
- Formato de registro de temporada "2016-2017", a mano, con notificación si se registra con otro formato
- Especies a registrar: Langosta, Escama, Pulpo, Mero, Negrillo
- Registro en formato wide que pasa a formato long en la base de datos

Pendientes:

- [ ] Hacer el registro
- [ ] Unir el registro con la el dashboard
- [ ] Hacer el filtro por las últimas 4 temporadas y el filtro por última temporada
- [ ] Acomodar el dashboard final

Observaciones:
- Se revisará con la cooperativa el cálculo del remanente

**Comment by iaga** [comment]
@serranoycandela favor de revisar cómo hacer que se vea el texto del encabezado

![imagen](https://user-images.githubusercontent.com/41757755/119733148-b8a4f400-be3e-11eb-97c0-c1d4395a0720.png)

**Comment by iaga** [comment]
@TatianaMerino lista la base filtrada y la conexión para el registro de arribos

CARPETAS_TRABAJO\tmerino\tinker\pivot_excel\dashboards\registro_arribos_fs.xlsm

**Comment by iaga** [comment]
## Código: última temporada

= Table.DuplicateColumn(#"Changed Type", "Temporada", "Temporada - Copy")
= Table.SplitColumn(#"Duplicated Column", "Temporada - Copy", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Temporada - Copy.1", "Temporada - Copy.2"})
= Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Temporada - Copy.1", Int64.Type}, {"Temporada - Copy.2", Int64.Type}})
= Table.AddColumn(#"Changed Type1", "Custom", each List.Max(#"Changed Type1"[#"Temporada - Copy.2"]))
= Table.AddColumn(#"Added Custom", "filtro", each if [#"Temporada - Copy.2"] = [Custom] then [#"Temporada - Copy.2"] else 0)
= Table.SelectRows(#"Added Conditional Column", each [filtro] <> 0)

**Comment by iaga** [comment]
@TatianaMerino lista la unión del registro y los filtros (última temporada, últimas 4)

\CARPETAS_TRABAJO\tmerino\tinker\pivot_excel\dashboards\registro_captura_fs.xlsm

**Comment by iaga** [comment]
## Código macros captura

Sub add_data()
    last_captura = Sheets("registro_datos").Cells(Rows.Count, 3).End(xlUp).Row
    last_row = Sheets("datos").Cells(Rows.Count, 1).End(xlUp).Row
    new_row = last_row + 1
    
    For Each Row In Range("C8:I" & last_captura).Rows
        socio = Row.Cells(1, 1).Value
        langosta = Row.Cells(1, 2).Value
        pulpo = Row.Cells(1, 3).Value
        mero = Row.Cells(1, 4).Value
        negrillo = Row.Cells(1, 5).Value
        If Not langosta = "" Then
            Sheets("datos").Range("A" & new_row).Value = socio
            Sheets("datos").Range("B" & new_row).Value = Range("C2").Value
            Sheets("datos").Range("C" & new_row).Value = Range("D2").Value
            Sheets("datos").Range("D" & new_row).Value = Range("R5").Value
            Sheets("datos").Range("E" & new_row).Value = Range("R6").Value
            Sheets("datos").Range("F" & new_row).Value = Range("G2").Value
            Sheets("datos").Range("G" & new_row).Value = "Langosta"
            Sheets("datos").Range("H" & new_row).Value = langosta
            new_row = new_row + 1
        End If
        If Not pulpo = "" Then
            Sheets("datos").Range("A" & new_row).Value = socio
            Sheets("datos").Range("B" & new_row).Value = Range("C2").Value
            Sheets("datos").Range("C" & new_row).Value = Range("D2").Value
            Sheets("datos").Range("D" & new_row).Value = Range("R5").Value
            Sheets("datos").Range("E" & new_row).Value = Range("R6").Value
            Sheets("datos").Range("F" & new_row).Value = Range("G2").Value
            Sheets("datos").Range("G" & new_row).Value = "Pulpo"
            Sheets("datos").Range("H" & new_row).Value = pulpo
            new_row = new_row + 1
        End If
        If Not mero = "" Then
            Sheets("datos").Range("A" & new_row).Value = socio
            Sheets("datos").Range("B" & new_row).Value = Range("C2").Value
            Sheets("datos").Range("C" & new_row).Value = Range("D2").Value
            Sheets("datos").Range("D" & new_row).Value = Range("R5").Value
            Sheets("datos").Range("E" & new_row).Value = Range("R6").Value
            Sheets("datos").Range("F" & new_row).Value = Range("G2").Value
            Sheets("datos").Range("G" & new_row).Value = "Mero"
            Sheets("datos").Range("H" & new_row).Value = mero
            new_row = new_row + 1
        End If
        If Not negrillo = "" Then
            Sheets("datos").Range("A" & new_row).Value = socio
            Sheets("datos").Range("B" & new_row).Value = Range("C2").Value
            Sheets("datos").Range("C" & new_row).Value = Range("D2").Value
            Sheets("datos").Range("D" & new_row).Value = Range("R5").Value
            Sheets("datos").Range("E" & new_row).Value = Range("R6").Value
            Sheets("datos").Range("F" & new_row).Value = Range("G2").Value
            Sheets("datos").Range("G" & new_row).Value = "Negrillo"
            Sheets("datos").Range("H" & new_row).Value = negrillo
            new_row = new_row + 1
        End If
        
    
    Next
    Range("C8:I30").Value = ""
    Range("C2").Value = Date
    Range("D2").Value = Date
    MsgBox "Datos de captura guardados correctamente"
    Application.Goto (ActiveWorkbook.Sheets("registro_datos").Range("C8"))
    ActiveWorkbook.Save

End Sub

**Comment by iaga** [comment]
## Código macros arribos

Sub add_data()

    If Range("C4").Value = "" Or Range("C5") = "" Or Range("C6").Value = "" Or Range("G2").Value = "" Then
       MsgBox "Faltan datos generales"
    Else
        last_captura = Sheets("registro_datos").Cells(Rows.Count, 3).End(xlUp).Row
        faltan_kilos = WorksheetFunction.CountBlank(Range("H8:I" & last_captura))
        If faltan_kilos > 0 Then
            MsgBox "Faltan datos de kg o precio por kg"
        Else
            last_row = Sheets("test_datos").Cells(Rows.Count, 1).End(xlUp).Row
            
            new_row = last_row + 1
            folio = Range("C4").Value
                
            Range("C8:S16").Copy
            
            Sheets("test_datos").Range("A" & new_row).PasteSpecial Paste:=xlPasteValues, Operation:=xlNone, SkipBlanks:=False, Transpose:=False
            
            Range("C8:C16").Value = ""
            Range("H8:I16").Value = ""
            Range("C4:C6").Value = ""
            Range("G2").Value = ""
            Range("C2").Value = Date
            Range("D2").Value = Date
            MsgBox "Datos del folio " & folio & " guardados correctamente"
            Application.CutCopyMode = False
            Application.Goto (ActiveWorkbook.Sheets("registro_datos").Range("D2"))
            ActiveWorkbook.Save
        End If
    End If


End Sub

**Comment by iaga** [comment]
@TatianaMerino  Lista la nueva versión de captura, para agregar la gráfica que falta:

\CARPETAS_TRABAJO\tmerino\tinker\pivot_excel\dashboards\registro_captura_fs_t_vacio_v2.xlsm

**Comment by iaga** [comment]
= Table.TransformColumnTypes(Source,{{"Especie", type text}, {"Permiso", type text}, {"Expedicion", type datetime}, {"Vigencia", type datetime}, {"Cve_especie", type text}, {"Captura", type number}, {"Precio", type number}, {"Fecha_i", type datetime}, {"Fecha_f", type datetime}, {"Folio", type text}, {"Días", Int64.Type}, {"Embarcaciones", Int64.Type}, {"Lugar", type text}, {"Categoría", type text}, {"Mes", type text}, {"Año", Int64.Type}, {"Ganancia", type number}})

**Comment by iaga** [comment]
## Correcciones

Carpeta de trabajo: \CARPETAS_TRABAJO\tmerino\tinker\pivot_excel\dashboards\correcciones_140621

### Arribos

\CARPETAS_TRABAJO\tmerino\tinker\pivot_excel\dashboards\correcciones_140621\registro_arribos.xlsm

Hoja: histórico reciente

**Actividades:**

- [ ] Crear tabla que despliegue automáticamente las categorías de pesca (Es decir: debe desaparecer "Boquinete" y "Otros" y aparecer "Escama") @TatianaMerino 

### Captura

**Comment by TatianaMerino** [comment]
@iaga Listas las modificaciones en la carpeta correcciones_140621 
Archivos: 
- registro_captura_final
- registro_arribos_final
