### ISSUE TITLE
Instalar tableau en el anfiteatro

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#5]
Comprarlo, instalarlo y verificar que funcione

**Comment by rgarcia-herrera** [comment]
http://www.tableau.com/products/server#pricing-specs

**Comment by rgarcia-herrera** [comment]
La versión desktop no puede conectarse a base de datos, sólo hojas de excel y csv.

http://www.tableau.com/products/desktop#pricing-specs

**Comment by rgarcia-herrera** [comment]
Alternativas a Tableau:
 - [Birt](http://www.eclipse.org/birt/) es un componente de Eclipse.
 - [HTSQL](http://htsql.org) permite analizar bases de datos relacionales

**Comment by rgarcia-herrera** [comment]
Cubes es un backend para diseñar cubos OLAP (on-line analytical processing).
http://cubes.databrewery.org/

Se puede usar en conjunto con Cubes Viewer para interactuar con tus cubos desde la web:
http://www.cubesviewer.com
