### ISSUE TITLE
Actualizar nombres en carpeta de ORGANIZACION_APC

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#502]
A los nombres de las subcarpetas les hacen falta los prefijos.

**Comment by ovisnigra** [comment]
listo. cierro

**Comment by ovisnigra** [comment]
@PaolaGomezPriego puedes revisar qué pasó con la carpeta de plantillas, está eliminada del DropBox. Supongo que tiene que ver con que la tenías como carpeta compartida.

**Comment by Nayita** [comment]
@ovisnigra 
Hola Sergio, revisando la carpeta de manuales en la carpeta iso de ORGANIZACIÓN APC, no encontré el manual que hizo Abril del uso de plataforma. Ya tenía formato iso. Lo puedes checar por fa.
Gracias.

**Comment by ovisnigra** [comment]
Reviso

**Comment by ovisnigra** [comment]
cierro issue. la carpeta ya está restaurada y ya se han subido nuevas cosas.
