### ISSUE TITLE
Reportar por este medio los avances de la reunión con Eric Morales #megadapt

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#503]
Establecer los objetivos y resultados de la semana.

**Comment by marcoajh** [comment]
El objetivo de las reuniones es corregir los errores del modelo de hidrología subterránea. 

El lunes 15 de Enero se revisó el modelo, Eric notó que el modelo usa valores de P constantes y propuso usar un valor calculado de P para cada time-step.

Acordamos probar con un conjunto hipotético de 20 zonas para implementar el modelo.

Hoy (miércoles) por la tarde tendré la propuesta para que la revisemos mañana (jueves).

**Comment by marcoajh** [comment]
Eric Revisó el modelo el pasado jueves.
Se aplicaron las correcciones relacionadas con los valores P.
Se propuso calcular valores P entre  zonas de diferentes acuiferos, éste valor será la suma de valores P ponderada por la distancia de contacto entre cada par de zonas.
La siguiente reunión está programada para el miércoles 31 de Enero (falta que Eric confirme).

**Comment by marcoajh** [comment]
@PaolaGomezPriego 

Me reuní con Eric los días miércoles 24 y jueves 25.
Para la primera reunión se revisó el cálculo de los valores de P entre zonas de diferente acuífero, para la segunda reunión se calculó el balance a 10 años, se identificaron las zonas que presentan recuperación en la carga hidráulica. Eric revisó dichas cuencas y aprobó el funcionamiento del modelo. También recomendó comenzar a mover los valores de bombeo de acuerdo al crecimiento poblacional en cada zona y distribuir la recarga, ésto se revisará la siguiente semana, con fecha por definir.
Para calcular el crecimiento poblacional en cada zona es necesario ponderar las tasas de crecimiento por municipio o localidad según el área que ocupan en cada zona.
Por distribución de la recarga se refiere a distribuir el valor de recarga en recarga natural, fugas, etc... según el tipo de cobertura y superficie que ocupa en cada zona, se hace la suposición que 1 ha urbana es igual a 1 ha natural, etc...
 
Se generaron dos capas, una de carga hidráulica (Disponibilidad) y otra de balance, ya están en el storage.
MEGADAPT_integracion/Procesamiento/OutputModelos/AguaSubterranea/Balance.shp
MEGADAPT_integracion/Procesamiento/OutputModelos/AguaSubterranea/Disponibilidad.shp

La hoja de cálculo con el modelo está en el storage:
MEGADAPT_integracion/Procesamiento/Codigo/Modelo_Agua_Subterranea/mod_agua_sub_Ene_2018.ods

**Comment by marcoajh** [comment]
Queda también pendiente hacer un informe que documente las condiciones de modelación con las cuales se obtuvieron éstos resultados.

**Comment by PaolaGomezPriego** [comment]
Marco: Está confirmada la reunión del 1 de febrero a las 9:00 con Eric Morales? @serranoycandela

**Comment by marcoajh** [comment]
Me puede recibir a las 15:30 de hoy (1 febrero)
