### ISSUE TITLE
Solicitar folios a Ana Cecilia #Organización APC

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#505]
Estoy en espera de que @ovisnigra me proporcione las ligas a los formatos para poder mandar el correo a Ana Celia con la petición.

**Comment by ovisnigra** [comment]
Ahi van: 

- [Liga al formulario de solicitud](https://docs.google.com/forms/d/e/1FAIpQLSdB_voN1q7SNMsaMvcEYSzMbiVClv05A9gss_z4M8ewT7R9wQ/viewform?usp=sf_link)
- [Liga al formulario de correcciones]( https://docs.google.com/forms/d/e/1FAIpQLScYX_1AKw6hg7VH8qV7P-qoQiJGuwamTqwJipNZxbkNautZzA/viewform?usp=sf_link)
- [Liga a la base de datos de las solicitudes](https://docs.google.com/spreadsheets/d/10VRhkBeX5culxvIMsY2bmQrCuv52PiMNnHnc8FDR1jE/edit?usp=sharing)
- [Liga a un documento de muestra generado mediante el formulario y la base de datos](https://drive.google.com/file/d/1MIw61HY9kiitVcBPJo2pzTVtmDqPL8qG/view?usp=sharing)

**Comment by edithvilla** [comment]
@ovisnigra ya le mandé el correo a Ana Cecilia, estoy en espera de su respuesta (17ene2018)

**Comment by ovisnigra** [comment]
Gracias. esperemos pues. saludos

**Comment by edithvilla** [comment]
22 de enero, Ana Cecilia no ha contestado mi correo para proporcionarnos los folios. Le mandaré un correo  para recordarle

**Comment by edithvilla** [comment]
@ovisnigra @PaolaGomezPriego 
Ana Cecilia contesto:

1. Establecer el procedimiento en el cual entran o se van a utilizar los formatos
2. Hay diferencia en los formatos (word-papel y digital) meta a largo plazo es tener  odo en digital
3. Es necesario cumplir con los requerimientos de documentos formales de lancis, las especificaciones se encuentran en el documento "Procedimiento de Control de Información Documentada". Este documento se encuentra en revisión por la Dra. Ana Escalante, se espera que este aprobado y lo puedan circular con la comunidad de LANCIS en dos semanas.

Para una solución rápida, se puede foliar con un número consecutivo sin mayor problema, mientras los formatos se incorporan a un procedimiento del área de planeación colaborativa

**Comment by edithvilla** [comment]
Estar al pendiente de cuando esta lista el Procedimiento de Control de Información Documentada con Ana Cecilia para pedirle una reunión

**Comment by edithvilla** [comment]
6 de febrero, 2018
Le mandé correo a Ana Cecilia para pedirle el documento: "Procedimiento de Control de Información Documentada".
