### ISSUE TITLE
No cambiar nombres de carpetas a compartir desde dropbox #organizacion_APC

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#507]
Al 17 de enero del 2018, actualicé el dropbox de mi máquina y sigue el problema de renombrar nombres de carpetas. Por lo tanto, si se requiere hacer esta operación tienen que volver a subir las carpetas renombradas.  
Sergio: plantillas sigue apareciendo como "plantillas" en mi máquina y no como "apc_plantillas" e hice la operación varias veces.

**Comment by ovisnigra** [comment]
Enterado. ¿Entonces vuelvo a subir las carpetas de APC?

**Comment by edithvilla** [comment]
@ovisnigra 
Yo no tuve ese problema y ya he puesto una carpeta en ORGANIZACION_APC
