### ISSUE TITLE
Revisar respaldo de sleuth #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#509]
Necesitamos reunirnos para revisar el respaldo de slueth y repartir responsabilidades

**Comment by edithvilla** [comment]
en el storage solo tenemos los archivos raster finales que se ocuparon para hacer la animación del modelo de crecimiento urbano.

**Comment by edithvilla** [comment]
@serranoycandela se comprometió hacer el respaldo del cluster (issue #510 )

**Comment by edithvilla** [comment]
@serranoycandela 

se encargará de hacer respaldo del código del modelo

**Comment by edithvilla** [comment]
@serranoycandela 
se encargará de hacer respaldo del código del modelo, por favor avísame cuando esté listo

**Comment by edithvilla** [comment]
@marcoajh 
¿Está completo el respaldo en el InputModelos\CrecimientoUrbano?, no veo el escenario 07 y 08

solo quiero confirmar contigo que está completo el respaldo. gracias

**Comment by marcoajh** [comment]
@edithvilla .
Todavía no le he solictado a @serranoycandela  los archivos para respaldarlos.

**Comment by PaolaGomezPriego** [comment]
reportar por este medio los avances
