### ISSUE TITLE
Revisar y corregir del el nombre de las colonias de las capas de encharcamientos por delegación  #Megadapt 

### ISSUE THREAD

**Issue by Didigar** [lancis-apc/planeacion-colaborativa#550]

**Comment by Nayita** [comment]
Concluido

**Comment by lancis-apc** [comment]
@yosunemiquela Nos indicas donde están los bancos de datos que se corrigieron la última vez. 
@serranoycandela Nos indicas cuáles son las colonias que siguen teniendo problemas

**Comment by lancis-apc** [comment]
@edithvilla

**Comment by serranoycandela** [comment]
hice un csv con las colonias que vienen de la base de datos de encharcamientos que no son compatibles con las colonias en el shapefile
/Dropbox/MEGADAPT/mega_procesamiento/banco_datos/encharcamientos_agebs/colonias_no_compatibles.csv

son 75 colonias

**Comment by yosunemiquela** [comment]
Aquí están los .csvs con los datos de Unidad Tormenta:

MEGADAPT/mega_insumos/febrero2018/yosune/bd_megadapt_encharcamientos

**Comment by lancis-apc** [comment]
@serranoycandela: para avanzar en el issue, URGE indiques cual es la capa que usaste de colonias

**Comment by lancis-apc** [comment]
@serranoycandela indica que es /Dropbox/MEGADAPT/mega_procesamiento/banco_datos/encharcamientos_agebs/colonias_charcos.csv

**Comment by edithvilla** [comment]
@yosunemiquela 

creamos una nueva carpeta (old) donde movimos el banco de datos por delegaciones que nos proporcionaste

MEGADAPT/mega_insumos/febrero2018/yosune/bd_megadapt_encharcamientos/old

y colocamos los nuevos en la raíz de la carpeta "bd_megadapt_encharcamiento"

le corregimos el encoding a todos los archivos

**Comment by edithvilla** [comment]
Edith Villa corregí:
ALVARO OBREGON_8 de Agosto          ALVARO OBREGON_8 DE AGOSTO
BENITO JUAREZ_8 de Agosto                BENITO JUAREZ_8 DE AGOSTO
BENITO JUAREZ_NARVARTE                  GUSTAVO A. MADERO_AMPL GABRIEL HERNANDEZ
BENITO JUAREZ_VERTIZ  NARVARTE     BENITO JUAREZ_VERTIZ NARVARTE
CUAJIMALPA_...N                                    CUAJIMALPA DE MORELOS_...N
CUAUHTEMOC_BUENA VISTA                CUAUHTEMOC_BUENAVISTA
CUAUHTEMOC_EX-HIPODROMO DE PERALVILLO         CUAUHTEMOC_EX-HIPODROMO DE PERALVILLO       
GUSTAVO A. MADERO_AMPL CASAS ALEMAN        GUSTAVO A. MADERO_CASAS ALEMAN
GUSTAVO A. MADERO_ARAGON             GUSTAVO A. MADERO_ARAGON 

En IZTAPALAPA no había esas colonias, ni en el csv ni en el dbf

**Comment by edithvilla** [comment]
corregí encoding de:
ALVAROOBREGON.csv
AZCAPOTZALCO.csv
BENITOJUÁREZ.csv
COYOACÁN.csv
CUAJIMALPA.csv
CUAUHTEMOC.csv
GUSTAVOMADERO.csv
IZTAPALAPA.csv
IZTACALCO.csv
MIGUELH.csv
MILPAALTA.csv
TLAHUAC.csv
TLALPAN.csv
VENUSTIANOCARRANZA.csv

**Comment by Nayita** [comment]
Listo!
XOCHIMILCO
MILPA ALTA
LA MAGDALENA CONTRERAS

Están corregidas y cargadas en dropbox

**Comment by yosunemiquela** [comment]
gracias!

**Comment by yosunemiquela** [comment]
Los nuevos análisis para Salud están en:
MEGADAPT/mega_procesamiento/banco_datos/Encharcamientos/Salud

**Comment by edithvilla** [comment]
@yosunemiquela 
ya están los encabezados corregidos de los csv de las delegaciones

**Comment by yosunemiquela** [comment]
MEGADAPT/mega_procesamiento/banco_datos/Encharcamientos/Salud

ya quedó
@serranoycandela

**Comment by edithvilla** [comment]
@yosunemiquela @serranoycandela @Nayita 

el archivo csv correspondiente a Iztapalapa lo restaure a la versión 20 de febrero 2018

MEGADAPT/mega_insumos/febrero2018/yosune/bd_megadapt_encharcamientos


voy a trabajar con esta versión y corregir las colonias

**Comment by edithvilla** [comment]
Ya corregí las colonias de Iztapalapa

IZTAPALAPA_EJÉRCITO DE AGUA PRIETA
IZTAPALAPA_POPULAR ERMITA ZARAGOZA
IZTAPALAPA_PUEBLO SANTA MARIA TOMATLAN
IZTAPALAPA_PUEBLO SANTA MARTHA ACATITLA

cambiaron por
EJERCITO DE AGUA PRIETA
CONJ URBANO POP ERMITA ZARAGOZA
SANTA MARIA TOMATLAN
PUEBLO SANTA MARTHA ACATITLA

**Comment by yosunemiquela** [comment]
Ya están las nuevas bases de datos:
MEGADAPT/mega_procesamiento/banco_datos/Encharcamientos/Salud
