### ISSUE TITLE
Incorporar Reseña Presentación Diputados (versión final) a carpeta de dropbox#IAI

### ISSUE THREAD

**Issue by bibianamonsivais** [lancis-apc/planeacion-colaborativa#551]
Hola @Nayita ,

La versión final de la Reseña de la Presentación a la Cámara de Diputados, ya está lista y disponible en la carpeta de IAI del Dropbox. Se localiza en la siguiente ruta: 
 IAI/iai_carpetas_trabajo/bibiana_monsivais/resena_diputados/Version_final/ y el nombre del archivo es:
resena_iai_pr_diputados_29mar2017.docx

Hay que buscrle casa en la carpeta de IAI.

Gracias!!!

**Comment by Didigar** [comment]
@bibianamonsivais 
Enterada, una vez que la suba a dropbox la incorporo

**Comment by bibianamonsivais** [comment]
@Nayita ya se colocó en la carpeta acordada:
IAI/iai_procesamiento/resena_diputados_29mar2017/resena_iai_pr_diputados_29mar2017.docx
