### ISSUE TITLE
Terminar de escribir protocolo de organización de discos duros #ORGANIZACION_APC

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#567]

**Comment by Nayita** [comment]
Protocolos a escribir:
Respaldo de información en discos duros
Software
gráficas
scripts que no son gráficas...análisis estadísticos

Incluir en algún protocolo los pasos a seguir para la reorganización del dropbox

**Comment by Nayita** [comment]
@yosunemiquela 
Sólo para formalizar lo acordado. Quedo en espera para el viernes 9 de marzo de tu manuscrito con la descripción de los estándares de calidad para entrega y recepción de los scripts de análisis estadísticos.
Gracias.

Saludos

**Comment by yosunemiquela** [comment]
Ya hice una guía de estilo ´para escritura de código en R. se encuentra en :
@Nayita 
/CARPETAS_TRABAJO/ymiquelajauregui

**Comment by Nayita** [comment]
@yosunemiquela 
Gracias Yosune ya quedamos con esto.

**Comment by Nayita** [comment]
@edithvilla 
Ya está puse el protocolo de entrega y recepción en mi carpeta de trabajo para que le incorpores tu parte.
CARPETAS_TRABAJO/nruiz
Gracias. Abrazo

**Comment by edithvilla** [comment]
@Nayita 
Ya agregué la sección de los mapa y corregí un par de detalles de redacción

CARPETAS_TRABAJO/nruiz/lancis_fed_pcr.docx

**Comment by Nayita** [comment]
Falta protocolo de organización de discos duros

**Comment by Nayita** [comment]
Se incorporó al protocolo de organización de activos de información
