### ISSUE TITLE
Revisar protocolos y manuales #organización APC

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#571]

**Comment by Nayita** [comment]
@edithvilla 
Voy a hacer los cambios de codificación de los documentos existentes y te aviso para poderlos revisar...

**Comment by Nayita** [comment]
Protocolo de logística
Agregar:
Petición de audios
Nombramiento de lista de asistencia
Registro de observaciones

**Comment by Nayita** [comment]
Hacer manual de registro de observaciones

**Comment by Nayita** [comment]
Agregar lo de uso de cámaras de video, fotos y grabadoras
Hablar con Ana Cecilia respecto al cuidado de datos personales y permisos para la lista de asistencia

**Comment by Nayita** [comment]
@ovisnigra @lancis-apc 
Hola Sergio, me comentó Paola que detectaste protocolos duplicados. Ya revisé la carpeta de protocolos y no encontré duplicados. Solo el md y el html de uno de ellos que obviamente se llaman igual. Si me indicas la ruta donde encontraste esos duplicados con mucho gusto lo reviso.
Gracias.

Saludos

**Comment by ovisnigra** [comment]
De todos modos voy a mandar un anuncio al gugl groups. No son protocolos, son un par de procedimientos con un nombre sospechosamente similar. Lo escribí todo en un archivo temporal que puse en la raíz de la carpeta, se llama `README_revision_carpeta.txt`. Para ahorrarte tiempo lo pego aquí:
***
Revisión de carpeta ORGANIZACION_APC

* apc_iso/formatos solicitud
  En esta carpeta hay dos archivos similares: `Formato de solicitud equipo LANCIS.docx` y `solicitud_de_equipo,_materiales_o_servicios.docx` revisar si son distintos o si solo debiera conservarse uno de los dos. De cualquier manera, el primero no tiene el formato de nombres que acordamos usar.

* Completar el README.txt de la carpeta `apc_repositorio_python`. Describir qué se supone que va a contener este directorio.

* Completar el README.txt de la carpeta `apc_repositorio_r`.

**Comment by Nayita** [comment]
@ovisnigra 
Oki Sergio, lo checamos con Edith...gracias

**Comment by Nayita** [comment]
@ovisnigra 
Ya checamos los formatos y son distintos. Uno es con el que pedimos las grabadoras y el otro es el interno que hiciste (supongo). Ya corregimos el nombre porque tenía el nombre bajo el cual nos dieron el archivo.
Edith dice que ya borró el README de python mientras no se vayan respaldando los códigos
Repositorio de r ya lo revisaré yo pero por el momento no es prioridad

**Comment by Nayita** [comment]
@lancis-apc 
Al revisar el protocolo de formato de entrega de datos (metadatos) sugerimos agregar a este protocolo

- Bases de datos

- Metadatos

- Gráficas

- Mapas (diseño)

- Scripts de análisis estadísticos

Cómo la ves? Das tu Vo. Bo.?

**Comment by edithvilla** [comment]
@Nayita @ovisnigra 

Nadia, coloqué el 
Procedimiento de organización general en:

ORGANIZACION_APC/apc_iso/procedimiento_organizacion_general.md

lo dejé en la raíz de la carpeta porque ya no es un protocolo

**Comment by Nayita** [comment]
@edithvilla 
Ponlo en la carpeta de procedimientos ;)

**Comment by edithvilla** [comment]
@Nayita 
ya está el marckdown en  
ORGANIZACION_APC/apc_iso/procedimientos

**Comment by edithvilla** [comment]
@Nayita 
ya está el manual de sigplan
ORGANIZACION_APC/apc_iso/manuales

se llama "manual_sigplan_oe_operador.doc"

**Comment by Nayita** [comment]
falta corregir el protocolo rmarkdown

**Comment by edithvilla** [comment]
@Nayita 
Ya actualicé el procedimiento de organización general, por favor podrías darle una revisada a la parte de la reorganización de carpetas del dropbox

ORGANIZACION_APC/apc_iso/procedimientos/procedimiento_organizacion_general.md

**Comment by edithvilla** [comment]
@13Emilio 

se encuentra una versión actualizada del protocolo de entrega y recepción de datos

ORGANIZACION_APC/apc_iso/protocolos/lancis_fed_pcr

**Comment by Nayita** [comment]
Concluido
