### ISSUE TITLE
Generar tablas de contingencia con resultados capacidad del drenaje #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#573]
Para reunión de SACMEX

**Comment by yosunemiquela** [comment]
Ya generé un .csv que contiene la información a nivel de AGEBs sobre frecuencia, volumen, tres índices de severidad con distintos pesos (V50,V75,V90), así como la información sobre capacidad (Yeowen).

**Comment by yosunemiquela** [comment]
En espera de ponerlo en la carpeta de dropbox
