### ISSUE TITLE
Generar parallel coordinates con resultados de capacidad del drenaje #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#574]
Yosune aporta la tabla por AGEB con todas las variables y Fidel lo integra a la plataforma.

**Comment by serranoycandela** [comment]
la tabla solo tiene 2052 registros pero en el DF hay 2432 agebs

**Comment by yosunemiquela** [comment]
Los csv para todas las AGEBS con la información de encharcamientos-precipitación-capacidad están aquí:

PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/ymiquelajauregui

**Comment by serranoycandela** [comment]
los veo y veo que hay como 400 agebs sin dato en Frecuencia, Volumen, FrecCateg, PecCateg, VolCateg, ProbaFP, ProbaVP, NormaFrec, NormaVol, IS50, IS90, IS75, Grupos y Grupos2

voy a asignarle 0 frecuencia 0 volumen para ensamblar en parallel coordinates pero me preocupa que esos 400 agebs deberían caer en la categoría mas baja de frecuencia de encharcamientos pues no tienen ningún reporte según entiendo 

y esas categorías se calcularon con cuantiles no? entonces al agregar esos 400 agebs con frecuencia 0 los cortes de las categorías deberían cambiar de lo contrario ya no serían cualtiles no?

voy a ensamblar de cualquier modo y mañana lo comentamos

**Comment by serranoycandela** [comment]
todo el chiste era poder mostrar los grupos así que para probar la idea dejé fuera a los agebs que no tenían grupo ni categoría, creo que lo debemos hacer completo pero aquí está la primer prueba
http://pc.magrat.mine.nu/parallel_coordinates_maps/39f6e134304b13d35c72079efb0ebf33
p.d. recuerden que para verse bien ocupa pantalla completa en una pantalla full hd

**Comment by yosunemiquela** [comment]
generé un csv. con la información concerniente a la frecuencia de tipo de encharcamiento por Colonia, Volumen maximo, promedio, y suma de frecuencia. cada observación tiene un OBJECT ID ( a excepción de unas cuantas Colonias en el archivo de SACMEX que no coinciden con la  base de datos de Colonia, cuyo origen es dudoso).
la ruta es :
PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/ymiquelajauregui

**Comment by serranoycandela** [comment]
para los agebs que me entregaron información ensamblé este parallel coordinates
http://pc.magrat.mine.nu/parallel_coordinates_maps/be6947c2e94a616cf98b4e895578ce70

**Comment by serranoycandela** [comment]
con escala nominal para los grupos y categorías mejora pero falta ordenarlos http://pc.magrat.mine.nu/parallel_coordinates_maps/e6bb35efbf40d3ac00b4273bc97a72ad

**Comment by yosunemiquela** [comment]
Los nuevos csv para las AGEBS con indices reescalados así como los {indices a nivel de colonia estén en:

PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/ymiquelajauregui/Datos_procesados

**Comment by PaolaGomezPriego** [comment]
Se cambiaron nombres de campos, se reordenaron columnas de índices y se normalizaron valores de índices. Listo para la siguiente actualización @serranoycandela 
ubicación de insumo: 
PRESENTACIONES\pr_megadapt_sacmex_20feb2018\insumos\fserrano

**Comment by PaolaGomezPriego** [comment]
ya se se normalizaron los tres indicadores del análisis de redes de drenaje (capacidad, densidad y conectividad) y se actualizó el dbf: agebs_soc_ench_y_pc4

**Comment by serranoycandela** [comment]
http://pc.magrat.mine.nu/parallel_coordinates_maps/3ff35265de475f4b004594c77c4a542a

**Comment by serranoycandela** [comment]
ok aquí está un parallel coordinates con:
(Capacidad, Conectividad, Densidad, IS50, IS75, y IS90)  normalizados y con densidad de unidades economicas (U_Econo)
http://pc.magrat.mine.nu/parallel_coordinates_maps/5c4e14c30a705b3386bbe6318846ed53

**Comment by PaolaGomezPriego** [comment]
@aleestrada  Verificar datos de rezago
Eliminar índice de 90

**Comment by PaolaGomezPriego** [comment]
@yosunemiquela dar datos de volumen máximos
Agregar volumen máximo a PC.

**Comment by yosunemiquela** [comment]
calculé VolMax y ya está a nivel de AGEB. La ruta al archivo es:
PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/ymiquelajauregui/Datos_procesados/Encharcamientoswet_VolMax.csv

**Comment by serranoycandela** [comment]
Los datos de rezago ya se corrigieron

**Comment by serranoycandela** [comment]
aquí está http://pc.magrat.mine.nu/parallel_coordinates_maps/4c369dd71f8ff6af943e81eb460049f1

**Comment by serranoycandela** [comment]
con VolProm
http://pc.magrat.mine.nu/parallel_coordinates_maps/05a6333cad5ffe9a0ceb0d0c901fc29e

**Comment by PaolaGomezPriego** [comment]
Falta poner el nombre del último shapefile utilizado

**Comment by serranoycandela** [comment]
el ultimo parallel coordinates que se generó, osea:
http://pc.magrat.mine.nu/parallel_coordinates_maps/05a6333cad5ffe9a0ceb0d0c901fc29e
se hizo con este shapefile:
/pr_megadapt_sacmex_20feb2018/insumos/fserrano/agebs_soc_ench_y_eco6.shp
