### ISSUE TITLE
Proporcionar plantilla de html para protocolos #GENERAL

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#585]
@ovisnigra necesitamos que nos proporciones la plantilla que utilizaste para en el protocolo de presentaciones que escribiste. Yo tengo mi markdown pero cuando lo guardo como html, no me queda igual al tuyo. Yo hago la conversión con "pandoc"

**Comment by ovisnigra** [comment]
El procedimiento es más o menos así:

1. Instalar [Pandoc](https://pandoc.org/installing.html)
2. Copiar los archivos `github.css` y `comandos_pandoc.txt` de la carpeta `ORGANIZACION_APC\apc_iso\protocolos\protocolo_organización_presentaciones\procesamiento` a la carpeta donde esté el archivo que se quiere convertir.
2. Abrir Windows PowerShell
3. Navegar a la ruta del archivo (copiar la ruta y en el PowerShell teclear: `cd + la ruta que copiaste entrecomillada`
4. Una vez en el directorio donde está nuestro archivo seguir las instrucciones de las primeras líneas del archivo `comandos_pandoc.txt`:
 
```
pandoc ORIGEN.md -s -c github.css --self-contained -o DESTINO.html

```
 Sustituir `ORIGEN.md` por el nombre del archivo markdown y `DESTINO.html` por el nombre que llevará el html (qué idealmente sería el mismo que el MD.

y ya, con eso debería bastar. Revisen que la conversión haya funcionado en su carpeta y si detectan algún error en el HTML, posiblemente tengan que corregir el MD y volver a hacer la conversión. No cierren el PowerShell hasta haber verificado el resultado. Para volver a correr un comando en el Shell basta apretar las flechas hacia arriba y volver a dar ENTER. Cualquier duda, me dicen.

**Comment by edithvilla** [comment]
@ovisnigra 

ya tengo mi archivo en .md, traté de seguir tus instrucción pero me marcaba un warning. Me podrías enseñar cómo hacerlo ahora que vengas al lancis??

**Comment by ovisnigra** [comment]
sí, lo vemos. de mientras ¿podrías copiar el _warning?_

**Comment by edithvilla** [comment]
@ovisnigra @Nayita 

ya puedo convertir de markdown a html

instalé el pandoc en mi computadora para poder hacer la conversión

**Comment by edithvilla** [comment]
@Nayita 
ya están los html de:

lancis_fed_pcr.html
protoco_estruc_nom_informes.html
protocolo_logistica.html
protocolo_org_clases_posgrado.html
protocolo_recursos_financieros.html

ORGANIZACION_APC/apc_iso/protocolos
