### ISSUE TITLE
Reorganizar la carpeta de IAI #organización APC

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#599]

**Comment by Nayita** [comment]
@edithvilla 
De tu carpeta de trabajo de IAI qué muevo a insumos y qué envío a tu carpeta de trabajo?

**Comment by Nayita** [comment]
@edithvilla 
Por fa, checa también la carpeta iai_respaldo, principalmente la carpeta de plataforma_anfiteatro_megadapt

**Comment by Nayita** [comment]
Faltan rastrear archivos y Edith revisará carpeta.

**Comment by edithvilla** [comment]
@Nayita 

1. La carpeta de plataforma_anfiteatro_megadapt, ya está re ubicada en presentaciones de megadapt

2. En cuanto al reporte financiero que me comentaste ayer  IAI/iai_convenios_reportes_financieros/3_tercera_entrega_may2016

el archivo que está lleno es: formato_de_reporte_financieroepvm.xlsx
no digo que este formato sea el que mandaron porque tiene cosas marcadas pero si es el que esta lleno

**Comment by Nayita** [comment]
concluido
