### ISSUE TITLE
Hacer secuencia de slides  y dar formato a slides para presentación SACMEX

### ISSUE THREAD

**Issue by ovisnigra** [lancis-apc/planeacion-colaborativa#601]
Con fecha Tue, 13 Feb 2018, 17:43 Paola Gómez ha mandado una nueva solicitud de trabajo con los siguientes datos:

-- | --
-- | --
Email address | pgomez@iecologia.unam.mx
Solicitante | Paola Gómez
Tipo de solicitud | Diseño
Fecha requerida de entrega | Wed, 14 Feb 2018, 00:00
Proyecto | Megadapt
Prioridad | Urgente (esencial para el cumplimiento del proyecto)
Datos del producto o servicio
Producto o servicio | Figura(s)
Número de elementos | 4 slides de figuras
Formato de salida | PNGSLIDE para anfiteatro
Insumos | PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/pgomez/pr_megadapt_cesop_labt_09ago2017.pptx
Comentarios u observaciones | Hay que hacer una secuencia de SLIDES del diagrama de flujo de las diapositivas 5, 6 y 7. No solo es formato, es la creación de un diagrama de flujo bonito. También crear slides de las diapositivas 13-16 con las ÚLTIMAS versiones de las figuras.
Cómo deben llamarse los archivos generados | sl_5, sl_6 y sl_7 y para el resto sl_20, sl_21..etc.
Dónde guardar | PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/plataforma
Destino del producto | presentación SACMEX
Palabras clave | sacmex, encharcamientos, drenaje, taller megadapt
Uso posterior | El producto se puede usar para otros fines y se puede agregar al repositorio de LANCIS

**Comment by ovisnigra** [comment]
Empecé por la segunda parte de la solicitud. Ya están cargadas las slides 13 a 16 en formato final en la siguiente ruta:

`PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/plataforma/slides`

los insumos temporales para generar estas slides quedan en:

`PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/pgomez/sl_13-16`

Continúo con la primera parte que es hacer la secuencia de las slides 5, 6 y 7. Me comunico si hay dudas.

**Comment by ovisnigra** [comment]
listas las slides 5 a 8 en carpeta de plataforma

PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/plataforma/slides

los insumos temporales para generar estas slides quedan en:

PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/pgomez/sl_5-8

Quedo pendiente por si hubiera correcciones.

**Comment by PaolaGomezPriego** [comment]
Ya están listas para una nueva secuencia las diapositivas 13-15

**Comment by PaolaGomezPriego** [comment]
Borré la última instrucción hasta mañana

**Comment by PaolaGomezPriego** [comment]
ahora si, agregar secuencia de la 19 a la 24

**Comment by PaolaGomezPriego** [comment]
también ya está lista la secuencia 14 y 15

**Comment by ovisnigra** [comment]
lista la secuencia 19-23 (quedó una menos porque eliminé una que me pareció innecesaria).

 Ya están cargadas las slides en la plataforma y el PPT modificable en tu carpeta de insumos.

Revisa y me dices.

**Comment by PaolaGomezPriego** [comment]
@Nayita mencionará los cambios de numeración de slides por este medio

**Comment by PaolaGomezPriego** [comment]
migrar a   /procesamiento/figuras

**Comment by ovisnigra** [comment]
## Notificaciones viernes 16 de febrero:

1. Ya están arriba las slides 5-8, 19-25 y 14-15* en la carpeta `...plataforma/slides`
2. \* las slides 14 y 15 terminaron siendo 3 (por la estructura del contenido y por congruencia con las otras secuencias), las numeré como: 140, 150 y 160 para evitar sobreescribir la slide 16.
3. Ya migré de slides que había guardado en tu carpeta de insumos, ahora están en `...procesamiento/figuras` como pediste, ahí encontrarás los archivos PPT de las slides.
4. Sigo ahora con la slide 25, que me notificaste vía WhatsApp que ya estaba lista.

**Comment by PaolaGomezPriego** [comment]
1. me gustó mucho mas como quedó esta vez.
2. en la secuencia 14-16 le agregué a la caja de proporciones: Análisis de proporciones, para que quede como paso.  me gustó.
3. gracias. 
4. quedaron muy bien!
5. ok.

**Comment by PaolaGomezPriego** [comment]
favor de hacer slides. No preocuparse por la numeración solo respetar las de las secuencias.

**Comment by ovisnigra** [comment]
Por lo que mencionas en el punto **2**, entonces vuelvo a generar el slide final de la 16 para que refleje ese cambio que hiciste ¿cierto?

**Comment by PaolaGomezPriego** [comment]
si a la respuesta del punto 2

**Comment by ovisnigra** [comment]
ok. ya quedó actualizado en plataforma también (sl_160)

**Comment by PaolaGomezPriego** [comment]
6. re-haces slides de diapositivas de la 3 y 4?

**Comment by PaolaGomezPriego** [comment]
PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/pgomez/nodos_red_desalojo 
aquí se encuentran los datos que alimentan la diapositiva 25 de mi presentación

**Comment by PaolaGomezPriego** [comment]
también por favor haz la diapositiva del título.

**Comment by Nayita** [comment]
@PaolaGomezPriego 
Listos slides de las gráficas en plataforma/slides

**Comment by ovisnigra** [comment]
ya están las slides 25 y 26 con todo y gráfica. las nombré 250 y 260 pa no sobreescribir

**Comment by PaolaGomezPriego** [comment]
Re-inicio numeración de asuntos:
1. volver a hacer slide de la diapositiva 3, ahora se llama sl_2_02 y ya te la puse en procesamiento
2. Revisar y volver a hacer slide de la 15, ahora se llama sl_10_02

**Comment by PaolaGomezPriego** [comment]
3. la 25 y 26 tienen problema la segunda tabla de nodo mas grande no es título.. los dos puntos son una lista y no tienen que ir en negritas. Las tablas cuando se ponen una sobre otra se mueven la ubicación de los números entre la primer tabla, yo se que fue mi error pero igual se ve feo.

**Comment by PaolaGomezPriego** [comment]
No se que tanto te lleve subirle un poco al tono de azul a los cuadros, se ven muy claros en el anfiteatro. Me encanta el color, pero ya sabes como son estas pantallas. Verifica la numeración cuando crees las slides.  Ya están renumeradas todas las slides de como van a quedar en el guión.

**Comment by PaolaGomezPriego** [comment]
2. TAMBIÉN volver a hacer slide de la 16, ahora se llama sl_10_03

**Comment by PaolaGomezPriego** [comment]
4. de las que tenías 19-25, les cambié el título. volver a hacer slides con nuevos nombres. son la secuencia sl_7_01 hasta la 7_07

**Comment by ovisnigra** [comment]
Listo todo excepto:

> No se que tanto te lleve subirle un poco al tono de azul a los cuadros, se ven muy claros en el anfiteatro. Me encanta el color, pero ya sabes como son estas pantallas. Verifica la numeración cuando crees las slides. Ya están renumeradas todas las slides de como van a quedar en el guión.

¿a cuál azul te refieres exactamente? al que usamos en los esquemas de pasos, ahí usé un azul un poco más tenue cuando son pasos anteriores, ¿ese es el que se pierde? o te refieres a todos los nombres de pasos en general?

Sí me lleva un rato, pero lo puedo hacer si quieres, nomás aclárame cuáles son los que hay que cambiar.

**Comment by ovisnigra** [comment]
lo de la numeración sí lo chequé

**Comment by PaolaGomezPriego** [comment]
ya deja así lo de los colores. solo anota que el color (incluso el de un paso nuevo) no se ve con suficiente contraste con el color blanco de las letras.

**Comment by ovisnigra** [comment]
enterado

**Comment by PaolaGomezPriego** [comment]
Dar formato a las 5 tablas (de la diapositiva de powerpoint 16 en adelante), para que los altos de columna queden iguales y todos los títulos queden centrados a lo alto.  La tabla 5 se está actualizando en este momento y se va a tardar unos minutos.

**Comment by Nayita** [comment]
@ovisnigra 
No tocar nada de esta presentación por fa. Gracias
