### ISSUE TITLE
Cargar archivos con funciones de valor en plataforma GeoValue Functions con base en funciones hipotéticas #megadapt

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#604]
Para la presentación de SACMEX, tener ejemplos de funciones de valor del modelo.

**Comment by lancis-apc** [comment]
1. Revisar última versión de red para verificar la importancia de las capas que requieren función de valor. 
2. Verificar la calidad las capas de información @edithvilla revisa y si tiene dudas, le pregunta a @serranoycandela 
3. Precargar y tener listas para las sesiones con SACMEX
