### ISSUE TITLE
Hacer etiqueta de cd SACMEX

### ISSUE THREAD

**Issue by ovisnigra** [lancis-apc/planeacion-colaborativa#605]
Con fecha Tue, 13 Feb 2018, 14:01 Edith Villa Mendoza ha mandado una nueva solicitud de trabajo con los siguientes datos:

-- | --
-- | --
Email address | epvmendoza@gmail.com
Solicitante | Edith Villa Mendoza
Tipo de solicitud | Diseño
Fecha requerida de entrega | Thu, 15 Feb 2018, 00:00
Proyecto | Megadapt
Prioridad | Urgente (esencial para el cumplimiento del proyecto)
Datos del producto o servicio
Producto o servicio | Hacer etiqueta de cd
Número de elementos | 1
Formato de salida | DOCX (Word)
Insumos | Issue #580
Cómo deben llamarse los archivos generados | etiqueta_megadapt_sacmex_20feb2018
Dónde guardar | PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/logistica
Destino del producto | Entrega de archivos en un CD
Uso posterior | El producto se puede usar para otros fines y se puede agregar al repositorio de LANCIS

**Comment by ovisnigra** [comment]
@edithvilla Hay un problema con el llenado de la forma. Los datos de la etiqueta deberían estar en la solicitud misma, no en otro issue de GH. Me refiero a estos datos:

Título: Síntesis de encharcamiento y Red de desalojo de la Ciudad de México
Logotipos: UNAM, LANCIS, NSF, IAI
Fecha: 20 de febrero, 2018

Por ahora lo tomo así, pero por favor no me hagan eso. La solicitud está hecha para que tenga toda al información necesaria, debemos usarla así. Creo yo.

**Comment by ovisnigra** [comment]
espero tenerlo para mañana como me pides

**Comment by edithvilla** [comment]
@ovisnigra entendido y anotado. la corrijo de todos modos para que la tengas bien. solo me quedó la duda del formato de salida, que le pongo??? en qué formato me la entregas?

**Comment by ovisnigra** [comment]
el formato lo tengo en Illustrator

**Comment by ovisnigra** [comment]
lista etiqueta. 

Creé la carpeta `etiqueta_megadapt_sacmex_20feb2018` dentro de  `PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/logistica`

Archivos principales: `etiqueta_megadapt_sacmex_20feb2018.ai` y `etiqueta_megadapt_sacmex_20feb2018.pdf` cualquiera de estos dos sirve para imprimir (solo que el de illustrator necesita que tengas cargada la fuente Cronos, si quieres hacer cambios. También en la carpeta están los archivos de lo logos, necesarios para abrir el archivo AI.

Haz pruebas de impresión y me dices si jalan. Quedo pendiente. Estaré conectado al menos un par de horas más. Saludos
