### ISSUE TITLE
Organizar contenido de discos duros por proyecto#organización APC

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#608]

**Comment by edithvilla** [comment]
@Nayita 
Se le asignaron las carpetas del dropbox al disco nuevo Seagate de 2T
CAPACITACION
ORGANIZACION_APC
PUBLICACIONES
SOFTWARE

**Comment by edithvilla** [comment]
@Nayita 
actualice la lista de los archivos de los discos duros en el google drive
solo agregué en el de pacífico norte la fila 66

**Comment by Nayita** [comment]
Se ha concluido con 2 discos duros. en total 8 proyectos: Apatlaco, CVM, PN, ZOFEMAT, REPECHIQUE, Climate products, SSGDU e INVASORAS.

**Comment by Nayita** [comment]
Esta semana comenzaremos con los respaldos personales y los de administración. Cada respaldo estará en un solo disco.

**Comment by Nayita** [comment]
Se está terminando con los archivos referentes a administración. Esta semana se termina con esto  y con los respaldos de los colaboradores

**Comment by Nayita** [comment]
Se concluyó con el disco de respaldo de colaboradores.
Hay proyectos pequeños sueltos que se agruparán en un solo disco y se llamarán OTROS

**Comment by Nayita** [comment]
No se pudo concluir esta semana con el respaldo de todos los proyectos o archivos que se agruparán en OTROS. Tienen nombres muy largos y la conversión a ZIP es muy tardada. Esta semana sin falta se concluye con esta tarea.

**Comment by Nayita** [comment]
Concluido
