### ISSUE TITLE
Verificar capas de nodos red desalojo #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#610]
1. Verificar diámetros en todas las capas (secas y lluvias). 
2. Verificar porque no hay diámetros en las lumbreras. 
2. Si no hay nodos en tanque tormenta, eliminar esa columna.
3. Verificar los nombres de las estructuras que tienen celdas vacías y confirmar si incluyen el número de la delegación. 

@Nayita

**Comment by PaolaGomezPriego** [comment]
5. Hay dos nodos que no tienen estructura en los nodos de secas.

**Comment by PaolaGomezPriego** [comment]
/presentaciones/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/pgomez/pr_megadapt_cesop_labt_09ago2017.pptx 
en las diapositivas 25 y 26 está la caracterización de los nodos de las dos capas

**Comment by edithvilla** [comment]
@PaolaGomezPriego @Nayita 

1. Estoy verificando lo de los diámetros
2. Las únicas lumbreras que no tienen diámetro son las que pertenecen al Túnel Emisor Poniente, así que hay que completar las faltantes, excepto si son Plantas de Bombeo o alguna estructura parecida que no teníamos datos del diámetro
3. Nadia está verificando los tanques tormentas en los informes
4. Las capas de los nodos ya están completos con los nombre o con el número de la estructura
5. Ya están completos los nodos de secas con las estructuras

PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_20feb2018\capas_a_entregar\

**Comment by Nayita** [comment]
@PaolaGomezPriego

Ya están revisadas y corregidas las capas de los nodos de lluvias y secas

PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_20feb2018\capas_a_entregar\

**Comment by edithvilla** [comment]
@PaolaGomezPriego 
la actividad de:
Revisar la información de plantas de tratamiento, ya está lista
el único nodo que hay se cambia a Planta de Bombeo y se elimina la columna Planta_Trat, en las dos capas (lluvias y seas)

**Comment by lancis-apc** [comment]
1. Revisar los errores mas graves de ubicación de nodos entre la capa de red de desalojo de SACMEX y la nuestra. 
2. Identificar los puntos mas importantes para revisar con la gente SACMEX

**Comment by lancis-apc** [comment]
3. Preguntar si se deben desconectar TODOS los tanques tormenta. Ing. Pérez comentó en la reunión que ya todos se conectan a los colectores.

**Comment by edithvilla** [comment]
UBICACIÓN DE LA INFORMACIÓN:
\MEGADAPT\mega_sig\infraestructura

**Comment by edithvilla** [comment]
actividad cancelada
