### ISSUE TITLE
Crear serie web para presentación sacmex en anfiteatro #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#611]
Nodos y trazos diferenciados por colores para lluvias y secas.

**Comment by PaolaGomezPriego** [comment]
ver jsons o capas de origen. 
SACMEX: /presentaciones/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/sacmex/INFRAESTRUCTURA%20HIDRAULICA%20DF_SACMEX_020915/DESALOJO/red_desalojo_primario
Nosotros: 
/presentaciones/pr_megadapt/pr_megadapt_sacmex_20feb2018/capas_a_entregar

**Comment by serranoycandela** [comment]
estoy experimentando con leaflet
http://patung.mine.nu/~fidel/qgis2web_2018_02_16-00_08_31_286522/#12/19.3910/-99.1095
que opinas @PaolaGomezPriego ?

**Comment by serranoycandela** [comment]
o con el ancho según el diámetro
http://magrat.mine.nu/~fidel/qgis2web_2018_02_16-01_01_16_134913/#12/19.4282/-99.0998

**Comment by serranoycandela** [comment]
con puntos de colores y mas grandes
http://magrat.mine.nu/~fidel/qgis2web_2018_02_16-12_33_51_219581/#12/19.3524/-99.1296

**Comment by PaolaGomezPriego** [comment]
hacer:
1. Lluvias
2. Secas
3. LLuvias & red_desalojo primario
4. Red de desalojo primario

**Comment by serranoycandela** [comment]
1 Lluvias : http://magrat.mine.nu/~fidel/lluvias/#11/19.3951/-99.1319
2 Secas : http://magrat.mine.nu/~fidel/secas/#11/19.3951/-99.1324

**Comment by serranoycandela** [comment]
3 Lluvias y red de SACMEX http://magrat.mine.nu/~fidel/comparacion/#12/19.3759/-99.1066

**Comment by serranoycandela** [comment]
comparación http://magrat.mine.nu/~fidel/qgis2web_2018_02_16-16_32_40_870203/#13/19.3738/-99.1547

**Comment by lancis-apc** [comment]
terminado.
