### ISSUE TITLE
Calcular estadísticas descriptivas por grupo de tabla de frecuencias de AGEB #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#620]
Calcular población total, ingreso promedio, rezago promedio, y promedio de densidad de unidades económicas por grupo de AGEB. Entregar tablas. 

Ver tabla en diapositiva 16 para modelo de llenado en:
pr_megadapt_sacmex_20feb2018\procesamiento\figuras\sl_14-16

**Comment by yosunemiquela** [comment]
PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/ymiquelajauregui /Caracterización de los grupos de AGEBS.pptx

**Comment by yosunemiquela** [comment]
ya quedaron las diapositivas con las tabals de contingencia para cada indicador requerido  

PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/ymiquelajauregui/sl_14-16

**Comment by yosunemiquela** [comment]
ya quedó!
PRESENTACIONES/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/ymiquelajauregui/sl_14-16
