### ISSUE TITLE
Hacer figura y slide de red superdecisions SACMEX

### ISSUE THREAD

**Issue by ovisnigra** [lancis-apc/planeacion-colaborativa#621]
Con fecha Fri, 16 Feb 2018, 18:27 Paola Gómez ha mandado una nueva solicitud de trabajo con los siguientes datos:

-- | --
-- | --
Email address | pgomez@iecologia.unam.mx
Solicitante | Paola Gómez
Tipo de solicitud | Diseño
Fecha requerida de entrega | Mon, 19 Feb 2018, 00:00
Proyecto | Megadapt
Prioridad | Urgente (esencial para el cumplimiento del proyecto)
Datos del producto o servicio
Producto o servicio | Figura(s)y slide
Número de elementos | 1
Formato de salida | PNG
Insumos | /presentaciones/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/lbojorquez/
Comentarios u observaciones | el archivo estoy por ponerlo en esa ubicación pero será el único en formato superdecisions
Cómo deben llamarse los archivos generados | fi_megadapt_esquema_red_sacmex
Dónde guardar | /presentaciones/pr_megadapt/pr_megadapt_sacmex_20feb2018/procesamiento/figuras
Destino del producto | presentación sacmex
Palabras clave | red superdecisions sacmex modificada Bojorquez 16 feb 2018
Uso posterior | El producto se puede usar para otros fines y se puede agregar al repositorio de LANCIS

**Comment by PaolaGomezPriego** [comment]
sl_16 y sl_17

**Comment by ovisnigra** [comment]
@PaolaGomezPriego ya están prácticamente listas, sólo me falta saber qué título llevan las slides

**Comment by PaolaGomezPriego** [comment]
Títulos para slides: red de escasez de agua  y 2 red de inundaciones

**Comment by ovisnigra** [comment]
listas las slides en carpeta de plataforma.

las figuras en AI y PNG, así como el PPT quedan en:  `PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_20feb2018\procesamiento\figuras\fi_megadapt_esquema_red_sacmex_sl_16-17`

**Comment by PaolaGomezPriego** [comment]
Invertir los títulos (escasez de agua e inundaciones)
Corregir risegos
Cambiar a azul.
