### ISSUE TITLE
Reportar los productos que se generaron el periodo junio-diciembre 2017 #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#631]
NSF y ASU están pidiendo estos reportes de MEGADAPT. Como sus ingresos y becas salieron de ahí, necesitamos un párrafo por producto o persona. Incluir productos de Diana, Marco y Luis Octavio. 

Favor de poner la información en esta ubicación:
/ADMIN/megadapt

**Comment by edithvilla** [comment]
@PaolaGomezPriego @dpedroza74 @bibianamonsivais @Nayita @rociobrito @aleestrada @ovisnigra 

Ya está la tabla con la lista de productos, colaboradores y ubicación de los productos.

Falta ubicar un par de productos.

Sergio y Alejandra, pueden incorporar sus datos a esta tabla

**Comment by dpedroza74** [comment]
Te lo envié por correo ayer y estoy atenta por si hay cosas que corregir o aclarar

**Comment by ovisnigra** [comment]
@edithvilla ¿puedes indicar la ruta o el link a la tabla plis?

**Comment by aleestrada** [comment]
Se agregó en la tabla los productos generados en el semestre, junto con su ubicación.

**Comment by Nayita** [comment]
@edithvilla 
Que si se agregue lo de reescalamiento de Marco. Falta poner ubicación.
Lo de Diana ya está resuelto.

Saludos

**Comment by ovisnigra** [comment]
listo

**Comment by edithvilla** [comment]
@PaolaGomezPriego @rociobrito 

La tabla ya está lista, ya quedó listo lo de Marco

**Comment by Nayita** [comment]
Concluido
