### ISSUE TITLE
Integrar el registro de observaciones de la reunión de SACMEX #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#632]
@PaolaGomezPriego  ya está lista de integración del registro de observaciones:

PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_20feb2018\insumos\pgomez\SACMEX_engagement_obs_20feb2018.docx

**Comment by PaolaGomezPriego** [comment]
@bibianamonsivais

**Comment by PaolaGomezPriego** [comment]
Ya lo revisé.

**Comment by bibianamonsivais** [comment]
@PaolaGomezPriego ,

Ya agregué los comentarios en el registro. Lo ubiqué en:

PRESENTACIONES\pr_megadapt\pr_megadapt_sacmex_20feb2018\logistica\rep_obs_pr_sacmex_20feb2018.docx

**Comment by Nayita** [comment]
@edithvilla 
Que si se ponga lo del reescalamiento que hizo Marco. No se dónde está el archivo, tu sabes? lo puedes agregar?
Lo de Diana ya está resuelto

**Comment by Nayita** [comment]
Concluido
