### ISSUE TITLE
Organizar carpeta de pr_megadapt_sacmex20feb #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#636]
1. Organizar procesamiento. 
2. Eliminar slides que no se usaron.
3. Crear pdf. 
4. Hacer guión que incluya sitios de PC y FV.

**Comment by Nayita** [comment]
@PaolaGomezPriego 
1. En procesamiento/ en la carpeta figuras sólo había algunos slides utilizados (9). Hice una nueva carpeta llamada slides. Copio el resto de los slides utilizados a esta carpeta?
2. Eliminados

**Comment by Nayita** [comment]
Concluida
