### ISSUE TITLE
Agregar páginas de internet a la presentación #presentación SACMEX

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#644]

**Comment by Nayita** [comment]
@lancis-apc 
Listo. Se encuentran en: presentaciones/pr_megadapt/pr_megadapt_sacmex_20feb2018
El archivo se llama pr_megadapt_sacmex_20feb2018_v2

**Comment by lancis-apc** [comment]
gracias. Ya se envió a Yeowon, Hallie y Rebecca. Se cierra.
