### ISSUE TITLE
resamplear a agebs la capa de frecuencias de encharcamientos #megadapt

### ISSUE THREAD

**Issue by serranoycandela** [lancis-apc/planeacion-colaborativa#647]

**Comment by yosunemiquela** [comment]
Aquí está la ruta con los dos .csv para los periodos 2007-2009 y 2010-2014
MEGADAPT/mega_procesamiento/banco_datos/Encharcamientos/Salud

**Comment by lancis-apc** [comment]
@yosunemiquela 
1. Actualizar ubicación de bancos de datos conforme a protocolo. 
2. Generar capas por año para subir a plataforma
3. Actualizar análisis de severidad.

**Comment by serranoycandela** [comment]
Este issue es un duplicado del issue 640
