### ISSUE TITLE
Manuales de SIGPLAN #OGANIZACION

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#649]
@lancis-apc 
este es el path del manual del SIGPLAN

SOFTWARE/sigplan/docs/manuales

**Comment by edithvilla** [comment]
@lancis-apc @serranoycandela 

Se puede acceder a la plataforma con la siguiente URL

192.168.1.191/ecologia/login

1. Seleccionar proyecto

2. Usuario y contraseña (operador1)

4. El manual de usuario se encuentra 

SOFTWARE/sigplan/docs/manuales/OE Manual - Operador.doc

5. El archivo Plataforma_Aptitud_LEME.txt es el archivo que Marco dejó con las especificaciones para cuando no se conecta por problemas de la IP
SOFTWARE/sigplan/Plataforma_Aptitud_LEME.txt

**Comment by edithvilla** [comment]
Comentarios a la plataforma SIGPLAN

1. Creación de atributos
   No se entiene lo de la sumatoria de los atributos, se necesita un mejor aviso
   
2. Preparación de capa,
	Preparar un protocolo para el nombramiento de las capas
	
3. Función de valor
	
	En la vista previa faltan las unidades de los datos
	los parámetros mínimo y máximo que aparecen tienen que ser los de la capa 
	Descripción de los parámetros de cada función
	la ecuación de la función de coseno
	En la función de valor discreta no se puede escribir el guión bajo
		
	Una vez generado el mapa de función de valor no se despliegan decimales en los parámetros "mínimos" y "máximos"

**El nombramiento de las capas deberá de hacer automático, tomando los nombres de los sectores, aptitud

4. Análisis de aptitud

	Nombre del mapa, que sea automático
	
	Reducir la transparencia del mapas de aptitud

**Comment by serranoycandela** [comment]
la aplicación está en:
pulque.mine.nu/ecologia/login
