### ISSUE TITLE
Pasar a formato html el procedimiento, el protocolo y manuales#organización apc

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#650]

**Comment by Nayita** [comment]
@edithvilla 
Hola Edith, estos son los protocolos que requieren ser reelaborados en html
protocolo_estruc_nom_informes
protocolo_org_clases_posgrado
protocolo_peticionservicio
protocolo_recursos_financieros

**Comment by edithvilla** [comment]
@Nayita 
Ya están los html en el dropbox:
protocolo_estruc_nom_informes
protocolo_org_clases_posgrado
protocolo_peticionservicio
protocolo_recursos_financieros
protocolo_gr_ma_html

**Comment by Nayita** [comment]
hecho
