### ISSUE TITLE
Generar layers de frecuencia y volumen de encharcamientos agregado por ageb para SESMO #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#652]
1. Con identificación de umbral entre encharcamiento e inundaciones y agregado para todo el periodo. 
2. Con base en resampleado por ageb. 
3. Generar layers independientes de encharcamientos e inundaciones. 
4. Poner /MEGADAPT/mega_layers/sesmo 
4. Documentar

avisar en cuanto esté listo a @abaezacastro

**Comment by yosunemiquela** [comment]
Los datos están en:
MEGADAPT/mega_layers/sesmo/
Falta adjuntar script y metadatos
Fidel hará el resampling para generar los layers
@serranoycandela @abaezacastro

**Comment by serranoycandela** [comment]
las capas resultantes están en la carpeta MEGADAPT/mega_layers/sesmo/
y se llaman agebs_encharcamientos_0714.shp y agebs_inundaciones_0714.shp

**Comment by abaezacastro** [comment]
gracias @serranoycandela 
hay que poner estas capas junto con las capas de Layers para hacer el join de agebs_abm.shp

**Comment by serranoycandela** [comment]
el join está listo en 
MEGADAPT/mega_layers/sesmo/agebs_abm.shp
