### ISSUE TITLE
Hacer relación de insumos para la página web#ORGANIZACIÓN APC

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#667]

**Comment by Nayita** [comment]
@ovisnigra @lancis-apc 
Hola Sergio, ya agregué una hoja más en la hoja de datos de google drive Organización_General. Se llama Insumos_página_web. Ahí pondré las rutas de los protocolos y manuales una vez que ya estén en html, así como los códigos y las páginas útiles. 

Te estaré notificando cada vez que vaya cuando ya haya terminado de llenarla.

Saludos

**Comment by ovisnigra** [comment]
@Nayita @lancis-apc 
Les propongo que en lugar de poner las rutas en la hoja de Organización General, pongan las rutas en este issue: #660 

por favor, por favorcito

**Comment by Nayita** [comment]
@ovisnigra @lancis-apc 
Oki. Las pongo en ambos

**Comment by edithvilla** [comment]
@Nayita 

Monitoreo del estado de invasiones biológicas de plantas en México
http://www.unibio.unam.mx/invasoras/

Programa de Ordenamiento Ecológico Marino y Regional del Pacífico Norte
http://magrat.mine.nu:8080/Versatile/

Curso de Ordenamiento Ecológico
http://kinet.cuaed.unam.mx/educacion_continua/ordenamiento_ecologico/


estos son los que me acuerdo

**Comment by Nayita** [comment]
Ver comentarios en el issue 660.
Concluido
