### ISSUE TITLE
Rastrear ubicación de markdown de gráfica cajas y bigotes para SESMO #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#669]
La última versión usada en las presentaciones.

**Comment by Nayita** [comment]
@lancis-apc 
La ruta es la siguiente MEGADAPT/mega_procesamiento/graficas/vulnerabilidad_politica
El archivo se llama G_vulnerabilidad_ago.rmd

**Comment by lancis-apc** [comment]
@serranoycandela por si se necesita

**Comment by edithvilla** [comment]
@lancis-apc @Nayita @serranoycandela 

todo lo que se encontraba de graficas en:
MEGADAPT/mega_procesamiento/graficas
se movió a 
PUBLICACIONES/preparacion_articulo/sesmo_2018
