### ISSUE TITLE
Copiar y documentar hillshade para capas base DF #megadapt

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#673]
ubicación del archivo:  CARPETAS_TRABAJO/pgomez/hillshade_lowres

**Comment by edithvilla** [comment]
@serranoycandela @lancis-apc 

el hillshade ya está en la carpeta:

MEGADAPT/mega_sig/Relieve/hillshade_lowres

Paola, ya no está en tu carpeta

**Comment by edithvilla** [comment]
Ya está listo el readme
