### ISSUE TITLE
Reunión de organización y revisión de protocolos

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#681]

**Comment by ovisnigra** [comment]
## modificaciones al Protocolo de organización general
* Sobre las carpetas de trabajo:
  - No debe haber carpetas de trabajo por proyecto, en su lugar los responsables de sus carpetas sólo deben usar la carpeta general en la raíz del Dropbox ( `Dropbox (LNCS)/CARPETAS_TRABAJO` ).
  - Recomendar que el contenido de la capeta de trabajo esté ordenado por proyecto y producto.
  - Enfatizar el caracter temporal del contenido de estas carpetas y recalcar que cada responsable de su carpeta deberá mover los archivos de esta carpeta a las correspondientes carpetas de insumos en el directorio del proyecto o producto.
* Sobre la carpeta de publicaciones.
  - Voy a integrar contenido a esta carpeta y avisaré a Edith cuando lo haga.
* Sobre las solicitudes de diseño/correcciones
  - Para evitar confusión cambiaré el nombre de _correcciones_ por el de _modificaciones._
* Sobre los issues de Github
  - Evitar hacer issues demasiado particulares, o al menos evitar que sean estos donde se comparta información importante, para ello usar los issues más generales de los productos (o proyectos) y compartir la asignación de estos para colaborar adecuadamente.
* Sobre el protocolo de presentaciones
  - Especificar los criterios de creación de slides en la carpeta de procesamiento y de los slides finales en plataforma.
  - quitar la parte de las miniaturas.
***
de mi parte es lo que anoté que me compete.

**Comment by edithvilla** [comment]
yo agregaría
____________________

- Sobre las solicitudes de diseño/correcciones
El registro de las correcciones se llevará en el issue del GitHub

- Sobre la actualización del procedimiento de la organización general
Agregar cómo se deben de nombrar las carpetas de "PUBLICACIONES"
Agregar y/o corregir lo de las "CARPETAS_TRABAJO"
