### ISSUE TITLE
Buscar los shells de Pacífico Norte #PACIFICO

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#690]
Necesito buscar los shells de Marco

**Comment by edithvilla** [comment]
@AbrilKirikou 

En este momento la actividad la tengo en pausa porque tengo otras actividades que son prioritaria

**Comment by AbrilKirikou** [comment]
@edithvilla confirmo y quedo a la espera de la actualización de la tarea

**Comment by edithvilla** [comment]
@AbrilKirikou 

Ya copié los shell de pacífico norte:

PAPIIT/pap_insumos/integracion

voy a dejar todo el día de hoy sincronizando
