### ISSUE TITLE
Hacer el diagrama del procedimiento de activos de información #ORGANIZACION

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#694]

**Comment by edithvilla** [comment]
@Nayita 
ya tengo el diagrama de procedimiento de activos de información:
procedimiento_activos_informacion.html
procedimiento_activos_informacion.md
procedimiento_activos_informacion.png

los coloqué en:
ORGANIZACION_APC/apc_iso/procedimientos

**Comment by edithvilla** [comment]
@lancis-apc 

aquí se encuentra el html para revisar el procedimiento

ORGANIZACION_APC/apc_iso/procedimientos/procedimiento_activos_informacion.html

**Comment by Nayita** [comment]
@edithvilla 
Agregar Equipo técnico a los que entregan información
Unificar tiempos verbales
Agregar en "Mandar o llenar el formato conforme al protocolo tal...."
Corregir errores de escritura
Agregar en el rombo de verificación conforme a protocolo y quitar "cumple con protocolo"

**Comment by edithvilla** [comment]
ya está el diagrama en 

ORGANIZACION_APC/apc_iso/procedimientos/procedimiento_gestion_activ_inf
