### ISSUE TITLE
Preparar insumos para taller de sacmex #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#701]
@Nayita @bibianamonsivais @lancis-apc @serranoycandela 

Organización de logística
      Solicitud de grabadoras (Bibiana)
      Prepara listas de asistencias (Nadia)
      Lista de información requerida para sacmex (Edith)
      Excel: Funciones de Valor (Fidel)     

la ruta de la carpeta para el taller:

MEGADAPT/mega_talleres/sacmex_mar2018

**Comment by edithvilla** [comment]
Imprimir la tabla de la matriz límite

DF101215_GOV_AP modificado PNAS.limit

**Comment by Nayita** [comment]
Actividad concluida

**Comment by edithvilla** [comment]
@yosunemiquela 

el archivo de excel con la información de las capas está en:

megadapt/mega_talleres/sacmex_mar2018/insumos/evilla/mega_layers_sacmex_2018.xlsx
