### ISSUE TITLE
Generar aviso de privacidad para LANCIS #organizacion_apc

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#703]
1. Poner ubicación de donde quedará este documento.
2. esta es la leyenda que sugiero se incluya en la hoja de asistencia

La información proporcionada en esta reunión/taller será rigurosamente resguardada bajo el protocolo de protección de datos personales de LANCIS. Con la firma de esta hoja de asistencia, autorizo a que se grabe y tomen fotografías que podrán ser utilizadas únicamente para los fines de investigación del proyecto y que se detallan en el aviso de privacidad que se adjunta a este formato.

**Comment by Nayita** [comment]
@lancis-apc 
El documento modificado para este taller está en https://www.dropbox.com/home/megadapt/mega_talleres/sacmex_mar2018/logistica y
https://www.dropbox.com/home/ORGANIZACION_APC/apc_plantillas/plantilla_aviso_privacidad
El machote enviado por Bertha está en 
https://www.dropbox.com/home/ORGANIZACION_APC/apc_plantillas/plantilla_aviso_privacidad
 
Es necesario que se elabore un aviso de privacidad general para LANCIS ;)

Saludos
