### ISSUE TITLE
Crear archivo para documentar las fv del taller de sacmex #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#714]
@Nayita 

Cree un archivo para ir documentando las funciones de valor

MEGADAPT\mega_talleres\sacmex_mar2018\insumos\evilla\fv_compendio_sacmex_21mar2018.xlsx

solo es para ir registrando los valores que entran a las gráficas de función de valor, es muy útil.
mañana lo revisamos

**Comment by Nayita** [comment]
concluido. Subido a la misma ruta MEGADAPT\mega_talleres\sacmex_mar2018\insumos\evilla\fv_compendio_sacmex_21mar2018.xlsx

**Comment by edithvilla** [comment]
@Nayita 
por favor podrías asegurar y unificar los nombres de la columna I del excel con los archivos que guardo Fidel en: MEGADAPT\mega_talleres\sacmex_mar2018\jsons

gracias

**Comment by Nayita** [comment]
@edithvilla 
Hecho....ahora si lo cerramos
