### ISSUE TITLE
Dar acceso a la carpeta de zofemat #PAPIIT

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#720]
@AbrilKirikou @lancis-apc @Nayita 
 
Abril, tu vas a hacer la encargada de los activos de información de papiit?, lo pregunto porque necesito indicaciones de dónde colocar la carpeta de zofemat en el dropbox.

La carpeta de zofemat ya no está en el dropbox porque ya no es un proyecto activo (lo tenemos en disco duro externo).

Solo como recordatorio, es necesario que tomes la capacitación del uso del dropbox para poder tener acceso a él.

**Comment by edithvilla** [comment]
Contestación de Abril
No, hasta donde sé no voy a ser la encargada de activos de información de PAPIIT. 

La razón por la que te solicité el acceso es porque en el último correo sobre el tema me dijiste que la carpeta iba a seguir en el dropbox y lo único que quería era que me invitaras a esa carpeta para que pudiera tener acceso a los materiales del taller. Ahora, yo desconozco los protocolos que tienen para el manejo del dropbox y si tengo que tomar la capacitación entonces eso tendrá que esperar para cuando vuelva. 

Le marco copia de esto a Daniela, porque ella me pidió un informe del modelo original del taller y sin los insumos que hay en ese respaldo yo no puedo avanzar mucho en ello. 

Les pido por favor que me indiquen qué se puede hacer al respecto para avanzar.

**Comment by lancis-apc** [comment]
Edith: pon la última carpeta (de las cinco copias de respaldos que tenemos) en PAPIIT/papiit_insumos/zofemat   para seguir protocolo   e invita a la cuenta de dropbox de Abril.

**Comment by edithvilla** [comment]
@13Emilio 

voy a colocar la carpeta de zofemat en 

PAPIIT/papiit_insumos

por lo tanto voy a crear la carpeta de "papiit_insumos"

tenemos dos respaldo de zofemat

1. con fechas de 2015 -2016 y pesa 157 Gb
2. con fechas de 2014 y pesa 228 Gb.

¿cuál de los dos crees necesitar?

**Comment by AbrilKirikou** [comment]
@edithvilla 

Necesito verlos, podemos agendar un skype y me compartes la pantalla para verlos? Mi usuario de skype es: abril.kirikou. 

Muchas gracias,

Abril

**Comment by edithvilla** [comment]
@AbrilKirikou 

estoy colocando las siguientes carpetas en "papiit_insumos":

> - > 2013_antecedentes
>     
> - > respaldo_2015

Estas dos carpetas corresponden a los dos respaldos que tenemos.
No subí carpetas que contenían información geográfica, solo subí donde las que correspondían a informes o presentaciones y otros archivos.

**Comment by AbrilKirikou** [comment]
@edithvilla 

Me podrían compartir la carpeta de dropbox a la dirección acidsali@asu.edu?

Con respecto a los insumos, lo que necesito tener acceso es a los modelos de superdecisions, tablas e informes.

**Comment by edithvilla** [comment]
@AbrilKirikou 

Por cuestiones de tiempo no puedo subir TODO el respaldo de zofemat.

Ya te mandé la invitación al correo que me dices

**Comment by AbrilKirikou** [comment]
@edithvilla 

Los modelos en superdecisions son lo más importante que requiero. Sin ellos no puedo avanzar en el informe.

**Comment by edithvilla** [comment]
@AbrilKirikou 
acabo de sincronizar la carpeta "sgsd_pacifico_norte" 

por el momento es lo único que te puedo sincronizar, si necesitaras algo más sería hasta el 2 de abril

**Comment by AbrilKirikou** [comment]
@edithvilla 

Confirmo de recibido y te vuelvo a contactar el 2 de abril. Que tengas buenas vacaciones.

**Comment by AbrilKirikou** [comment]
@edithvilla 
No necesito a acceso a otras carpetas. Las que ya compartiste se van a mantener en la carpeta de insumos, cierto?

**Comment by edithvilla** [comment]
zofemat se encuentra en:
PAPIIT/pap_insumos/integracion/zofemat

si se necesita subir más información referente a zofemar se reabrirá el issue
