### ISSUE TITLE
Preparar presentación FOMIX-Yucatán 6 ABRIL #lancis

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#722]
Edith y Nadia: Iniciar protocolo para presentación

Daniela:¿Podrías notificar por este medio en cuanto sepas la hora y asistentes a la reunión?

**Comment by edithvilla** [comment]
@lancis-apc @dpedroza74 

Necesito mayor información de la reunión
¿De qué trata la reunión?
¿qué tienen planeado presentar?
¿en qué sala del anfiteatro?
¿a qué proyecto pertenece?

lo pregunto para ver que tipo de presentación vamos a tener y así poder prepara la carpeta de la presentación en el dropbox.

**Comment by dpedroza74** [comment]
Como parte del inicio del espejo LANCIS-Mérida el año pasado, en una reunión en agosto Luis hizo una presentación al Gobierno del Estado de Yucatán sobre lo que se hace en LANCIS para buscar opciones de colaboración. Ahí se acordó que podríamos concursar por recursos en una convocatoria de CONACYT y el Gobierno del Estado que se llama "FOMIX". A esta reunión viene gente del Gobierno del Estado (Secretaría de Investigación, Innovación y Educación Superior  y Secretaría de Desarrollo Urbano y Medio Ambiente) y de CONACYT Regional Sureste para conocer las instalaciones y capacidades del LANCIS y acordar cómo va a quedar la demanda de FOMIX. Será en la sala de inmersión. Se va a presentar una general de lo que hacemos en LANCIS (estamos trabajando en ella) y otra sobre la propuesta del FOMIX.

**Comment by edithvilla** [comment]
Ya está creada la carpeta para la presentación:

PRESENTACIONES/pr_lancis/pr_lancis_fomix_06abr2018

tiene la estructura básica de carpetas, por favor avisen por este medio cuando coloquen información

**Comment by lancis-apc** [comment]
la reunión es a las 11 am

**Comment by Nayita** [comment]
@dpedroza74 
Como quedamos dejé las nuevas slides en PRESENTACIONES\pr_lancis\pr_lancis_fomix_06abr2018\procesamiento\slides, la carpeta se llama pr_lancis_fomix_06 abr2018_cambios_1
Revisa las correcciones. Espero que estén bien y que te gusten. Cualquier cambio lo hago mañana sin problema.
Notifica por aquí dónde me dejas el nuevo guión. Gracias ;)
Saludos

**Comment by edithvilla** [comment]
@dpedroza74 @Nayita 

La lista de asistencia scaneada se encuentra:

PRESENTACIONES/pr_lancis/pr_lancis_fomix_06abr2018/logistica/asistencia_lancis_fomix_06abr2018

**Comment by edithvilla** [comment]
@Nayita 

Esta respaldado el audio  de la reunión en:

PRESENTACIONES/pr_lancis/pr_lancis_fomix_06abr2018/logistica/audio_fomix_06abr2018

**Comment by edithvilla** [comment]
@Nayita 

La minuta no está lista

**Comment by Nayita** [comment]
@dpedroza74 @edithvilla 
Ya generé la presentación completa en pdf y power point en la carpeta. La ruta es la siguiente: PRESENTACIONES\pr_lancis\pr_lancis_fomix_06abr2018

**Comment by Nayita** [comment]
Concluido
