### ISSUE TITLE
Pedir metadatos de la capa de Unidades Económicas #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#724]
@aleestrada 

Ale, me parece que tenemos pendiente la información de los metadatos de la capa de unidades económicas.

Me podrías proporcionar  la capa con sus metadatos?

gracias

**Comment by aleestrada** [comment]
Tanto la capa, como los metadatos se encuentran en:

presentaciones/pr_megadapt/pr_megadapt_sacmex_20feb2018/insumos/aestrada

Quedo pendiente de la revisión.

**Comment by edithvilla** [comment]
@aleestrada 

Revisé la información y encontré:

- El número de columnas que colocaste en el archivo de los metadatos (5) no corresponde al número en la tabla de atributos del shape

- Tampoco coincide la tabla con la descripción de las columnas en el archivo de los metadatos con la de la tabla de atributos del shape

**Comment by edithvilla** [comment]
@aleestrada 

Alejandra, confirmo de recibido: archivo de metadatos y la capa de unidades económicas por AGEB de la CdMx

**Comment by edithvilla** [comment]
@vichdzgeo 

Alejandra Estrada entregó la capa de unidades económicas por AGEB de la CdMx, el insumo está

MEGADAPT\mega_insumos\abril2018\AEstrada
