### ISSUE TITLE
Verificación de carpetas en respaldo #organizacion_apc

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#739]
1. Zafiro

Tengo tres de:
2.Tesina-AlbertoReyes
3. TesinaAlberto
4. Alberto_Tesina_Informe_final

todas están respaldadas?

5.  Materiales Maestría LNCS  (tiene cosas del desarrollo del posgrado)

**Comment by lancis-apc** [comment]
6. PropuestasLANCIS
que incluye Propuestas CONANP, PropuestasINE y Propuestas SEMARNAT

**Comment by lancis-apc** [comment]
5. entonces ese no lo borro hasta verificar.

**Comment by Nayita** [comment]
@lancis-apc 
Carpeta respaldada. Archivos incluidos en dropbox conforme a protocolo.
Puedes borrar la carpeta ;)
