### ISSUE TITLE
Hacer limpieza de la carpeta MIAs #OIPA

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#740]
Cuando un integrante del servicio social termina, hay que desvincularlo inmediatamente.

**Comment by Nayita** [comment]
@lancis-apc 
OK. Ya quité a las últimas personas que estaban en compartir y ya ordené la carpeta, ahora se llama SS_OIPA en lugar de MIAs y ya quedó todo ordenado por años. Sólo dejé la carpeta de Emilio y de Andrea por contener archivos con los que se está trabajando actualmente.
