### ISSUE TITLE
Organizar seminarios #ORGANIZACION

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#757]
La ubicación de los archivos necesarios para los seminarios se encuentran en:

CAPACITACION/cursos_no_formales/seminarios_apc

**Comment by edithvilla** [comment]
@Nayita 

- agregué la carpeta:  "fv_capacitacion_16abr2018"   para el seminario de capacitación en funciones de valor en la carpeta CAPACITACION/cursos_no_formales/seminarios_apc

**Comment by edithvilla** [comment]
### SEMINARIO PROGRAMADOS

- Lunes 9 de abril, 12:00 pm, Sistema de Gestión de Calidad

- Miércoles 11 de abril, 12:00 - 14:00 pm, Capacitación en DropBox y GitHub

- Lunes 16 de abril, 12:30 pm, Capacitación en funciones de valor

**Comment by edithvilla** [comment]
@lancis-apc @vichdzgeo @Nayita @bibianamonsivais @aleestrada @serranoycandela @yosunemiquela @rociobrito @dpedroza74 @13Emilio @AbrilKirikou 

### SEMINARIOS PROGRAMADOS

- Lunes 9 de abril, 12:00 pm, Sistema de Gestión de Calidad

- Miércoles 11 de abril, 12:00 - 14:00 pm, Capacitación en DropBox y GitHub

- Lunes 16 de abril, 12:30 pm, Capacitación en funciones de valor

**Comment by edithvilla** [comment]
## SEMINARIOS DE ORGANIZACIÓN
Serán los primeros lunes de cada mes, y es indispensable que estemos todos los colaboradores del APC-LANCIS.
El objetivo de estos seminario es el revisar las actividades, prioridades y pendientes de todo el equipo.
- 30 de abril
- 4 de junio
- 31 de julio

**Comment by edithvilla** [comment]
@paola-gp  @vichdzgeo @Nayita @iaga  @aleestrada @serranoycandela @yosunemiquela @rociobrito @dpedroza74 @13Emilio @AbrilKirikou

Seminario programado para el día lunes 13 de agosto a las 12:30
**"Presentación del protocolo de manejo de información geográfica"**

**Comment by edithvilla** [comment]
Seminarios de septiembre, 2018

lunes 17 de septiembre: Capacitación en modelación multicriterio primera parte

lunes 24 de septiembre: Capacitación en modelación multicriterio segunda parte

Es importante traer computadoras ya con el programa instalado Super Decisions (http://www.superdecisions.com/downloads/) y con el número serial instalado para que pueda usarse el programa.

**Comment by Nayita** [comment]
listo! gracias

**Comment by vichdzgeo** [comment]
@yosunemiquela

**Comment by edithvilla** [comment]
@paola-gp, @Nayita, @vichdzgeo 
Seminario para el mes de enero, propuesta para el lunes 14 o 21 de enero de 2019.

### Revisar los procedimientos y protocolos como parte del Sistema de Gestión de Calidad

**Procedimientos de:**
organización general
verificación de productos

**Protocolos de:**
organización de activos de información
manejo de la información geográfica
generación de gráficas y mapas con salida en HTML
logística para reuniones y/o talleres externos
recepción y entrega de activos de información
manejo de bases de datos

**Comment by edithvilla** [comment]
Se acordó con Paola comenzar el día lunes 14 de enero y 28 de enero la revisión de los procedimientos y protocolos

**Comment by edithvilla** [comment]
@paola-gp @vichdzgeo @Nayita @iaga @aleestrada @serranoycandela @yosunemiquela @rociobrito @dpedroza74 @JosueMA @AlfMedina 

Programación de seminario para el mes de enero de 2019.

Lunes 14 de enero a las 12 pm. **Introducción al uso de python en QGIS**.  Para este seminario se necesita que asistan con su computadora e instalado QGIS versión 2.18.

Martes 15 de enero a las 12 pm **Revisar los procedimientos y protocolos como parte del Sistema de Gestión de Calidad**
Procedimientos de:
- organización general
- verificación de productos

Protocolos de:
- organización de activos de información
- manejo de la información geográfica
- generación de gráficas y mapas con salida en HTML
- logística para reuniones y/o talleres externos
- recepción y entrega de activos de información
- manejo de bases de datos

**Comment by edithvilla** [comment]
@paola-gp ya está creada la carpeta para el seminario del día martes 29 de enero, 2019

ruta: /CAPACITACION/cursos_no_formales/seminarios_apc/superdecisions_fv_29ene2019

**Comment by edithvilla** [comment]
Se cierra este issue hasta nuevo aviso
