### ISSUE TITLE
extraer del audio del taller de funciones de valor con sacmex cuales fueron las funciones aceptadas para las que hay mas de una versión

### ISSUE THREAD

**Issue by serranoycandela** [lancis-apc/planeacion-colaborativa#758]
ejemplo: antiguedad_escasez y antiguedad_escasez_2

**Comment by Nayita** [comment]
@serranoycandela 

antiguedad_escasez_2

calidad_agua_sodio_escasez   (1)

Son las fv aceptadas de acuerdo al audio

**Comment by Nayita** [comment]
Cerrado

**Comment by serranoycandela** [comment]
hay que hacer una carpeta que contenga solo los jsons aceptados @Nayita @edithvilla

**Comment by edithvilla** [comment]
@serranoycandela los jsons finales de las funciones de valor se encuentran en:
\MEGADAPT\mega_procesamiento\input_modelos\modelo_gentes\fv_sacmex

son 7 funciones de valor finales:

fv_antiguedad_drenaje
fv_antiguedad_escasez_2
fv_calidad_agua_sodio_escasez (1)
fv_falla_escasez
fv_horas_servicio_escasez
fv_presion_hidraulica_escasez
fv_subsidencia

**Comment by Nayita** [comment]
Concluido
