### ISSUE TITLE
Migrar carpeta de presentaciones de OIPA a carpeta personal Paola#OIPA

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#769]

**Comment by Nayita** [comment]
@lancis-apc 
En tu carpeta de trabajo existe la carpeta phd y ahí había dejado los documentos que originalmente estaban en la carpeta doctorado y que por indicaciones tuyas no migraron a la carpeta OIPA.
Pregunta:
En tu carpeta de trabajo pusiste una carpeta oipa que está vacía. Dónde pongo la carpeta de presentaciones? en oipa o phd?

**Comment by lancis-apc** [comment]
resuelto
