### ISSUE TITLE
Organizar documentación de los proyectos del apc #MEGADAPT

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#784]
Las actividades que tengo que hacer son:
- Verificar que todas las listas de asistencia estén escaneadas
- Organizar las listas de asistencia que se encuentran en formato análogo (en el cajón del archivero enorme que se encuentra en el Área del APC-LANCIS)
-Escanear las listas que hagan falta y respaldarlas en:
/Archivos_Socio_Institucional/Gestión y logística (Docs administrativos)

**Comment by lancis-apc** [comment]
Agregar documentos de convenios y acuerdos de colaboración.

**Comment by edithvilla** [comment]
Primera etapa de organización de la documentación de MEGADAPT (28jun2018)
Se hizo una revisión de los documentos que se encuentran en el cajón del archivero general del APC-LANCIS.

1. Definir qué hacer con los cuestionarios en blanco (están fechados)
2. Reconocimientos (están fechados)
3. Resúmenes del proyecto MEGADAPT
4. Protocolos de: reuniones, entrevistas, guión para entrevistas específicas, propuestas de cuestionarios para entrevistas

Se hizo un paquete de los cuestionarios de Grupos Focales. Hay más documentación de Grupos Focales que falta definir cómo organizarlo (información del reclutamiento, listas de asistencias)

**Comment by edithvilla** [comment]
Me queda pendiente escanear las listas de asistencia, invitaciones y solicitudes de información de los:
1. [ ] Talleres de Iztapalapa
2. [ ] Talleres de Xochimilco
3. [ ] Talleres de La Magdalena Contreras
4. [ ] Talleres de SACMEX

**Comment by edithvilla** [comment]
1. **Delegación La Magdalena Contreras**, se realizaron talleres a las comunidades de:
- El Ocotal    \MEGADAPT\mega_talleres\taller_lmc_ocotal_03mar2015.pdf
- El Rosal     \MEGADAPT\mega_talleres\taller_lmc_rosal_09mar2015.pdf
- La Magdalena Atlitic (este taller es el único que cuenta con carta de invitación al Presidente de la Comunidad)    \MEGADAPT\mega_talleres\taller_lmc_atlitic_11-12nov2014.pdf

> En estos archivos se encuentran escaneadas las listas de asistencia y en el caso de la Comunidad Magdalena Atlitic se encuentra también la carta invitación

**Comment by edithvilla** [comment]
2. Delegación Iztapalapa, se realizaron talleres solamente en la colonia Miravalle, este archivo contiene la lista de asistencia

 \MEGADAPT\mega_talleres\taller_miravalle_iztapa_15mar2015.pdf

se realizó un segundo taller de juego:

 \MEGADAPT\mega_talleres\taller_juego_miravalle_iztapalapa_03jun2017.pdf

**Comment by edithvilla** [comment]
3. Delegación Xochimilco, se realizaron talleres con los siguientes grupos:
- Grupo de manejo de Xochimilco         \MEGADAPT\mega_talleres\taller_xochi_grupotrabajo_05feb2015.pdf
- Pescadores         \MEGADAPT\mega_talleres\taller_xochi_pescadores_08jun2015.pdf
- San Gregorio       
      - Parajes           \MEGADAPT\mega_talleres\taller_xochi_sangregorio_parajes_09jun2015.pdf
                               \MEGADAPT\mega_talleres\taller_xochi_sangregorio_parajes_12jun2015.pdf
      - Zona cerril      \MEGADAPT\mega_talleres\taller_xochi_sangregorio_zonacerril_29jun2015.pdf

**Comment by edithvilla** [comment]
4. SACMEX, se realizaron talleres con el Sistema de Aguas de la Ciudad de México
- Taller: \MEGADAPT\mega_talleres\taller_sacmex_12oct2015.pdf
- Presentación de avances:  \MEGADAPT\mega_talleres\reunion_sacmex_20feb2018.pdf
- Taller funciones de valor: \MEGADAPT\mega_talleres\taller_sacmex_fv_21mar2018.pdf
- Cartas de petición de información a SACMEX     \MEGADAPT\mega_insumos\agosto2016\SACMEX\peticion_informacion.pdf

**Comment by edithvilla** [comment]
Listas de asistencia de los talleres/reunión JUEGOS que se hicieron en las Delegaciones La Magdalena Contreras, Iztapalapa y Xochimilco

se realizó un segundo taller de juego:

 \MEGADAPT\mega_talleres\taller_juego_2017.pdf

**Comment by edithvilla** [comment]
TODA LA DOCUMENTACIÓN QUEDÓ RESGUARDADA EN SOBRES Y SE ENCUENTRA POR EL MOMENTO EN EL CAJÓN DEL ARCHIVERO DEL ÁREA DE PLANEACIÓN COLABORATIVA

**Comment by edithvilla** [comment]
Se hizo limpieza en el archivero del APC, se procedió a 
1. doblar hojas de rotafolio de los talleres de megadapt para guardarlos en una caja
2. las hojas de rotafolio del proyecto de zofemat (2012) de los resultados de los talleres, se eliminaron
3. las hojas de rotafolio del proyecto de cuenca del valle de méxico (2012) de los resultados de los talleres, se eliminaron

**Comment by edithvilla** [comment]
ya está terminada la tarea
