### ISSUE TITLE
Gestionar activos de información relacionados con el informe de IAI#IAI

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#788]
IAI/iai_procesamiento
IAI/iai_informes
Actualizar el readme respecto al informe de febrero de 2017...moverlo a procesamiento y decir porqué no se entrego.
REvisar documentos a entregar para este informe 
Aprender cómo se hace el índice y actualizarlo

**Comment by Nayita** [comment]
Todo lo referente al informe se está colocando en la siguiente ruta IAI/iai_procesamiento/integracion_informe_iai_abril2018

**Comment by Nayita** [comment]
Se revisaron todas las figuras de las siguientes rutas DISENO/figuras_lancis y DISENO/Megadapt%20IAI y las de las presentaciones. Se detectaron figuras en las presentaciones de Luis que no se tienen las originales. Se pedirá a Luis nos informe su origen

**Comment by Nayita** [comment]
@EsmeraldaOsejo 
Por indicaciones de Paola te comento que cualquier duda o ayuda que necesites para la gestión de los activos de información que se estén generando del informe, cuentes conmigo. Importante no olvidar los protocolos que ya conoces para esta actividad.

**Comment by EsmeraldaOsejo** [comment]
Vale. Muchas gracias, @Nayita

**Comment by Nayita** [comment]
Terminado y en espera de alguna novedad del informe donde necesiten de mi colaboración

**Comment by Nayita** [comment]
#840 

En este issue se hace referencia de que Esmeralda se hace cargo de la página y del manejo y revisión del contenido del informe

**Comment by Nayita** [comment]
Entrega de activos de información del informe final de IAI

Actividades a realizar para la entrega:

- [ ] Leer los protocolos

- [ ] Hacer quiz

- [ ] Colocar en la carpeta asignada los insumos generados que alimentaron la página web. Ruta: C:\Dropbox (LANCIS)\IAI\iai_procesamiento\integracion_informe_iai_abril2018

- [ ] Entregar permisos, si es necesario 

- [ ] Explicar funcionamiento de la página web 

- [ ] Hacer entrega de la información al coordinador o a la persona asignada por el coordinador

**Comment by EsmeraldaOsejo** [comment]
@Nayita, este issue ya había quedado terminado el 7 de diciembre de 2018, como tú misma lo pusiste.
La coordinadora de este informe soy yo desde hace varios meses, y lo reviso directamente con Luis, de modo que a él le entregaré toda la información, así como a Edith para que todo quede según protocolos en Dropbox. Las actividades relacionadas con el Dropbox quedarán concluidas en el transcurso de este mes.
Pronto abriré un issue según protocolo en el que pondré todo esto.
Gracias.

**Comment by Nayita** [comment]
@EsmeraldaOsejo  sólo una aclaración, yo soy la responsable de los activos de información de la carpeta de IAI por instrucciones de Paola, por lo tanto, me tendrás que entregar a mí. Edith es la encargada de dar acceso al Dropbox únicamente.

**Comment by paola-gp** [comment]
@EsmeraldaOsejo: con base en protocolo no se abren nuevos issues si existe uno

**Comment by EsmeraldaOsejo** [comment]
Ya se encuentran en su lugar correspondiente los archivos del informe. Solamente queda pendiente que me entreguen unas figuras para integrarlas. El informe final en PDF estará listo en cuanto me entreguen esas figuras.
A la página se accede a través de wordpress.com, el correo es lancis_apc@iecologia.unam.mx y la contraseña es "laincondicional".
La página reproduce con exactitud el contenido del informe, de modo que no se puede modificar una sin modificar el otro, y viceversa.

**Comment by Nayita** [comment]
Lo que se mostraba queda en el archivo especial para ese fin.
