### ISSUE TITLE
Realizar prueba de issues de GitHub pa todos #Organizacion

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#789]
- 1. Formato A: /
2. Formato B: /

 /ORGANIZACION_APC/prueba/test
Entregable: /ORGANIZACION_APC/prueba/entrega

Tareas
Ecjljklf
djdlsfjksljfd
fjalsdjflksjd
jdflasjdflajs
lkjdlfakjs
cacacacaca
@aleestrada @bibianamonsivais @dpedroza74 @Nayita @rociobrito @13Emilio @vichdzgeo @yosunemiquela @edithvilla @AbrilKirikou

**Comment by AbrilKirikou** [comment]
@lancis-apc ¿cómo se puede especificar el responsable o coordinador de la tarea?

**Comment by rociobrito** [comment]
Quiero un café @aleestrada

**Comment by yosunemiquela** [comment]
1. Actualizar información @rociobrito 

2. Hacer gráficas @rociobrito

**Comment by lancis-apc** [comment]
@AbrilKirikou: los assignees son los responsables

**Comment by bibianamonsivais** [comment]
@Nayita, añadí un README al la carpeta:
/IAI/insumos/informeblabla

**Comment by Nayita** [comment]
@edithvilla 

Dónde está el archivo guardado?

**Comment by edithvilla** [comment]
@dpedroza74 

La actividad cacacaca ya está lista en:
CAPACITACION/cursos_no_formales/seminarios_apc

**Comment by vichdzgeo** [comment]
Generar los metadatos

**Comment by aleestrada** [comment]
La tarea está en proceso.
En espera que issue #788 sea concluido

**Comment by rociobrito** [comment]
Hola Paola @lancis-apc

**Comment by rociobrito** [comment]
Ey ey ey

**Comment by bibianamonsivais** [comment]
@aleestrada a ver que pasa

**Comment by dpedroza74** [comment]
yoyo

**Comment by vichdzgeo** [comment]
010101

**Comment by rociobrito** [comment]
LOL

**Comment by AbrilKirikou** [comment]
¿podrían cambiar el assignee? para hacer la prueba?

**Comment by lancis-apc** [comment]
Listo! se cierra issue
