### ISSUE TITLE
Crear carpeta del artículo de salud #MEGADAPT

### ISSUE THREAD

**Issue by aleestrada** [lancis-apc/planeacion-colaborativa#791]
ruta: PUBLICACIONES/preparacion_articulo

El artículo es para la revista Environmental Research Letters y se envió a mediados del año pasado (2017)

**Comment by edithvilla** [comment]
@aleestrada 

Ya está lista la carpeta en:
PUBLICACIONES/preparacion_articulo/erl_2017
ahí puedes colocar tus carpetas
