### ISSUE TITLE
Coadyuvar en la elaboración del protocolo de R#organización-apc

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#804]
El documento final estará en ORGANIZACION_APC/apc_iso/protocolos y en la página web de APC de GitHub

**Comment by lancis-apc** [comment]
Revisar: https://www.iso.org/ics/35.080/x/

**Comment by Nayita** [comment]
Yosune ha revisado el link que envió Paola con los iso para nomenclatura de códigos. Decidir cual le va a servir para obtenerlo.
El jueves 19 de abril se canceló la reunión para iniciar el protocolo

**Comment by Nayita** [comment]
Se convoca a una nueva reunión para el 4 de mayo. En espera de confirmación

**Comment by Nayita** [comment]
Producto de la reunión se hizo el repositorio y el README para generar el protocolo. Con base al README cada integrante comenzará a describir cada uno de los títulos.

**Comment by Nayita** [comment]
@rgarcia-herrera @aleestrada @serranoycandela @yosunemiquela 
Es importante que incluyan dentro de sus actividades la escritura el protocolo de scripts. Han pasado dos semanas y no se ha desarrollado ningún titulo de acuerdo a la revisión que hicimos con Yosune en esta semana
Gracias por su atención

**Comment by Nayita** [comment]
@rgarcia-herrera @serranoycandela @aleestrada @yosunemiquela 
Informen los avances del protocolo. Se que Yosune ha trabajado en el protocolo pero registrenlo en el issue. Gracias

**Comment by yosunemiquela** [comment]
ya le metí más al protocolo.
Hay que complementando..
@Nayita @rgarcia-herrera @serranoycandela @aleestrada

**Comment by Nayita** [comment]
Rodrigo trabajó en el protocolo esta semana. En espera de que se logre concluir.

**Comment by edithvilla** [comment]
Cadena de custodia para agregar a los códigos

### Título

- Creador

- Fechas de creación

- Proyecto: 

- Lenguaje y versión:

- Código:

**Comment by Nayita** [comment]
@paola-gp @edithvilla 
Les envío la liga al protocolo https://github.com/sostenibilidad-unam/protocolos/blob/master/protocolo_software.md

**Comment by Nayita** [comment]
Minuta de la reunión del día 26 de junio de 2018
El protocolo ya se puede utilizar como está.
Acuerdo se comenzará haciendo un registro de los códigos que se tienen por persona. Edith les mandará la propuesta para el registro de la información.
REgresando de vaciones se hará un programa de trabajo de entrega de este registro.

**Comment by Nayita** [comment]
Se le solicitó a Fidel y Alejandra que revisaran y retroalimentaran el protocolo.

**Comment by Nayita** [comment]
@yosunemiquela @aleestrada @rgarcia-herrera @serranoycandela 
De acuerdo a la reunión que tuviemos antes de salir de vacaciones y conformo a lo dicho en la reunión les informo que el protocolo ya está disponible en la página web interna de APC.
Les pido que cualquier actualización al protocolo me lo hagan saber para actualizarlo en la página.
Gracias

**Comment by Nayita** [comment]
Concluido
