### ISSUE TITLE
Dar acceso a plataforma SIGPLAN #Papiit

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#809]
Dar acceso a la gente de NAVIC a la plataforma de aptitud.

**Comment by edithvilla** [comment]
@lancis-apc 
Se puede acceder a la plataforma con la siguiente URL

192.168.1.191/ecologia/login

Seleccionar proyecto

Usuario y contraseña (operador1)

El manual de usuario se encuentra

SOFTWARE/sigplan/docs/manuales/OE Manual - Operador.doc

**Comment by edithvilla** [comment]
@lancis-apc 
el acceso a la plataforma de SIGPLAN es

pulque.mine.nu/ecologia/

La lista de usuario/roles se encuentra en:

/SOFTWARE/sigplan/Plataforma_aptitud_LEEME.txt

**Comment by lancis-apc** [comment]
ya está notificado NAVIC, solo quedan en espera de los instaladores viejos.

**Comment by lancis-apc** [comment]
dejar prendida la PC hasta nuevo aviso.

**Comment by lancis-apc** [comment]
Verificar si tenemos los instaladores de:
1. Sistema operativo Linux. Se asume el sistema operativo Ubuntu 11 
2. Sistema de Información Geográfica GRASS 6.4.1 
3. Base de datos MySQL 5.1.62 
4. Lenguaje e interprete Python 2.7 
5. Framework Django 1.3.1 
6. Servidor de aplicaciones web Apache 2.0

**Comment by edithvilla** [comment]
1. \SOFTWARE\sigplan\ubuntu_11.04_64bits

**Comment by edithvilla** [comment]
Ya verifiqué y lo único que tenemos es lo que se encuentra en:
\SOFTWARE\sigplan
