### ISSUE TITLE
Crear actividades e issues para atender pendientes de APC #Organizacion_APC

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#814]
Reunión agendada para lunes 23 de abril a las 10:00
Venir preparados con las actividades desglosadas, tiempos estimados para realizarlas y personas involucradas. Agregar temas si es necesario. 

Pendientes

MEGADAPT
**- Modelación dinámica de sistemas**

- [x] Wrf (se cancela) 
- [x] SLEUTH (crear issue @serranoycandela)
- [ ] Revisar con Sergio Flores el Análisis de Unidades Económicas
- [ ] Agua subterránea (@edithvilla dar seguimiento una vez terminado análisis de escurrimientos)
- [x] Análisis de escurrimientos (crea issue @yosunemiquela)
- [ ] Salud 
**- ABM**
- [x]  FV Sacmex (crea issue @serranoycandela)
- [x] Optimización
- [x] Nuevas capas de SACMEX (crean issues @edithvilla y @vichdzgeo) 
- [ ] Modelos mentales de residentes (@edithvilla recordar a Luis para primera semana de mayo)

OTROS

**Gestión de calidad**
- [ ] Repositorios de SIG
- [ ] Verificación de calidad de activos de información geográfica 
- [ ] Documentación de análisis espaciales
- [ ] Documentación de software y scripts
- [ ] Reglamentos de manejo de GITHUB y Dropbox
- [ ] Manual de creación de páginas web
- [ ] Gestión y repositorios de administración
- [ ] Manual de procesamiento de bases de datos

**Otros proyectos**
- [x] Informe IAI 
- [x] NAVIC
- [ ] Laboratorio binacional (@edithvilla pendiente hasta que Luis informe sobre su atención)
- [x] Papiit
- [ ] Consolidación LANCIS (pendiente de noticias de CONACYT @rociobrito)

- [ ] Invasoras (pendiente)
- [ ] FOMIX Yucatán (pendiente a que salga la demanda)
- [ ] Problemas nacionales (pendiente de resultados de CONACYT)

- [ ] Software de administración (pendiente de decisión @rociobrito)

**Comment by lancis-apc** [comment]
MEGADAPT

- [ ] Capa de tandeo por AGEB para alimentar el modelo (crear issue) @aleestrada 

- [ ] Función de grado de protesta (crear issue) @aleestrada

**Comment by paola-gp** [comment]
Se cierra issue se da cointinuidad en #855
