### ISSUE TITLE
Desarrollar protocolo de presentación de reportes técnicos #Organizacion_APC

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#821]
Ver los tres documentos en:  \pgpriego\gestion_calidad  para iniciar la discusión.

**Comment by Nayita** [comment]
@lancis-apc Una pregunta: los reportes técnicos se refieren a los que hablábamos ayer para reportarle a Luis o es para proyectos? ya hay un protocolo para informes que Sergio hizo hace mucho tiempo y que igual podríamos complementar.
Si es lo de reporte a Luis, se me ocurre más una plantilla que un protocolo...espero tus comentarios

**Comment by lancis-apc** [comment]
Esto es para que especialistas y nosotros mismos estandaricemos las entregas con un mínimo de calidad.

**Comment by Nayita** [comment]
Concluido

**Comment by Nayita** [comment]
El protocolo quedó en ORGANIZACION_APC/apc_iso/protocolos. El archivo se llama protocolo_report_tec_informes.md. También se encuentra en la página web de GitHub-lancis-apc
