### ISSUE TITLE
Georreferenciar los datos de encharcamientos críticos- sacmex #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#823]
ubicación: MEGADAPT/mega_insumos/abril2018/SACMEX/Puntos críticos de encharcamiento/Relación de ubicación de equipos de emergencia (40).xlsx y RESUMEN UBICACION DE 120 SITIOS.xls

**Comment by vichdzgeo** [comment]
Ubicación: MEGADAPT/mega_procesamiento/banco_datos/operativo_lluvias

Los datos georeferenciados ya se encuentran en formato shape para su uso.

Para el archivo Relación de ubicación de equipos de emergencia(40).xlsx corresponde el archivo: mega19tp12eqemer_v1.shp.
Para el archivo RESUMEN UBICACION 120 SITIOS.xls corresponde el archivo:
mega19tp12oplluv_v1.shp

**Comment by edithvilla** [comment]
Hecho
