### ISSUE TITLE
Procesar la base de datos de gastos-pozos - sacmex #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#824]
ubicación: MEGADAPT/mega_insumos  ?

**Comment by edithvilla** [comment]
\MEGADAPT\mega_insumos\agosto2016\SACMEX\SHAPES\INFRAESTRUCTURA HIDRAULICA DF_SACMEX_020915\ABASTECIMIENTO\POZOS.dbf

está la columna: INSTALACIÓN en el shape

y en la base de datos está la columna: NOMBRE

**Comment by edithvilla** [comment]
edith, revisar abreviaciones que vienen en la base de datos de gastos y buscar esa información en los planes hidráulicos

**Comment by edithvilla** [comment]
@vichdzgeo no hay documentación de las abreviaturas en los Planes Hidráulicos

**Comment by vichdzgeo** [comment]
Ruta: MEGADAPT/mega_procesamiento/banco_datos/gastos

los productos finales se encuentran en la ruta antes mencionada, se crearon archivos shape del 2010 al 2017
