### ISSUE TITLE
Procesar los datos de fugas y faltas - sacmex #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#825]
megadapt/mega_insumos/abril2018/SACMEX/FUGAS_FALTAS Y EFICIENCIA AÑOS 2017 Y 2018.xlsx

### Actividades
1. Separar por delegación para el año 2017 los datos de fugas y faltas
2. Obtener el número de reportes de los datos por delegación

### Insumos

Esta base de datos se obtuvo bajo el Oficio número: GCDMX-SEDEMA-SACMEX-DG-DEPP-DT-SPI-UDPMSH-1014116/2018
SISTEMA DE AGUAS DE LA CIUDAD DE MÉXICO
Dirección Ejecutiva de Programación y Proyectos
Dirección Técnica
Subdirección de Planeación de Inversión
Unidad Departamental de Planes Maestros de los Sistemas Hidráulicos

**Comment by edithvilla** [comment]
está listo el procesamiento, el archivo se ubica en:
\MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas\bd_fugas_faltas_procesadas.xlsx
es la hoja que se llama "resumen" y "gráficas"

**Comment by edithvilla** [comment]
Resumen
Número de reportes por Fugas
2017 - 25,298
2018 -  3,669
Colonias - 1,530
Total: 28,967

Número de reportes por Faltas
2017 - 61,179
2018 -  10,452
Colonias - 1,631
Total: 71,631

**Comment by edithvilla** [comment]
### Procesamiento de las bases de datos de Faltas y Fugas - SACMEX

- ubicación de los datos: MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas
Actividades:
1. [ ] Reunión de capacitación (lunes 14 de mayo) con Nadia y Victor
2. [ ] Bases de datos repartidas:
        Fugas 2017 y 2018 (bd_fugas2017,2018_frecuencias.csv)- Edith Villa
        Faltas 2017 (bd_faltas2017_frecuencias.csv - 1688 registros) - Víctor
        Faltas 2018 (bd_faltas2018_frecuencias.csv - 999 registros - Nadia
3. [ ] Procesamiento (coincidencias > al 86%)
4. [ ] Filtro de las coincidencias > al 86%
5. [ ] Uniones para obtener la base de datos del segundo procesamiento (coincidencias > a 60%)
6. [ ] Filtro de las coincidencias > al 60%

**Comment by Nayita** [comment]
Acuso de recibido. Para comenzar a trabajar le estoy programando 12 horas esta semana de arranque y ya la próxima le disminuyo a 10 horas

**Comment by edithvilla** [comment]
FUGAS 2017
Delegaciones:

1. [x] Álvaro Obregón
2. [x] Azcapotzalco
3. [x] Benito Juárez
4. [x] Coyoacán
5. [x] Cuajimalpa de Morelos
6. [x] Cuauhtémoc
7. [x] GAM
8. [x] Iztacalco
9. [x] Iztapalapa
10. [x] La Magdalena Contreras
11. [x] Miguel Hidalgo
12. [x] Milpa Alta
13. [x] Tláhuac
14. [x] Tlalpan
15. [x] Venustiano Carranza
16. [x] Xochimilco

890 REGISTROS  (bd_fugas2017_colonias_f1.csv) ARCHIVO LISTO PARA HACER EL JOIN

**Comment by edithvilla** [comment]
FUGAS 2018
Delegaciones:

1. [ ] Álvaro Obregón
2. [ ] Azcapotzalco
3. [ ] Benito Juárez
4. [ ] Coyoacán
5. [ ] Cuajimalpa de Morelos
6. [ ] Cuauhtémoc
7. [ ] GAM
8. [ ] Iztacalco
9. [ ] Iztapalapa
10. [ ] La Magdalena Contreras
11. [ ] Miguel Hidalgo
12. [ ] Milpa Alta
13. [ ] Tláhuac
14. [ ] Tlalpan
15. [ ] Venustiano Carranza
16. [ ] Xochimilco

**Comment by Nayita** [comment]
Se terminaron de procesar los dos filtros en el archivo de faltas 2018. Comienza la revisión manual de 121 registros

**Comment by Nayita** [comment]
Terminé revisión manual de todas las delegaciones. Tengo varios registros que no encontré ningún tipo de coincidencia

**Comment by edithvilla** [comment]
FUGAS 2018:
La base de datos que se hizo de manera manual es de 118 registro de los cuales falta por ubicar 37 registros (ubicar a nivel de calle para asignarle la colonia)
FUGAS 2017:
Estoy en el filtro 2

**Comment by Nayita** [comment]
Faltas 2018
Terminé estos Municipios de la revisión manual. Faltan 29 registros únicamente para terminar

1. [x] Álvaro Obregón
2. [x] Azcapotzalco
3. [x] Benito Juárez
4. [x] Coyoacán
5. [x] Cuajimalpa de Morelos
6. [x] Cuauhtémoc
7. [x] GAM
8. [x] Iztacalco

**Comment by edithvilla** [comment]
Reporte de Fugas 2017:
bd_fugas2017_frecuencias.csv (1569 registros)

Para el primer filtro se encontraron 890 registros
Para el segundo filtro se encontraron 310 registros
Para el filtro final se tiene 1365

No se pudieron encontrar 204

**Comment by edithvilla** [comment]
Reporte de Fugas 2018:
bd_fugas2018_frecuencias.csv (789 registros)

Para el primer filtro se encontraron  462 registros
Para el segundo filtro se encontraron  213 registros
Para el filtro final se tiene 713

No se pudieron encontrar 76

**Comment by edithvilla** [comment]
Esta es la organización de la carpeta:

\MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas\faltas
aquí se colocan las capas digitales de colonias y agebs para faltas 2017 y 2018

\MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas\fugas
aquí se colocan las capas digitales de colonias y agebs para fugas 2017 y 2018

\MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas\bd
aquí se colocan las bases de datos de los filtros (f1, f2 y f3)

**Comment by edithvilla** [comment]
Ya están las capas de fugas a nivel de colonias y agebs para los años 2017 y 2018, 
\MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas\fugas

así como también las bases de datos
\MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas\bd

**Comment by vichdzgeo** [comment]
*** Procesamiento de colonias a agebs ****
Para el proceso de re escalado de colonias a agebs se utiliza el script colonias2.agebs.py
Ruta del script: MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas

el código corre en Qgis 2.18

**** Modificaciones en código para su ejecución ***
folder = se establece la ruta de la carpeta que contiene los archivos shape
new_geom = ruta y nombre del archivo shape de agebs 
old_geom = ruta y nombre del archivo shape de colonias
old_geom_id= "COL_ID"
resamplingFields = ["_Frecuenci"]


*****Tiempo estimado de procesamiento******
 5 minutos.


*****Notas importantes******
Verificar que la capa de agebs solo tenga en sus atributos "id_ageb"

**Comment by Nayita** [comment]
Ya se terminó de procesar la suma de frecuencias de faltas 2018.
Los archivos ya están en la siguiente ruta indicada. Los archivos son: bd_faltas2018_colonias_86_1f, bd_faltas2018_colonias_2f y bd_faltas2018_colonias_1f2f3f

**Comment by Nayita** [comment]
Se inicia procesamiento de capas de colonias a agebs

**Comment by Nayita** [comment]
Ya están terminadas las capas de colonias y agebs de faltas 2018.
Los archivos están en la siguiente ruta: MEGADAPT/mega_procesamiento/banco_datos/fugas_faltas/faltas

**Comment by vichdzgeo** [comment]
**Aprendizajes en el proceso**

- Excel permite guardar en formato csv y codificación UTF8
- Para abrir un archivo CSV en Excel la manera correcta de hacerlo es abrir un documento nuevo > Datos > (subpestaña o panel) Obtener y trasformar datos > Desde texto /CSV   de esta manera se elige el archivo y la codificación correcta de los datos.
- Se realizo un script para la union de una tabla csv y un archivo shape

**Comment by edithvilla** [comment]
@aleestrada @yosunemiquela 
Ya están listas las capas de faltas y fugas para los años 2017 y 2018

ubicación: 
MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas\faltas\agebs_faltas2017.shp y agebs_faltas2018.shp

MEGADAPT\mega_procesamiento\banco_datos\fugas_faltas\fugas\agebs_fugas2017.shp y agebs_fugas2018.shp
