### ISSUE TITLE
Revisar formación del informe de IAI#IAI

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#840]
@EsmeraldaOsejo revisará y hará la corrección de estilo del documento de Luis (entrada_1) El archivo se encuentra en IAI/iai_procesamiento/integracion_informe_final. También revisará la redacción de Lecciones Aprendias del manuscrito que hizo Bibiana.
@bibianamonsivais integrará el documento ya corregido y se hará cargo de la corrección y formación de figuras y tablas. También hará una propuesta del orden en el que se incorporan los conceptos del documento de Luis en el informe.
@Nayita se hará cargo de la lectura final y del compendio de gráficas de las fichas e informes anteriores

**Comment by bibianamonsivais** [comment]
@Nayita ,

Ya hice las correcciones en las figuras de las Fichas de MEGADAPT que sugirió @EsmeraldaOsejo ayer.
Por el momento les tengo en la ruta: CARPETAS_TRABAJO/bmonsivais/iai/fi_fichas_megadapt_24Abr2018 , por si quieren revisarlas o moverlas a algún lugar en específico.

**Comment by Nayita** [comment]
@bibianamonsivais envíale a Luis la propuesta de índice para que lo revise. Ya está enterado y está en espera de recibirlo

**Comment by bibianamonsivais** [comment]
@Nayita , acabo de enviárselo.

**Comment by bibianamonsivais** [comment]
@Nayita , agregué unos comentarios al documento: (entrada_1), porque hay referencias bibliográficas que no pude rastrear. 

@luis-supremo , no todas están referenciadas con Mendeley. ¿Podrías confirmar que son correctas aquellas con comentarios? Gracias.
IAI/iai_procesamiento/integracion_informe_final

**Comment by Nayita** [comment]
@bibianamonsivais ya subí la relatoría de las presentaciones a IAI/iai_procesamiento/integracion_informe_final
para  que la revises. Gracias. Espero tus comentarios y correcciones

**Comment by Nayita** [comment]
@bibianamonsivais @EsmeraldaOsejo 
Puse en IAI/iai_procesamiento/integracion_informe_iai_abril2018 toda la información de presentaciones, productos de las presentaciones y la relatoría de las presentaciones para que se quede todo concentrado ahí.
Ya no utilicemos la carpeta integracion_informe_final para que Esmeralda pueda ver todo.

**Comment by EsmeraldaOsejo** [comment]
Ya subí los dos archivos a la carpeta IAI/iai_procesamiento/integracion_informe_iai_abril2018

**Comment by Nayita** [comment]
@luis-supremo toda la información que se está trabajando y generando del informe de IAI está en la siguiente ruta para que la puedas checar:
IAI/iai_procesamiento/integracion_informe_iai_abril2018

**Comment by EsmeraldaOsejo** [comment]
Ya subí la sección de Ciencias de la Sostenibilidad:
IAI/iai_procesamiento/integracion_informe_iai_abril2018/Ciencias de la sostenibilidad-EOB

**Comment by EsmeraldaOsejo** [comment]
@Nayita por cierto, no veo a Luis como participante, ¿sí puede ver las actualizaciones?

**Comment by EsmeraldaOsejo** [comment]
Ya subí la sección de Conocimiento ordinario y conocimiento científico. Faltan las referencias bibliográficas que marqué en amarillo. También hay otro comentario en amarillo, pero ese se puede ignorar, en todo caso.
IAI/iai_procesamiento/integracion_informe_iai_abril2018/entrada_1-Conocimiento ordinario y conocimiento científico-EOB

**Comment by Nayita** [comment]
@EsmeraldaOsejo Si recibe las notificaciones a su correo. Espero que las esté leyendo....

**Comment by Nayita** [comment]
@bibianamonsivais @EsmeraldaOsejo 
Ya subí las gráficas del informe anterior actualizadas a IAI/iai_procesamiento/integracion_informe_iai_abril2018/graficas
Revisaré el documento de lecciones aprendidas para ver si estas gráficas ilustran el texto

**Comment by bibianamonsivais** [comment]
Ya se integraron textos de las Fichas MEGADAPT al manuscrito del informe. Aún hay textos con los que tengo duda, y que mw gustaría verlos con @luis-supremo. Hay una relación de lo que se ha integrado de las Fichas en el archivo README-INTEGRACIÓN DE FICHAS MEGADAPT.

Falta integrar el bloque Involucramiento Ininterrumpido que está revisando @EsmeraldaOsejo.
Falta integrar las gráficas que me pasó @Nayita. Sugeriría que sea en alguna de las Lecciones Aprendidas, pero requiero retroalimentación para decidir en dónde.

**Comment by EsmeraldaOsejo** [comment]
Ya subí la última sección, Involucramiento ininterrumpido, y un documento con las ideas aisladas que falta integrar.
IAI/iai_procesamiento/integracion_informe_iai_abril2018/entrada_1-Involucramiento ininterrumpido-EOB
IAI/iai_procesamiento/integracion_informe_iai_abril2018/entrada_1-Ideas aisladas-EOB

No sabía si en Involucramiento ininterrumpido era necesario omitir la referencia directa al LANCIS (ya que entiendo que esta parte es sólo marco teórico). El hecho de que estuviera en negritas me hace pensar que sí. En todo caso, es muy fácil volver a hacer la referencia, de ser necesario.

También subí el documento completo con modificaciones, pero sugiero revisar solamente las secciones que están guardadas por separado, para evitar confusiones.
IAI/iai_procesamiento/integracion_informe_iai_abril2018/entrada_1-EOB

**Comment by bibianamonsivais** [comment]
@Nayita , @EsmeraldaOsejo ,

Aprovechando que Luis estará aquí la próximia semana, hicimos una cita para el jueves a las 15:00 para revisar el informe.

**Comment by Nayita** [comment]
@bibianamonsivais 
Perfecto Bibi, la reviso y la lleno con la información de las presentaciones.
Me doy por enterada de la reunión del próximo jueves. Entonces no escribiré nada de IAI en el boletín para el miércoles, en vista que los pendientes los veremos al día siguiente.

**Comment by bibianamonsivais** [comment]
@Nayita y @EsmeraldaOsejo ,

Les envié el link de un documento en Drive, en el que sugiero enlistar los pendientes que tenemos cada una sobre el informe, en orden prioritario. Puse algunos suyos respecto a lo que me acuerdo y extraje del audio, pero claro, cada una sabrá sus prioridades.
La idea con este documento de Dirve, es después vaciarlo en este issue.

El audio de la revisión (y de la pasada también), sugerí ubicarlo en la ruta:
IAI/iai_procesamiento/integracion_informe_iai_abril2018/revisiones_temporal

**Comment by EsmeraldaOsejo** [comment]
No puedo editar directamente el documento, pero mi parte queda así:

Esmeralda
Extraer textos de SESMO que puedan servir como ejemplos o definiciones generales para distintos apartados del informe IAI. Ya que estén listos se los paso a Bibiana para su integración.

Revisar la redacción de los fundamentos filosóficos con Luis. Una vez que estén listos también se los paso a Bibiana para su integración.

La unificación del estilo del informe se tiene que hacer conforme se integran los textos y se revisan los avances, pero la unificación final será cuando todo esté integrado y listo.

**Comment by Nayita** [comment]
@bibianamonsivais 
Ya integré mis actividades al documento de Drive

**Comment by EsmeraldaOsejo** [comment]
Ya terminé la extracción, traducción y redacción de información de SESMO.
@bibianamonsivais ya puedes tomar lo que consideres de utilidad para integrarlo al informe.
Está en IAI/iai_procesamiento/integracion_informe_iai_abril2018/Extractos de SESMO-EOB

**Comment by Nayita** [comment]
@EsmeraldaOsejo 
Puse el texto traducido en relación a las gráficas para tu revisión y correcciones. La liga es la siguiente: IAI/iai_procesamiento/integracion_informe_iai_abril2018/graficas
El archivo se llama traduc_texto_gr.
Gracias

**Comment by EsmeraldaOsejo** [comment]
Ya subí parte de los fundamentos filosóficos (racionalismo, empirismo y Nietzsche) de los conceptos "hecho" y "valor", para integrarlos al informe. Todavía faltan Kant y otros más... estoy esperando a que Luis me los pase. @bibianamonsivais y @Nayita estaría bien que opinaran sobre qué tan relevante y comprensible les parece esta parte y cómo proponen que se integre. Para hacerla más llevadera, propongo buscar ejemplos que relacionen a cada teoría filosófica mencionada con las ciencias de la sostenibilidad, sobre todo en las partes más extensas (Descartes y Hume).
Los documentos son:
IAI/iai_procesamiento/integracion_informe_iai_abril2018/Racionalismo contra el empirismo BIS-EOB-rec
y
IAI/iai_procesamiento/integracion_informe_iai_abril2018/Friedrich Nietzsche esmeralda-EOB
Lo que resalté en amarillo es parte de lo que considero que se podría quitar/recortar, de ser necesario, pero creo que hay que evaluarlo entre todos.

**Comment by EsmeraldaOsejo** [comment]
@Nayita ya estoy revisando tu traducción, la veo bien. La subo mañana temprano.

**Comment by Nayita** [comment]
Perfecto Esmeralda. Gracias. Reviso lo que nos pides.

**Comment by Nayita** [comment]
@bibianamonsivais @EsmeraldaOsejo 
Por indicaciones de Paola le estoy dando un poco de orden a la carpeta de integracion_informe_iai_abril2018. Por lo pronto, puse una nueva carpeta llamada documentos_1arevision en la que puse todos los documentos revisados por Esmeralda. Sólo ahora les pediría que sigan poniendo ahí los documentos que revisan de Luis antes de ser integrados al informe.
Si tienen cualquier comentario al respecto, avísenme. Gracias

**Comment by bibianamonsivais** [comment]
Pendientes del 31 de mayo al 3 de junio:

Bibiana:

- [ ] Corregir redacción del informe
Apartados:
      Características del proceso transdisciplinario
      Proyecto MEGADAPT
      Fases del proceso de investigación
      Retos principales
      Barreras y Lecciones Aprendidas
- [ ] Definir formato de recuadros informativos
- ...

**Comment by EsmeraldaOsejo** [comment]
@Nayita no entiendo, ¿entonces los seguimos subiendo a integracion_informe_iai_abril2018 o no?
Por lo pronto terminé la revisión del texto de las figuras y lo subí a la carpeta en la que tú lo habías puesto:
IAI/iai_procesamiento/integracion_informe_iai_abril2018/graficas/traduc_texto_gr-EOB

**Comment by EsmeraldaOsejo** [comment]
Nuevo pendiente (mío):

- [ ] Revisar la cohesión y redacción de los puntos 2.1 a 2.4 del informe, con base en la versión del 30 de mayo.

Haré mis comentarios al respecto en la reunión del lunes.

**Comment by EsmeraldaOsejo** [comment]
Listos los puntos 2.1 a 2.4.
Ahora voy a revisar del 2.5 al 2.7.3, en lo que @yosunemiquela ve la parte metodológica.
¿Cuándo les parece bien reunirnos de nuevo?

**Comment by Nayita** [comment]
@yosunemiquela @EsmeraldaOsejo 
Escribo una pequeña minuta de la reunión de ayer. Agreguen acuerdos que no se hayan descrito.

- Falta una introducción tanto en metodología como en la sección de "retos".
Yosune escribirá la introducción a la metodología.

- Falta la explicación de acoplamiento.

- Corrección de títulos de las columnas de las tablas.

- Relacionar fases del proyecto con métodos y resultados

- Quitar la muletilla "aclarar....."

- Buscar fotos de la presentación de SACMEX

**Comment by Nayita** [comment]
@yosunemiquela @EsmeraldaOsejo 
Comienzo con la revisión y correcciones de la sección 2.1 a 2.4. Revisaré la versión ya con correcciones de Esmeralda.
Yosune, si tienes correcciones puntuales de estas secciones mándamelas y las integro de una vez.

**Comment by EsmeraldaOsejo** [comment]
@Nayita, no he subido a ninguna carpeta el documento que tiene los cambios que hice del 2.1 al 2.4, de modo que no sé en qué documento vas a hacer qué correcciones. Cuando termine todos los puntos los voy a integrar y los voy a subir, no antes. Estoy cambiando la estructura y el orden de toda esa sección, con el visto bueno de Luis.
Tampoco quedamos en que hicieras ningún cambio o corrección sobre mi texto o el de Yosune. Eso nunca se dijo en la reunión con Luis. Por favor no mezclemos tareas. Si hay dudas con gusto nos reunimos de nuevo con Luis y las aclaramos.

**Comment by Nayita** [comment]
@EsmeraldaOsejo 
Lo aclaramos en la reunión con Luis.

**Comment by Nayita** [comment]
Minuta de la reunión

Acuerdos

El informe se hará en una página en GitHub

- Luis escribirá la introducción

- Esmeralda se encargará de la revisión y formación de la parte teórica. Ella entregará las secciones formadas para su cambio a formato md.

- Yosune escribirá la introducción a la metodología. 

- Nadia escribirá resultados junto con Yosune. Concluido el texto, Esmeralda revisará redacción. También pasará las secciones teóricas concluidas por Esmeralda a formato md.

@EsmeraldaOsejo @yosunemiquela 
Lean los acuerdos y si tienen algo que agregar modifiquen aquí directamente.

**Comment by Nayita** [comment]
Minuta de la reunión 06/jun/2018

Revisión de la sección 2.5 Conocimiento ordinario y conocimiento científico.
Se investigó lo de copyright en GitHub. Rodrigo informó que se está protegido por la ley. Sugiere agregar un apartado donde se diga como citar la información contenida en el informe de IAI.

**Comment by Nayita** [comment]
Minuta de la reunión 14/06/2018

Daniela enviará el artículo con el esquema de las "fases"
Luis desarrollará la sección de fases para poder conectar la metodología y los resultados.
Revisión del conocimiento ordinario y conocimiento científico, vulnerabilidad

**Comment by Nayita** [comment]
Minuta reunión 23/07/2018
Yosune y Nadia harán gráficas de resultados de acuerdo al texto de lecciones aprendidas con base en las etapas del proyecto.
Nadia hará base de datos de acuerdo al texto actual esperando la nueva clasificación de las etapas del proyecto.
En junio no se hicieron porque Yosune estaba trabajando de tiempo completo con el modelo de escacez.

**Comment by Nayita** [comment]
@yosunemiquela ya está la base datos para las gráficas en la siguiente ruta
IAI/iai_procesamiento/graficas. El archivo se llama fases_frecuencias. Chécalo y platicamos que procede.

**Comment by edithvilla** [comment]
En la carpeta IAI/iai_procesamiento/integracion_informe_iai_abril2018/figuras
agregué las figuras que se encuentran en el informe que se entregó en febrero de 2017:
* las figuras están en español
1. Diagrama general de megadapt
2. Modelos mentales
3. Rich picture
4. Objeto fronterizo
5. Overall representation
6. Integración de los modelos con dependencia

**Comment by Nayita** [comment]
@paola-gp 
Listado de activos de información con los que se cuentan para el informe. Los activos de información están en la siguiente liga:
IAI/iai_procesamiento/integracion_informe_iai_abril2018
Carpeta informe final: subcarpetas finales (información final de las fichas) y prefinales ( información de fichas en proceso)
man_iai_leccionesaprendidas_04jun2018.docx, archivo del documento hecho por Bibiana
Carpeta figuras: figuras solicitadas por Luis de las fichas tanto en inglés como en español
Carpeta gráficas: Gráficas actualizadas del último informe de Luis
Carpeta presentaciones: últimas presentaciones de MEGADAPT-IAI y sus respectivas reseñas y tabla

**Comment by Nayita** [comment]
Edith y Nadia están asignadas para elaborar los md de los archivos finales del informe.

**Comment by Nayita** [comment]
Minuta reunión 1 de julio de 2018

Se eligió la plantilla "Documentation Theme for Jekyll" tentativamente para iniciar con la elaboración de la página web, mientras se contrata a un experto para hacerla.

Se definió un índice general para hacer el readme y Luis enviará la información que tiene hasta el momento para ir alimentando el índice.

Luis comentó que el índice final quedará listo al término del informe.

@paola-gp para tu conocimiento

**Comment by Nayita** [comment]
Se creo una nueva carpeta donde estarán los markdowns de los archivos finales y prefinales en las siguiente ruta IAI/iai_procesamiento/integracion_informe_iai_abril2018/informe_final, llamada "md"

Ya se concluyeron los md de los archivos finales que compondrán el glosario.
Se inicia la elaboración de md de los archivos pre-finales.

**Comment by edithvilla** [comment]
Están corregidos los nombres de las figuras que se han ocupado en los informes y se encuentran:
/IAI/iai_procesamiento/integracion_informe_iai_abril2018/figuras
Se corrigió la figura de acuerdo a la reunión del día 1 de agosto: fi_overall_representation_mental_models_esp  
la figura se encuentra en la misma dirección

**Comment by EsmeraldaOsejo** [comment]
@edithvilla muchas gracias, sólo tengo algunos comentarios respecto a la traducción:
En la figura fi_megadapt_integracion_modelos_instituciones.png, hay que poner "instrumento fronterizo" en lugar de "objeto fronterizo", y "riesgo para la salud" en lugar de "riesgo a la salud". También me parece que hay que homogeneizar "biofísico-técnico" a la otra traducción que hay, que es "biofísico-infraestructural"... hay que corroborar esto último con Luis. Si está de acuerdo, también habría que hacer el cambio en la figura fi_modelo_general_megadapt.
En la figura fi_modelos_mentales hay que cambiar "Manifestaciones vulnerables en el paisaje" por "Manifestaciones de la vulnerabilidad del paisaje".

**Comment by EsmeraldaOsejo** [comment]
Sobre las nuevas carpetas y su contenido:
Por favor, recordar que hay que anotar todos los cambios en el README. Por instrucción de Luis, el 25 de julio hice la subcarpeta "informe final" con sus respectivas subcarpetas "finales" y pre-finales" y le hice su propio README, en el que se especifica que yo estoy encargada de todos los cambios y actualizaciones en dichas carpetas (ya que son los textos que voy editando). Sin embargo, se hicieron cambios el 01 de agosto y el 02 de agosto (hoy) sin hacer, hasta este momento, ninguna actualización a ninguno de los README. Uno de los cambios fue agregar la subcarpeta "md", que contiene documentos en markdown y figuras.
Yo sugeriría mover dicha subcarpeta, "md", a la raíz del informe (/IAI/iai_procesamiento/integracion_informe_iai_abril2018) y mover las figuras que están dentro a la subcarpeta "figuras".
Por favor mantengamos actualizado el README (inmediatamente después de hacer los cambios), porque de lo contrario no se puede llevar un control adecuado. 
Dentro del README están los apartados "fecha de última actualización" y "detalles de última actualización". También actualicé el README que está en IAI/iai_procesamiento/integracion_informe_iai_abril2018, que no se había actualizado desde que Bibiana se fue.

**Comment by EsmeraldaOsejo** [comment]
Acabo de actualizar yo el README de "informe_final" con esta información, para agilizar el proceso. Sólo falta que se agreguen los detalles de las actualizaciones que se hicieron en la subcarpeta "md". Sin embargo, en lo subsecuente sólo anotaré los cambios que haga yo.

**Comment by edithvilla** [comment]
Ayudo en la conversión de los siguientes archivos a markdown:
- [ ] 1. vulnerabilidad.docx           
- [ ] 2. traduccion_pies_graficas_entrevistas.docx       
- [ ] 3. traduccion_operationalization_of_sustainability_assertions_eob.docx 
- [ ] 4. traduccion_lecciones_aprendidas.docx
- [ ] 5. traducción_bibliografía_anotada.docx
- [ ] 6. tipos_de_aprendizaje.docx
- [ ] 7. retos_obstáculos_para_corregir.docx
- [ ] 8. recuadros_para fundamentos_filosoficos-eob.docx

los archivos markdown se están guardando en la siguiente dirección:
IAI\iai_procesamiento\integracion_informe_iai_abril2018\informe_final\md

**Comment by edithvilla** [comment]
Reunión para revisar las figuras del informe de IAI y las fichas de IAI: MIÉRCOLES 7 DE AGOSTO A LAS 4:00 PM

**Comment by Nayita** [comment]
@edithvilla he concluido con los md. Necesitas ayuda para los otros?

**Comment by Nayita** [comment]
Los archivos pre-finales concluidos:
[ ] ciencias_de_la_sostenibilidad
[ ] fases_proceso_teoria
[ ]

**Comment by Nayita** [comment]
El archivo fundamentos_filosoficos_incompleto_eo se hará cuando ya se haya corregido totalmente para no trabajar doble

**Comment by edithvilla** [comment]
Los ochos archivos ya están listos en markdown:
IAI\iai_procesamiento\integracion_informe_iai_abril2018\informe_final\md

**Comment by Nayita** [comment]
Minuta de 8 de agosto
Se revisaron las figuras y se decidió mandar un correo a Luis para consultar dos conceptos: instrumento fronterizo y el sistema biofísico-técnico.

Se corregirán cinco figuras con las correcciones a conceptos.

**Comment by EsmeraldaOsejo** [comment]
Hola,
Luis sí respondió sobre los términos. Dice que "sistema biofísico-técnico" y "sistema biofísico-infraestructural" son lo mismo, pero que se prefiere el segundo. Quizá habría que actualizar la ficha en inglés también...

**Comment by EsmeraldaOsejo** [comment]
Subí el archivo traduccion_ethic_orientations a "pre-finales". Aún no sé qué vamos a hacer con él al final, pero ya lo pueden pasar a md.

**Comment by edithvilla** [comment]
Ya están actualizadas las figuras con forme a la reunión del 8 de agosto y se encuentran en:

/IAI/iai_procesamiento/integracion_informe_iai_abril2018/figuras

**Comment by Nayita** [comment]
Ya se pasó a md el archivo de fundamentos_filosóficos.
Se comenzará con el archivo traduccion_ethic_orientations
Se comenzará con el diseño de la página web

**Comment by Nayita** [comment]
Se comenzó a trabajar en la página web para el informe. La plantilla elegida resultó ser más complicada para usarla de lo esperado. Al no ser una plantilla previamente precargada en GitHub pages requería de mayores conocimientos de programación para hacerla. Después de estar descargando diversos programas y complementos así como programar en la consola de windows y leer todo el instructivo para comenzar a utilizar la plantilla (3 horas), se decidió utilizar WordPress para hacer la página. Se creó una cuenta con la cuenta institucional y  se eligió una plantilla gratis para empezar a diseñarla.
La plantilla es muy parecida a lo que Luis nos mostró como ejemplo. Se está en proceso de formación de la página.

**Comment by Nayita** [comment]
Les dejo la liga de la página web en formación del informe: lancisapc.wordpress.com
para que la chequen y hagan sus comentarios y aportaciones.
@paola-gp

**Comment by EsmeraldaOsejo** [comment]
Muchas gracias, @Nayita 
Probablemente sea necesario cambiar la plantilla y hacer algunos ajustes. Luis dio la instrucción de que me encargue yo de la página, por ahora. Me abocaré a subir los contenidos y terminar de estructurarla. También continúo con la revisión de textos. Igualmente son bienvenidos todos los comentarios.

**Comment by Nayita** [comment]
Por indicaciones de la coordinadora se concluye mi actividad en este issue hasta nuevo aviso y me desasigno.

**Comment by paola-gp** [comment]
@Nayita: favor de dar formato con plantilla al informe final de IAI se llama informe_6sept2019_labt.docx y está en /IAI/iai_procesamiento

**Comment by Nayita** [comment]
Listo el informe con plantilla de informes de IAI en word y pdf. Ruta: \IAI\iai_informes\iai_informe_ago2019IAI\
Archivo: 
informe_final_iai_ago2019.docx
informe_final_iai_ago2019.pdf

Informe enviado al jefe de laboratorio en pdf

**Comment by Nayita** [comment]
Concluido
