### ISSUE TITLE
Crear repositorio documental de proyecto #PAPIIT

### ISSUE THREAD

**Issue by lancis-apc** [lancis-apc/planeacion-colaborativa#841]
- [x] Publicar ubicación

- [x] Añadir:

 
UNEP. The Coastal EBA Decision
Support Tool (DST) | Coastal
Ecosystem-Based Adaptation.

UNEP-WCMC. Managing Ecosystems
in the Context of Climate Change
Mitigation: A Review of Current
Knowledge and Recommendations for
Action., 2016.

**Comment by edithvilla** [comment]
@lancis-apc  por repositorio documental te refieres a una carpeta para colocar los documentos? si es así ya está:
/PAPIIT/pap_publicaciones

y a qué te refieres con "añadir", te refieres a colocarlos en un catálogo? a qué los busque y los coloque en el repositorio?
