### ISSUE TITLE
Revisar la información de la página de la ccud #organización

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#842]
### Revisar la información de la página de la CCUD
http://www.ccud.unam.mx/procedimientos

Revisar los siguiente documentos
- [ ] Protocolo de integración y publicación en el Portal de Datos Abiertos UNAM, Colecciones Universitarias

http://www.ccud.unam.mx/doc_ccud

- [ ] Acuerdo por el que se establecen los Lineamientos Generales para la Política de Acceso Abierto de la Universidad Nacional Autónoma de México
- [ ] Lineamientos para la integración y publicación de las colecciones universitarias digitales en el Portal de DAtos Abiertos UNAM, Colecciones Universitarias
- [ ] Términos de Libre Uso de Datos Abiertos de la UNAM
- [ ] Reglamento de transparencia, acceso a la información pública y protección de datos personales para la Universidad Nacional Autónoma de México

**Comment by vichdzgeo** [comment]
Victor: Revisar las diferencias entre la Norma técnica para metadatos (INEGI) y el ISO 19115
