### ISSUE TITLE
Preparar banco de datos con análisis de Resoutivos#OIPA

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#844]
El archivo se pondrá en OIPA/oipa_banco_de_datos

**Comment by Nayita** [comment]
Se elaboró un glosario y un README para la mejor comprensión del banco de datos. 
Ambos documentos ya se encuentran en la liga que se mencionó.
Faltan pequeñas correcciones y revisión final del banco de datos.
Se concluye hoy 14 de mayo de 2018

**Comment by Nayita** [comment]
@paola-gp ya quedó el banco de datos registro_resolutivo_2006. Esta en la siguiente ruta OIPA/oipa_banco_de_datos junto con el glosario y el README. Quedo pendiente

**Comment by Nayita** [comment]
@paola-gp 
Se generó una carpeta llamada registro_resolutivo. En esta carpeta está el banco de datos, el glosario y un readme.
El glosario está terminado con la descripción de todos los nombres de las columnas.
El readme tiene descrito el contenido además del significado  de cero, uno y espacios vacíos.
Los dos archivos que permanecen fuera de la carpeta son: un banco de datos donde sólo está la síntesis de las MIAs; y otro banco de datos donde sólo está toda la información registrada de la revisión de MIAs turísticas costeras, sin la información del análisis de los resolutivos y sin la hoja de síntesis de MIAs. Por lo tanto, ambos archivos permanecen en esa carpeta.
Quedo pendiente...

**Comment by paola-gp** [comment]
¿La revisión del banco de datos en la sección relacionada con "gaceta ecológica" se hizo para todos los años?  Porque hay registros vacíos en el 2011, 2013 y 2016 para el campo "registros duplicados".

**Comment by paola-gp** [comment]
también hay registros vacíos en el 2013 en la sección Historial del trámite, para el campo Sin registro.

**Comment by paola-gp** [comment]
Verificar los campos MIA que no se pudieron descargar  y Resolutivos que no se pudieron descargar. Aparece como que solo 6 del primero y 2 del segundo cumplen con esta condición para el periodo 2002-2006

**Comment by paola-gp** [comment]
No hay ningún registro en el campo Condicionado a la modificación del proyecto y a nuevas medidas de mitigación, por qué se incluyó?

**Comment by Nayita** [comment]
Como se que estás trabajando con el archivo voy a abrir el archivo Corina para ir contestando tus peguntas y comentarios

**Comment by Nayita** [comment]
Para la revisión y corrección del banco en cuanto a falta de registro de algún tipo de resolución por parte de la autoridad ("Resolutivos") se hizo lo siguiente:
Verificar con número de expediente cual era el estatus del registro en cuanto a resolutivo en el repositorio de documentos del dropbox y/o en la página web de SEMARNAT
Actualizar columna de "sin registro" y en la de "no descarga de MIAs y Resolutivos"
Actualizar registros en análisis de Resolutivos por falta de información debido a una distracción al registrar o descuido al momento de descargar Resolutivos
 Hacer tabla dinámica con el banco de datos actualizada

**Comment by Nayita** [comment]
@paola-gp 
La base de datos ya está corregida. La ruta en la que esta es OIPA/oipa_banco_de_datos/registro_resolutivo y el archivo se llama registro_resolutivo_2006_nrn
Duda:
Al hacer la tabla dinámica en la columna de "Suma de Resolutivos que no pudieron descargarse" los valores siguen siendo los mismos que en la tabla anterior sin corrección. Al cambiar a "Conteo de REsolutivos que no pudieron descargarse" el valor es muy alto. Al sumar manualmente esta columna me da un resultado muy diferente a lo que se resume en la tabla dinámica.
No entiendo por qué está pasando esto o qué debo hacer en la base de datos para que si sume correctamente

**Comment by Nayita** [comment]
la hoja de la tabla dinámica se llama evaluacion_resolutivo_estado_nr

**Comment by paola-gp** [comment]
Parece que se quedó en chache los datos viejos. Hiciste la tabla dinámica de cero?  Sugiero copiar la hoja Turisticas por expediente final a otro archivo y empezar en ahí de cero, para asegurar que no se mantiene el caché anterior.

**Comment by Nayita** [comment]
@paola-gp 
Si la hice desde cero pero al parecer sucedió lo que dijiste. Ya quedó lista la tabla. Está en la liga OIPA/oipa_banco_de_datos/registro_resolutivo. El archivo se llama evaluacion_resolutivo_estado_nrn_v1

**Comment by Nayita** [comment]
Corregida la tabla de evaluación_resolutivo_estado.
El archivo con el nombre de registro_resolutivo_gaceta es la base de datos con las dos columnas agregadas de "resolutivo sin gaceta en historial" y "se cuenta con resolutivo"

**Comment by Nayita** [comment]
Concluido
