### ISSUE TITLE
Actualizar gráficas para el informe de IAI #IAI

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#847]
ubicación: /Archivos_Socio_Institucional/Gestión 20 y logística (Docs administrativos)/Gráfica de interacciones

**Comment by edithvilla** [comment]
- [ ] Revisar informe de IAI
- [ ] Identificar la última versión de las gráficas
- [ ] Actualizar las gráficas
- [ ] Exportar las gráficas en png en la versión español
- [ ] Guardar la versión del archivo en /IAI/iai_procesamiento/graficas

**Comment by edithvilla** [comment]
@Nayita ya están listas las actualizaciones de las gráficas para el informe de IAI; están en español.
ubicación: \CARPETAS_TRABAJO\evilla\entrega
Observaciones:
1. La gráfica de los pie no estoy segura que Luis las quiera sobre todo la del 2018 (fi_sectores.png)
2. La gráfica de interacciones el nombre de los meses tendría que estar en minúsculas? (fi_megadapt_interacciones_t213.png)

**Comment by Nayita** [comment]
@edithvilla muchas gracias. Ya las moví a IAI/iai_procesamiento/integracion_informe_iai_abril2018/graficas.
1. Del punto 2 así como las pusiste yo creo que están bien. Ya lo veré con Luis y lo mismo con las gráficas de pie que éll decida.
2. Falta la gráfica de las entrevistas en español. Aún cuando no hay mayor actualización quiero que Luis vea si quiere integrarla.

Gracias

**Comment by edithvilla** [comment]
@Nayita ya está lista la gráfica:
\CARPETAS_TRABAJO\evilla\entrega\fi_megadapt_entrevistas.png

**Comment by Nayita** [comment]
@edithvilla acuso de recibido. gracias
