### ISSUE TITLE
Hacer prueba piloto encuesta Laboratorio Binacional #LABIN

### ISSUE THREAD

**Issue by AbrilKirikou** [lancis-apc/planeacion-colaborativa#850]
En seguimiento a instrucciones del Dr. Bojórquez, se les solicita que contesten la siguiente encuesta: https://es.surveymonkey.com/r/VT8LLG7

El objetivo de este ejercicio es evaluar el desempeño en línea y preparar el procesamiento de los resultados de esta encuesta. Por ello, el contenido de sus respuestas NO es relevante, sino el proceso de llenado de la misma. 

Como parte de este ejercicio también se les solicita que envíen al  al correo acidsali@asu.edu las respuestas a las siguientes preguntas

1. ¿Cuánto tiempo les tomó contestar TODA la encuesta?
2. Si tuvieron dificultades técnicas (respuestas incompletas, el sitio web no se cargó, etc.) favor de especificarlas

Atentamente,

Abril

**Comment by EsmeraldaOsejo** [comment]
Listo.

**Comment by aleestrada** [comment]
Se realizó encuesta. Las observaciones se enviarán al correo que se indicó.

**Comment by serranoycandela** [comment]
Ya

**Comment by lancis-apc** [comment]
Listo.

**Comment by edithvilla** [comment]
Listo

**Comment by bibianamonsivais** [comment]
Ya quedó

**Comment by Nayita** [comment]
Hecho

**Comment by dpedroza74** [comment]
Hecho

**Comment by AbrilKirikou** [comment]
Gracias a todos por su participación

**Comment by rociobrito** [comment]
Listo
