### ISSUE TITLE
Extraer capas de dinámica costera de II-UNAM de backup ZOFEMAT #organización 

### ISSUE THREAD

**Issue by AbrilKirikou** [lancis-apc/planeacion-colaborativa#858]
Por este medio solicito los datos originales de la II-UNAM, que se utilizaron en el proyecto de ZFMT, que están en el disco duro. Los datos corresponden a capas vectoriales (shp) y tablas en excel.

**Comment by lancis-apc** [comment]
Se va a dar acceso a los discos duros para que selecciones las capas que necesitas @AbrilKirikou . A partir de la selección, se deberá seguir el protocolo para documentar y mantener la línea de custodia de las capas.

**Comment by AbrilKirikou** [comment]
Gracias por la respuesta, quedo a la espera del acceso a los discos duros. ¿Podrían indicarme la ruta del protocolo para documentar y mantener la línea de custodia de las capas? Tomando en consideración que no se trata de productos desarrollados por el APC, sino insumos que se obtuvieron de SEMARNAT.

**Comment by lancis-apc** [comment]
Con base en la reunión de organización con Luis del 7/05/2018, la encargada de crear y mantener el repositorio de estas capas con base en protocolo es @AbrilKirikou

**Comment by AbrilKirikou** [comment]
¿Me podrían indicar de cuál protocolo hablan?

**Comment by edithvilla** [comment]
@AbrilKirikou ya está instalado el programa de TeamViewer en la computadora de escritorio para poder tener acceso remoto a esa computadora.
mando por telegram el ID de la computadora

**Comment by edithvilla** [comment]
@AbrilKirikou la carpeta II-UNAM se ubica en:

/PAPIIT/pap_insumos/integracion/

se está cargando en este momento
