### ISSUE TITLE
Solicitar una cuenta institucional a Alejandro #ORGANIZACIÓN-APC

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#860]
@bibianamonsivais 
El nombre de la cuenta sería lancis_apc@iecologia.unam.mx
Password el que queramos. Se aceptan propuestas y se notifica a Edith para su resguardo.
Esta nueva cuenta servirá para:
Cuenta de Mendeley
Migración del repositorio de GitHub

**Comment by bibianamonsivais** [comment]
Acabo de solicitarlo por correo, tal y como me indicaron que hiciera en cómputo. 
Queda pendiente su respuesta.

**Comment by bibianamonsivais** [comment]
Ya se creó la cuenta lancis_apc@iecologia.unam.mx
