### ISSUE TITLE
Buscar información sobre mercados públicos y ambulantes en el portal de la cdmx #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#861]
Mercado sobre ruedas

http://www.sedeco.cdmx.gob.mx/programas/programa/mercado-sobre-ruedas

Incidencias cdmx
http://www.datosabiertos.cdmx.gob.mx:5000/dataset/incidencias-cdmx

**Comment by edithvilla** [comment]
@Nayita por favor podrías agregar esta página como consulta de datos a la página de APC

http://www.datosabiertos.cdmx.gob.mx:5000/dataset

Título: Conjunto de datos abiertos de la Ciudad de México

**Comment by edithvilla** [comment]
### Buscar información sobre mercados públicos y sobre ruedas 
Esta información se necesita para generar la capa de basura.
En el página de la Secretaría de Desarrollo Económico, solo viene información (csv) para la Delegación Álvaro Obregón, tiene información geográfica de ubicación y día en el que se ponen los mercados sobre ruedas. La información se encuentra en:
\MEGADAPT\mega_insumos\agosto2018\sedeco

Ya pedí la información por medio del portal de transparencia de la CDMX

**Comment by edithvilla** [comment]
Responsable del programa de Mercados sobre ruedas:
José Luis Rodríguez Cuautli
Tel. 56822096 ext. 155

**Comment by edithvilla** [comment]
ya se metió la solicitud en la PNT
Folio de la solicitud    0103000061618

el oficio se encuentra en:
\MEGADAPT\mega_insumos\agosto2018\infomex

**Comment by edithvilla** [comment]
La plataforma Nacional de Transparencia no ha entregado nada, esta semana voy a ir a las instalaciones de averiguar sobre la información

**Comment by edithvilla** [comment]
al día de hoy 30 de agosto no hay respuesta del Portal de Transparencia.

Acudí a la SEDECO y me proporcionaron la liga a la Gaceta Oficial Distrito Federal:

http://www.sedecodf.gob.mx/archivos/Menu_Horizontal/2015/InformacionRelevante/GODF_Aviso_listado_Mercados_Publicos_CDMX_16042015.pdf

viene el listado de mercados públicos de la ciudad de méxico

en el dropbox se encuentra en:
\MEGADAPT\mega_insumos\agosto2018\sedeco\GODF_Aviso_listado_Mercados_Publicos_CDMX_16042015.pdf

**Comment by edithvilla** [comment]
[GODF_Aviso_listado_Mercados_Publicos_CDMX_16042015.pdf](https://github.com/lancis-apc/planeacion-colaborativa/files/2337003/GODF_Aviso_listado_Mercados_Publicos_CDMX_16042015.pdf)

**Comment by edithvilla** [comment]
sigo en espera de que conteste el Portal de Transparencia

**Comment by edithvilla** [comment]
4 de septiembre, sin recepción de respuesta del PNT

**Comment by edithvilla** [comment]
6 de agosto
@paola-gp @serranoycandela @vichdzgeo @nadia
ya mandaron el shape de mercados públicos

\MEGADAPT\mega_insumos\agosto2018\infomex\Mercados_CDMX.shp


también tenemos una base de datos georreferenciada de los mercados sobre ruedas de la delegación Álvaro Obregón

\MEGADAPT\mega_insumos\agosto2018\mercados_ruedas_alvaro_obregon\tianguis_alvaro_obregon.csv

**Comment by vichdzgeo** [comment]
La capa "Mercados_CDMX" ha sido incorporada según protocolo. su ubicación esta disponible en:

SIG/insumos/sosciedad/ifomex/vector/Mercados_CDMX.shp

Listo el meta dato de la capa: http://magrat.mine.nu:8088/geonetwork/srv/spa/catalog.search#/metadata/19ef873b-f2e5-4044-aed9-0a1bfdf06793
