### ISSUE TITLE
Proporcionar capas geográficas al equipo de salud #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#862]
@aleestrada @yosunemiquela 
ubicación de los datos: \MEGADAPT\mega_sig\gis_compartido
La liga se compartirá mediante correo para que puedan descargar los archivos

- [x] 1. Capa de incidencia de enfermedades diarréicas por AGEBs de la Secretaría de Salud de 2007-2014.

- [x] 2. Censo de población de INEGI por AGEB de los años 2005-2010. Ya coloqué la del 2015

- [x] 3. Capa de comercios informales de alimentos.

- [x] 4. Capa del sistema de drenaje.

- [x] 5. Capa de índice de severidad de encharcamientos de SACMEX de los años 2007 a 2014 que procesó Yosune; si se puede por separado bien, sino los datos acumulados.

- [x] 6. Datos de causas de encharcamientos de los años 2007 a 2014 (no importa que venga por colonia).

**Comment by aleestrada** [comment]
Es importante indicar que los datos del 2015 corresponden a la Encuesta Intercensal, que como su nombre lo indica es una encuesta no un censo, por lo que no se puede trabajar con información a nivel de AGEB, sólo se pueden hacer inferencias a partir del nivel de municipio.

**Comment by aleestrada** [comment]
Ya se colocó en la carpeta indicada, los archivos con los Censos de Población y Vivienda del 2005 y 2010, para el Distrito Federal. Ambos archivos cuentan con glosario de términos.

**Comment by edithvilla** [comment]
Estamos en proceso de general los metadatos de las capas faltantes

**Comment by edithvilla** [comment]
Ya se colocó en la carpeta la capa de Drenaje Profundo con sus respectivos metadatos

**Comment by yosunemiquela** [comment]
las capas anuales de severidad de encharcamientos anulaes 2007-2014 con sus respectivos metadatos están en:
CARPETAS_TRABAJO/Ymiquelajauregui/encharcamientos_severidad-anuales
@edithvilla

**Comment by edithvilla** [comment]
confirmo de recibido y ya las ubiqué en la carpeta compartida

**Comment by edithvilla** [comment]
@yosunemiquela faltaría: 6. Datos de causas de encharcamientos de los años 2007 a 2014 (no importa que venga por colonia). esto no viene en las capas que me diste

**Comment by edithvilla** [comment]
@vichdzgeo revisar la información de los datos y metadatos que entregó @yosunemiquela 
los archivos son:
encharcamientos_prec_(2007-2014).shp, .xml
\MEGADAPT\mega_sig\gis_compartido

**Comment by edithvilla** [comment]
@yosunemiquela 
Fuente de la información:
Sistema de Aguas de la Ciudad de México
Dirección Ejecutiva de Planeación y Construcción
Subdirección de Planeación e Inversión
Unidad Departamental de Planes Maestros de los Sistemas Hidráulicos
Oficio Número:

**Comment by edithvilla** [comment]
@yosunemiquela y @aleestrada por favor revisen lo que hace falta para entregar a más tardar mañana (22 de mayo) al equipo de salud

**Comment by vichdzgeo** [comment]
encharcamientos_preci_2007.xml 
Observaciones para su edición:

campo | observación
-------  | -------------
1.12 frecuencia de mantenimiento y actualización | cambiar por 9. No programado o por 10. Desconocido
1.13 Conjunto de caracteres | Cambiar el conjunto de caracteres por Utf-8
5.1.4.1 Nombre del datum horizontal | WGS84
5.1.4.2 Nombre del elipsoide | WGS84
6.3.3.1. Descripción | Agregar el año correspondiente a la capa utilizada de AGEBS así como citar a SACMEX, el nombre del archivo proporcionado y el número de oficio.
7.1 Descripción general de entidades y atributos | Describir algo similar a: El archivo shape cuenta con 2428 registros y su definición geométrica es de tipo polígono, representan o definen las áreas geoestadisticas básicas para la ciudad de México, ademas están asociadas a ciertas variables de encharcamientos como: frecuencia, magnitud, y cinco indices que varían entre 0 y 1, donde el 0 corresponde a la severidad nula y el uno a la severidad máxima.
7.2 Cita del detalle de ntidad y atributos | En este apartado se escriben el nombre de los campos contenidos en la tabla de atributos seguido por unidades y descripción.  puede verse un ejemplo de ello en el metadato siguiente /MEGADAPT/mega_sig/gis_compartido/DrenProf_sacmex.xml
9.6 Conjunto de caracteres | Cambiar el conjunto de caracteres por Utf-8

**Comment by vichdzgeo** [comment]
Metadatos verificados.

**Comment by yosunemiquela** [comment]
Ya quedó la capa de tipo de encharcamientos a nivel de colonia para el 2007-2014.
La ruta es:
CARPETAS_TRABAJO/Ymiquelajauregui/tipo_encharcamiento

Faltan metadatos
@edithvilla

**Comment by edithvilla** [comment]
Ya hice una copia de la carpeta en la carpeta que le compartimos a la Dra. Mazari
Quedamos en espera de los metadatos

**Comment by yosunemiquela** [comment]
ya quedaron los metadatos para la capa  de causas de encharcamientos de los años 2007 a 2014 por colonia.
La ruta es:
CARPETAS_TRABAJO/ymiquelajauregui/tipo_encharcamiento/metadatos

@edithvilla @vichdzgeo
