### ISSUE TITLE
Generación de Metadatos geográficos con base a la Norma Técnica #ORGANIZACIONAPC

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/planeacion-colaborativa#866]
@aleestrada @yosunemiquela @serranoycandela @bibianamonsivais @13Emilio @AbrilKirikou @Nayita 
Requisitos:

Tener instalado Java
descargar el programa SICAM:
inegi.org.mx/geo/contenidos/metadatos/doc/instaladorsicam.zip

Para los que no se encuentre en la CDMX poder conectarnos vía skype, solo pedimos que nos confirmen

**Comment by 13Emilio** [comment]
Hola, yo no podré estar en la reunión

**Comment by vichdzgeo** [comment]
Las plantillas para metadatos se encuentran en la siguiente ruta: ORGANIZACION_APC/apc_plantillas/plantillas_metadatos

Para cargar la plantilla deseada:

1.  Ejecutar la aplicación SICAM
2. Al aparecer la leyenda de ingresar IP, dejar en blanco y dar clic en aceptar
3. Ir al menú principal > Archivo > Abrir registro
4. La aplicación preguntara si desea grabar el archivo sin nombre, dar clic en No
5. Se abrirá una ventana para la navegación, elegir la plantilla xml conforme al sistema de referencia que correspondan los datos
6. Cambiar los datos de contacto y llenar los campos necesarios para la generación del metadato.
7. Una vez terminado el llenado de los campos, ir a menú principal > Archivo > Guardar como
8. Guardar con el mismo nombre que tiene la capa de la cual se realizan los metadatos.
