### ISSUE TITLE
Coadyuvar en la elaboración de protocolos de registro de metadatos

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#875]
Enseñar a Victor la estructura que deben llevar los protocolos y colaborar en la redacción. Subir los protocolos a la página web de GitHub de APC. Los protocolos quedarán en la siguiente ruta ORGANIZACION_APC/apc_iso/protocolos

**Comment by Nayita** [comment]
Victor envió su documento. En estos días lo reviso para enviarle comentarios

**Comment by Nayita** [comment]
Se pasa a la siguiente semana la revisión por trabajo en prioridades.

**Comment by Nayita** [comment]
@vichdzgeo 
Hola, ya terminaste el protocolo para que lo cheque?

**Comment by Nayita** [comment]
@vichdzgeo 
Van mis observaciones, todas son de forma:

- Revisar que se inicien los párrafos con mayúsculas.

- Checar redacción y ortografía en general.

- Indicar dónde vivirán los repositorios o dónde están.

- Integrar figuras.

- No se puede hacer referencia a issues. Mejor se agrega la información contenida en el issue al protocolo

**Comment by Nayita** [comment]
Nuevas actividades para este issue:
Colaborar en la elaboración del manual de este protocolo. 
Revisar los cambios al protocolo

**Comment by Nayita** [comment]
Se ha terminado con la corrección del protocolo. Salvo un par de correcciones ya está listo y mañana se revisa la versión final.

Se revisó y corrigieron los avances del manual. Mañana se termina la versión final.

**Comment by Nayita** [comment]
Protocolo terminado
Manual faltan terminar correcciones y se concluye

**Comment by Nayita** [comment]
Se sube el protocolo a la página web

**Comment by Nayita** [comment]
SE hacen correcciones al manual y se sube a la página web

**Comment by vichdzgeo** [comment]
Protocolo para revisión

/CARPETAS_TRABAJO/vhernandez/protocolos/protocolo_manejo_info_gis.md

**Comment by Nayita** [comment]
Concluido
