### ISSUE TITLE
Hacer tablas para el documento de candidatura #OIPA

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#886]
Las gráficas quedarán disponibles en la siguiente ruta OIPA/oipa_procesamiento/graficas

**Comment by Nayita** [comment]
Las gráficas cambiaron a tablas. La liga donde estarán es la siguiente OIPA/oipa_procesamiento/figuras

**Comment by Nayita** [comment]
@paola-gp 
Te voy poniendo en CARPETAS_TRABAJO/nruiz/oipa/tablas las tablas para tu revisión. Las tablas con vo.bo. quedarán en la ruta de arriba

**Comment by Nayita** [comment]
@paola-gp 
También quieres las tablas de evaluación_resolutivo_estado y año, verdad?

**Comment by Nayita** [comment]
@paola-gp 
Ya están las seis tablas. Espero tus comentarios

**Comment by paola-gp** [comment]
las puedes poner en OIPA/oipa_procesamiento/tablas

**Comment by Nayita** [comment]
listo!

**Comment by paola-gp** [comment]
Las cifras de una misma unidad nunca se centran. Asimismo, faltan las mismas tablas por año.

**Comment by Nayita** [comment]
Corrijo lo de las cifras. En cada archivo están también las de año.
Cambio el nombre de los archivos para hacerlo general. En cada archivo estarán tanto por estado como por año

**Comment by Nayita** [comment]
@paola-gp 
ya están las tablas corregidas. En cada archivo están tanto por estado como por año. El nombre de los archivos son: ta_evaluacion_resolutivo.docx, ta_historial_tramite.docx y ta_reg_gaceta.docx

**Comment by paola-gp** [comment]
Tengo la impresión de que los datos están mal en las tablas. No me dió tiempo de verificar, pero puedes hacerlo tu por favor?

**Comment by Nayita** [comment]
Yo copié y pegué los datos de las tablas dinámicas. En algunas les di otro orden a las columnas y en la de tabla de evaluación le cambié el título a una de las columnas porque no era suma de MIAs sino de registros de resolutivos.
He verificado los datos de las tablas dinámicas y son los mismos de las tablas que hice.
De todas maneras me puse a hacer algunas sumas de las columnas y coinciden con los resultados de las tablas dinámicas. 
Si quieres que revise algo en específico...estoy pendiente para verificar

**Comment by paola-gp** [comment]
Ya revisé las tablas dinámicas y tienes razón. Me preocupan los datos porque después de tu última depuración resulta que solo hay un proyecto con solicitud de consulta pública. Recuerdo que antes la cifra era mas grande.

**Comment by Nayita** [comment]
Checo eso específicamente. Pero yo no modifiqué nada de esas columnas. Podría ser la variación entre las columnas del historial del trámite y las del análisis de resolutivos. Déjame verifico

**Comment by Nayita** [comment]
@paola-gp 
Resuelto el motivo de la inconsistencia en datos de las tablas. En la primera tabla dinámica que hiciste tomaste en cuenta la información de la columna de consulta pública del análisis del Resolutivo junto con las del historial. En esta nueva tabla solo tomaste la información del historial, pero esa es la correcta porque justo estás haciendo referencia a la información que se encontró registrada en el historial. Claramente esa información no está bien reportada. Al leer los Resolutivos se encuentran las inconsistencias del mal registro en el historial

**Comment by Nayita** [comment]
Concluido
