### ISSUE TITLE
Extraer valores de las variables de precipitación, y evapotranspiración #MEGADAPT

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/planeacion-colaborativa#892]
- [x] Crear cuenta para acceder a los datos patung
- [x] Escribir la ruta de donde se encuentran los datos
- [x] Elaborar el script para automatizar el proceso de extracción

**Comment by vichdzgeo** [comment]
@yosunemiquela  me podrías indicar de favor la ruta donde se encuentran los archivos raster de evapotranspiración, ya tengo acceso a patung. 
Gracias

**Comment by yosunemiquela** [comment]
/srv/home/yosune/Climatico/ValleyofMexico_ClimateProducts/IndividualProducts/Livneh/Clipped/NonAveraged/Gridded/UTM/gtiff

**Comment by vichdzgeo** [comment]
Se generaron archivos shape por año para cada variable. 
los datos se encuentran en la siguiente ruta:
CARPETAS_TRABAJO\vhernandez\megadapt\swat\Seriesdetiempo

**Comment by vichdzgeo** [comment]
1 generar una cuadricula del tamaño de pixel de los archivos raster.
2. intersectar el archivo shape de bandas para cada cuenca con la cuadrìcula tamaño de pixel = 6250,6250

**Comment by vichdzgeo** [comment]
Investigando como crear un campo en el shape y que su valor sea la operación matematica de dos campos existentes (area*precmean)

**Comment by vichdzgeo** [comment]
se creo un código en colaboración con Fidel, utilizando solo archivos csv, utilizando python y pandas para optimizar el proceso, se logro reducir el tiempo de 1 día de procesamiento a 1 minuto (Esto es por año y por variable).

**Comment by vichdzgeo** [comment]
Se modifica el código con el fin de hacerlo más acorde a las necesidades del proyecto.

**Comment by vichdzgeo** [comment]
## Proceso 

El script se modifico para automatizar el proceso, ingresando solo el rango de años deseados y el nombre de la variable a trabajar, se crea un archivo por año.

## Problema
la base de datos contiene algunos casos donde para la misma cuenca hay más de 1 elemento clasificado en la misma banda: 
Ejemplo:

![image](https://user-images.githubusercontent.com/38017509/41925372-057dd2ec-7932-11e8-8c17-576110eed6df.png)

Se discute este problema con Fidel y Yousune para darle solución.

**Comment by vichdzgeo** [comment]
## Solución
Se toma la decisión de calcular promedio ponderado de las variables, con el fin de obtener solo un valor único por banda correspondiente de cada cuenca.

## Proceso
Se crea un script con el fin de ejecutar la solución por año por variable.

Ruta: CARPETAS_TRABAJO\vhernandez\megadapt\swat\bandaspixeltobandas\variables\wighted_average_por_banda.py

**Comment by vichdzgeo** [comment]
## Problema
Se tiene que crear series de tiempo (1993 - 2013)  para cada cuenca y sus bandas respectivas, teniendo en cuenta que donde no existan valores ( esto es dado que no  todas las cuencas poseen valores en las 6 bandas de elevación) se tienen que poner 0. 

Ejemplo: 
La Cuenca 1, solo tiene como banda de elevación la B1, la solución del problema es crear una lista como la siguiente: 
![image](https://user-images.githubusercontent.com/38017509/42105177-05e0f9c0-7b95-11e8-9196-a1564ecbb85e.png)

## Solución: 
 Se crea un script para generar los archivos por cuenca y por año.

## Solución
De los archivos obtenidos con el script anterior, se ocupan como insumo para un un nuevo script que concatenara los archivos por año, creando un único archivo

**Comment by vichdzgeo** [comment]
## Entrega

Se obtienen 244 archivos csv  (1 por cuenca) de las variables de precipitación (prec) y evapotranspiración (PET) de los años 1993-2013.

Ruta: \CARPETAS_TRABAJO\vhernandez\megadapt\swat\entregas\pet_prec_cuenca_ts

**Comment by vichdzgeo** [comment]
@yosunemiquela
