### ISSUE TITLE
Hacer tabla de tratados internacionales #OIPA

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#893]
Dar formato a la tabla de compromisos internacionales de Jennifer.
El documento terminado está en la siguiente ruta OIPA/oipa_procesamiento/tablas. El archivo tiene el siguiente nombre compromisos_internacional

**Comment by Nayita** [comment]
@paola-gp 
Checa la tabla y espero tu vo.bo

**Comment by paola-gp** [comment]
perfecta gracias. Cierro el issue
