### ISSUE TITLE
Preparar logística para la reunión con el  Coordinador de Innovación y Desarrollo #SVACC

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#894]

**Comment by edithvilla** [comment]
ya está lista la lista de asistencia

**Comment by edithvilla** [comment]
@paola-gp 
ya esta creada la estructura de las carpetas para la presentación de mañana
por favor puedes colocar el archivo pdf aquí

/PRESENTACIONES/pr_lancis_labbinacional_unam_asu/pr_vinculacionunam_07jun2018/insumos

**Comment by paola-gp** [comment]
1. Para después de la presentación, cambiar el nombre de labbinacional a SVACC. 
2. Ya está en insumos el último muck up de la SIGnificance: Plataforma significance-.pdf

La respuesta de NAVIC sobre lo que indican los rubros del muck up: 
en catálogos opciones que se requieren para configurar la plataforma, desde la adminsitracion de usuarios, roles, hasta adminsitracion de proyectos, si asi se decide; en proyectos: opciones para acceder directamente a reporte de los proyectos ya creados; y otra para ir directamente a la creacion de nuevos proyectos. estas opciones deben ir creciendo con la definición de los roles y la manera como se quiera manejar el licenciamiento.

**Comment by Nayita** [comment]
1. listo el cambio a svacc.

**Comment by edithvilla** [comment]
ya está escaneada la lista de asistencia y ubicada:
/Presentaciones/pr_lancis_svacc_unam_asu/pr_vinculacionunam_07jun2018/logistica

**Comment by Nayita** [comment]
Lista minuta. Ver ubicación issue #895
