### ISSUE TITLE
Participar en la presentación de plataformas #binacional

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#895]

**Comment by Nayita** [comment]
Se hará la minuta. El archivo quedará registrado en la siguiente ruta Presentaciones/pr_lancis_svacc_unam_asu/pr_vinculacionunam_07jun2018
El archivo se llama minuta_vinculacionunam_07jun2018

**Comment by Nayita** [comment]
Concluido

**Comment by paola-gp** [comment]
Agregar puntos de minuta a este issue

**Comment by paola-gp** [comment]
cambiar el proyecto de pr_lancis_svacc_unam_asu a: pr_svacc

**Comment by Nayita** [comment]
Acuerdos de la Minuta

1.	Tener la reunión con Salvador Morales para ver lo de la protección de la propiedad intelectual.
2.	Revisar el convenio de colaboración con Plenumsoft para que quede cubierta la confidencialidad de la información.
3.	El Mtro. J. M. Romero trabajará con su abogada para que se le de sentido a la estructura.
