### ISSUE TITLE
Organizar la dinámica de trabajo para el proyecto #Consolidación

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#903]
Acuerdos de la reunión del 12/junio/2018

- @aleestrada es responsable del producto plan de negocios conforme a los compromisos del proyecto de Consolidación. 
- @aleestrada es responsable de dar seguimiento a la propiedad intelectual de SIGnificance y SIGplanning. 
- @rociobrito es responsable de dar seguimiento con Luis a toda la porción administrativa y financiera del proyecto. La hoja de cálculo con los acuerdos específicos está en: /ADMIN/admin_apc/consolidacionlancis2018/consolidac_presupfinal_acuerdos12jun2018.xlsx
- @paola-gp no es responsable de ningún aspecto administrativo o financiero del proyecto. 
- @paola-gp es responsable de dar seguimiento y coordinar el trabajo técnico de NAVIC. 
- @dpedroza74 puede convertirse en la coordinadora del proyecto sujeto a que haya otra coordinación para el proyecto PAPIIT. 
- Luis es responsable de redactar contrato con NAVIC para segmentar y generar productos parciales diferenciables. 
- Ulises se compromete a: averiguar costos de auditoria, verificar restricciones de la partida Ediciones e impresiones divulgación, resolver la porción administrativa del proyecto (apertura de cuenta, etc.) para iniciar operaciones antes del cierre vacacional de la UNAM. 
- @rociobrito requiere verificar los acuerdos hechos antes de esta reunión para las fechas límites de entrega del área de planeación colaborativa a la administración para que esta última elabore los informes correspondientes. 

Primer informe parcial: 1 de agosto
Segundo informe parcial: 20 de septiembre
Informe final: 15 de noviembre. La fecha de entrega a CONACYT es el 30 de noviembre y no hay prórroga
Fecha última para hacer trámites en la administración de IE: 30 de octubre.
IMPORTANTE:
Todo el presupuesto de cuenta corriente del proyecto debe gastarse al 30 de noviembre. Cheques emitidos al 30 de noviembre pueden ser cobrados en diciembre.
Dirigirse directamente con Lizbeth en administración para cualquier duda del contenido del archivo de la presentación, y de los informes, y para la entrega de los informes financieros.
El documento enviado por Lizbeth con estas fechas y con un resumen de información importante de lo visto en la capacitación. La ruta es la siguiente: ADMIN/admin_apc/consolidacionlancis2018
. El documento se llama: solicitud_cambios_transferencias_conacyt

**Comment by aleestrada** [comment]
Estimada @paola-gp, estoy de acuerdo con los acuerdos estipulados en la minuta, sólo una duda. ¿Los informes que mencionas son los administrativos, no es así? Si es así, ¿tenemos fechas de los académicos?

**Comment by paola-gp** [comment]
@aleestrada   No tenemos claridad sobre los informes técnicos, la coordinación del proyecto nos tendrá que informar. Sin embargo, para noviembre seguramente se tiene que entregar un informe técnico que respalde el finiquito "oficial" del proyecto.

**Comment by Nayita** [comment]
Ruta donde se encuentra la información de actividades por persona: ADMIN\admin_propuestas\conacyt\consolidacion_ln_2018\activ_participante_31jul18_v2

**Comment by Nayita** [comment]
@edithvilla y @vichdzgeo Este es el issue para el informe. A continuación describo las actividades a realizar:

- Depurar la lista de participantes que entregarán informe

- Obtener las actividades en la plataforma de CONACYT de cada participante

- Hacer una tabla con los entregables de cada participante de acuerdo a la información ingresada a Conacyt

- Hacer informes correspondientes a cuatro pagos con sus respectivos respaldos. Les mando la liga donde está el ejemplo entregado por Paola: ADMIN/admin_apc/admin_auditoria_ecosus y los informes en: CARPETAS_TRABAJO/pgpriego/auditoria_ecosus

- Colaborar con la elaboración del informe técnico

**Comment by rociobrito** [comment]
/ADMIN/admin_apc/admin_consolidacionlancis2018/Participantes_apoyo_econ%C3%B3mico.xlsx   aquí está el archivo de participantes de conacyt que reciben apoyo económico

**Comment by dpedroza74** [comment]
Acabo de crear una carpeta con los formatos del informe que pide CONACYT en /home/CONSOLIDACION/con_informes/formatos_conacyt
Ahí viene una tabla de excel ITF 294714 que es donde se tiene que subir la información, tanto de los integrantes del grupo de trabajo (hoja de cálculo con título Inform técnico final) como el resto de estudiantes (incluyendo servicios sociales) que trabajan en LANCIS (hoja de cálculo con título Recursos humanos). @Nayita me informó que irá capturando la información ahí. 
En el documento pdf LN 2018 Especificaciones de entrega viene toda la explicación de lo que hay que presentar como informe. Ahí se especifica qué se debe adjuntar una reseña de las actividades de cada uno de los beneficiados en el gasto de los mismos:
• 320 Gastos de trabajo de campo
• 321 Honorarios por servicios profesionales (gestor de proyectos)
• 336 Pasajes y viáticos
• 485 Estancias técnicas/académicas
• 488 Honorarios para un técnico especializado
• 518 Incorporación de estudiantes.

A reserva de platicarlo con Luis, yo propongo que para el caso de gastos de trabajo de campo, pasajes y viáticos se haga una reseña general. Propongo como ejemplo lo que entregamos en el informe de PAPIIT que es un documento de word ejercicio presupuesto_papiit que está en 
 /PAPIIT/pap_informes/informe_avan_año1

**Comment by edithvilla** [comment]
Para los colaboradores que tengan que entregar comprobables para la auditoria, podrán colocar su información en siguiente carpeta:
\CONSOLIDACION\con_informes\comprobables_auditoria
Dentro de la carpeta **comprobables_auditoria**
Las carpetas están nombradas con las iniciales del nombre de los colaboradores

**Comment by Nayita** [comment]
@paola-gp el nombre es "Apoyos Complementarios para la Consolidación de Laboratorios Nacionales CONACYT"

**Comment by Nayita** [comment]
@dpedroza74 Ya quedó llenado el rubro de servicios sociales en la hoja de recursos humanos. Quedo pendiente

**Comment by dpedroza74** [comment]
Ya  integré la información  al avance que yo tenía en el formato y lo subí como un nuevo archivo llamado **ITF 294714_21nov**. Sin embargo, sugiero que se especifque más sobre los productos y actividades, ya que no creo que sea suficiente decir que hacen su servicio social.

**Comment by edithvilla** [comment]
@paola-gp en esta ruta se encuentra el informe de Pacífico Norte, etapa de Pronóstico en donde viene incorporado la sección de Vulnerabilidad:

/PACIFICO/pn_informes/pn_julio_2015/III. Pronóstico.pdf

**Comment by Nayita** [comment]
@paola-gp @yosunemiquela 
La ruta de los formatos es la siguiente:
/home/CONSOLIDACION/con_informes/formatos_conacyt
Daniela comenta que la información de los productos está en el siguiente archivo, cuya ruta es la siguiente:
CONSOLIDACION/con_informes/formatos_conacyt?preview=ITF+294714_23nov.xlsx

**Comment by paola-gp** [comment]
@vichdzgeo  para la elaboración de la página de internet, necesito quitar el blanco de fondo de todos los logos que aparecen en raíz de /ORGANIZACION_APC/apc_logotipos/00_logo_lancis
@Nayita indicará donde quedarán alojadas las nuevas versiones

**Comment by Nayita** [comment]
@vichdzgeo nombra el archivo del logo que  generes de la siguiente forma logo_lancis_completo_vsf.
Guardalo en la misma ruta que te indicó Paola. Gracias

**Comment by vichdzgeo** [comment]
Los archivos se agregaron conforme a lo especificado y en la ruta indicada: 
el nombre de los archivos es:
- logo_lancis_2018_vsf.png
- logo_lancis_completo_2018_vsf.png

**Comment by vichdzgeo** [comment]
Los logos en color blanco y sin fondo se agregaron en la ruta indicada:

el nombre de los archivos es:

- logo_lancis_2018_vbsf.png
- logo_lancis_completo_2018_vbsf.png
@paola-gp

**Comment by vichdzgeo** [comment]
Colores de lancis:

RGB = 68,200,245
![image](https://user-images.githubusercontent.com/38017509/48958818-3367be00-ef27-11e8-8dee-197e7e0a77b0.png)

RGB= 173,195,43

![image](https://user-images.githubusercontent.com/38017509/48958840-4d090580-ef27-11e8-9fb6-c863a78c36be.png)

RGB= 3,78,162
![image](https://user-images.githubusercontent.com/38017509/48958849-5f833f00-ef27-11e8-8b5a-71709803c84d.png)

**Comment by vichdzgeo** [comment]
Los archivos sin fondo con el imagotipo de color y la tipografía en blanco se agregaron en la ruta indicada:
el nombre de los archivos es:

logo_lancis_2018_vsf_v2.png
logo_lancis_completo_2018_vsf_v2.png
@paola-gp

**Comment by dpedroza74** [comment]
La carpeta para subir el material de impacto ambiental 
@paola-gp
 @Nayita 
CONSOLIDACION/con_informes/primer_informe_30nov2018/cursos_en_linea/impacto_amb

**Comment by dpedroza74** [comment]
Lo siento, subí un formato equivocado para el registro de los cursos optativos de posgrado. Ya puse el correcto en 
/CONSOLIDACION/con_informes/insumos
se llama
Formato cursos nuevos_.docx
@paola-gp 
@yosunemiquela 
y la carpeta para subirlos está en 
/CONSOLIDACION/con_informes/primer_informe_30nov2018/cursos_optativos

**Comment by Nayita** [comment]
@paola-gp va el link de las gacetas ecológicas http://sinat.semarnat.gob.mx/Gaceta/aniosgaceta

**Comment by paola-gp** [comment]
@Nayita: necesito el link de las guías para hacer las EIA

**Comment by Nayita** [comment]
@paola-gp va https://www.gob.mx/cms/uploads/attachment/file/121010/Guia_MIA-Particular_Turistico.pdf

**Comment by paola-gp** [comment]
@Nayita: Agregar a\primer_informe_30nov2018\plataformas_computacionales:

- [ ] Entrega plenumsoft

- [ ] https://github.com/sostenibilidad-unam/parallel_coordinates_maps

- [ ] https://github.com/sostenibilidad-unam/geo-value-function

**Comment by Nayita** [comment]
@paola-gp va el link
http://www.cmic.org.mx/comisiones/Sectoriales/medioambiente/Gu%C3%ADas%20SEMARNAT/MIA,%20Informe%20Preventivo%20y%20DTU/MIA%20Regional/MIA%20Regional.pdf

**Comment by Nayita** [comment]
@dpedroza74 
Ya están las actividades actualizadas de los servicios sociales. El archivo se llama: ITF 294714_28nov_nrn.
La liga es:\CONSOLIDACION\con_informes\formatos_conacyt. Quedo pendiente de cualquier corrección.

**Comment by Nayita** [comment]
Listos pdfs de los informes de los estudiantes en la carpeta indicada

**Comment by dpedroza74** [comment]
Ya subí el informe final ITF 294714_30nov a la carpeta /CONSOLIDACION/con_informes/primer_informe_30nov2018

**Comment by Nayita** [comment]
@dpedroza74 en la carpeta honorarios_becas quedaron los siguientes archivos: honorarios.pdf e informes_estudiantes.pdf
La liga es la siguiente: C:\Dropbox (LANCIS)\CONSOLIDACION\con_informes\primer_informe_30nov2018\honorarios_becas.
El archivos informes_estudiantes es una copia del archivo que está en la carpeta estudiantes.

**Comment by paola-gp** [comment]
ya está informe final en PDF firmado en /CONSOLIDACION/con_informes/primer_informe_30nov2018
