### ISSUE TITLE
Hacer gráficas para presentación svacc-eia#svacc

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#908]
Las gráficas terminadas quedarán en la siguiente ruta:
Presentaciones/pr_svacc/pr_svacc-eia_19jun2018/procesamiento/graficas

**Comment by paola-gp** [comment]
El insumo a usar está en /OIPA/oipa_banco_de_datos/registro_resolutivo/registro_resolutivo_2006_pgp_v3
Las gráficas que se necesitan están en las hojas:
1. Reg_gaceta_estado
2. Historial_tramite_estado
3. evaluacion_resolutivo_estado
4. desfa registro gaceta (para esta copiar el título a la diapositiva)

**Comment by paola-gp** [comment]
cambiar el nombre de /OIPA/oipa_banco_de_datos/ a /OIPA/oipa_bd/ en cuanto acabe este proceso.

**Comment by Nayita** [comment]
@paola-gp 
Listas las diapositivas con las gráficas. La ruta es la siguiente: Presentaciones/pr_svacc/pr_svacc-eia_19jun2018/procesamiento/graficas/gr_registro_resolutivo

Las gráficas están de acuerdo al orden de las indicaciones de arriba.

**Comment by paola-gp** [comment]
ya se agregaron títulos. Sin embargo, se necesita volver a copiar las gráficas para que tengan el mismo tamaño de origen (calcúlalo en número de celdas y columnas), considerando que entre mas grande sean de origen, mejor resolución tendrán en la presentación. Actualmente algunas gráficas están distorsionadas.

**Comment by Nayita** [comment]
Ya agregué las gráficas hechas bajo las indicaciones, espero que hayan mejorado. Las veo bien en la pantallita de la compu pero habrá que verlas en grande

**Comment by Nayita** [comment]
Ya están los slides en la carpeta de la plataforma. Tienen la numeración que originalmente tenían las diapositivas. La liga es la siguiente: Presentaciones/pr_svacc/pr_svacc-eia_19jun2018/plataforma/graficas

**Comment by Nayita** [comment]
Concluido
