### ISSUE TITLE
Preparar logística de la reunión svacc-eia #svacc

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#909]
ubicación:
Presentaciones/pr_svacc/pr_svacc-eia_19jun2018

@Nayita ya cree las carpetas

**Comment by edithvilla** [comment]
Ya están los archivos para la lista de asistencia y minuta
/Presentaciones/pr_svacc/pr_svacc-eia_19jun2018/logistica

**Comment by paola-gp** [comment]
Parallel coordinates 1: http://pc.magrat.mine.nu/parallel_coordinates_maps/a6a93870b514d79c0cbe766204456367

**Comment by paola-gp** [comment]
Parallel coordinates 2 no funciona:

http://pc.magrat.mine.nu/parallel_coordinates_maps/ec56acfbbafaaccf5a2c6353b489c97f

**Comment by paola-gp** [comment]
http://shark.navic.mx/proyecto/detail/1
usuario: userlancis contraseña: pwlancis

**Comment by paola-gp** [comment]
http://pc.magrat.mine.nu/parallel_coordinates_maps/ed0505a13b4a0ec2cd0ada8972f24096

este es el segundo bueno

**Comment by edithvilla** [comment]
Ya está scaneada la lista de asistencia y ubicada en:
/Presentaciones/pr_svacc/pr_svacc-eia_19jun2018/logistica

Ya agregué la minuta
/Presentaciones/pr_svacc/pr_svacc-eia_19jun2018/logistica

el archivo README.txt ya está listo también
/Presentaciones/pr_svacc/pr_svacc-eia_19jun2018/
