### ISSUE TITLE
Reportar la liga de reportes y/o protestas de inundaciones, escasez #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#914]
Se invita a toda la comunidad a compartir noticias, tweet, fotos y videos sobre reportes y/o protestas sobre inundaciones y escasez
Las ligas a las noticias pueden comentarlas en este issue
@rgarcia-herrera @serranoycandela @paola-gp @vichdzgeo @Nayita @rociobrito @aleestrada @dpedroza74 @13Emilio @AbrilKirikou

**Comment by paola-gp** [comment]
Sugiero que se de-suscriban para que no les lleguen los reportes de todos. 
http://www.eluniversal.com.mx/metropoli/cdmx/lluvia-deja-inundaciones-al-sur-de-la-cdmx

**Comment by aleestrada** [comment]
¿Qué les parece crear un grupo para realizar esto (facebook, twitter, telegram, whatsapp) y ahí compartimos las ligas y después (puede ser cada semana) las copiamos y pegamos en este issue.
Esto lo digo considerando que es más fácil que estemos en contacto con este tipo de noticias fuera de a oficina que en ella y que sería más fácil compartirlas por medio del teléfono que en la computadora.

**Comment by paola-gp** [comment]
@edithvilla ya creó el grupó.

**Comment by edithvilla** [comment]
se cierra este issue

Los reportes de las inundaciones quedaron en la carpeta de insumos del proyecto de megadapt
