### ISSUE TITLE
Preparar insumos para la reunión de preparación para la presentación de CID-UNAM#

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#918]
Crear una carpeta en la siguiente ruta: ENTREGAS/cid_unam
Donde estarán todos los manuales y protocolos necesarios para presentaciones en anfiteatro.
Escribir un listado de requisitos de la plantilla de diapositivas para la presentación. Este archivo llamado requisitos_diapositivas quedará en esta ruta, una vez que se termine

**Comment by Nayita** [comment]
Se ha concluido esta actividad

**Comment by Nayita** [comment]
Los documentos contenidos en la carpeta son:
Protocolo de logística
Manual para ajustar el tamaño de slides generadas en PowerPoint a la resolución del Anfiteatro
Plantillas de presentaciones y guiones
Acciones de photoshop

**Comment by Nayita** [comment]
De la reunión de hoy se terminaron las siguientes tareas:
Agregar a insumos el archivo de la lista de asistencia y la minuta
Agregar en el documento de requisitos, la lista de información requerida para solicitar el Anfiteatro
Hacer revisión y correcciones finales.

**Comment by Nayita** [comment]
Actividad concluida

**Comment by paola-gp** [comment]
yo creo que es redundante tener dos issues para lo que en si es la misma actividad.

**Comment by Nayita** [comment]
ya cerré el otro y este también lo voy a cerrar y ya abrí otro
