### ISSUE TITLE
Participar en reunión de logística para el cid #organización

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#919]

**Comment by Nayita** [comment]
Tareas por hacer producto de la reunión:
Agregar a insumos el archivo de la lista de asistencia y la minuta
Agregar en el documento de requisitos, la lista de información requerida para solicitar el Anfiteatro
Hacer revisión y correcciones finales.
Enviar el vínculo para compartir la carpeta cid-unam a los encargados de la presentación.

**Comment by paola-gp** [comment]
@Nayita ya se envió la invitación al dropbox a la gente del CID? quedaron que este fin de semana mismo trabajaban en los contenidos. El documento de requisitos y recomendaciones requería algunas labores de edición e último minuto. Se requiere poner aquí la ubicación y todo lo que se les pone en ese lugar y mantener actualizado lo que suben.
