### ISSUE TITLE
Colaborar en la gestión de la presentación del cid-unam#GENERAL

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#920]
La Dra. Cecilia ya envió los datos para la solicitud del Anfiteatro.
Ya se envió la solicitud a la Dra. Ana.
Se está en espera de respuesta.

**Comment by Nayita** [comment]
El Anfiteatro se utilizará en las siguientes fechas:
Para el día 29 de junio de 12 a 14 horas y dos ensayos uno para el miércoles 27 de junio de 12 a 13:30 horas y el otro para el jueves 28 de junio de 12 a 13:30 horas.
A continuación se deescriben los datos requeridos que envió la Dra. Cecilia.
•        Objetivos del evento: Mostrar la funcionalidad operativa del SIMISE aplicada a la planeación del Sector Energético Mexicano
•        Investigador o profesor responsable: Dra. Cecilia Martín del Campo Márquez

•        Proyecto asociado; Unidad de Planeación Energética (UPE)

•        Institución (y departamento o área, si aplica) UNAM: Coordinación de Innovación y Desarrollo  y Facultad de Ingeniería 

•        Tipo de evento: Presencial

•        Número de personas (mínimo 10, máximo 30): Quince

•        Fecha del evento: 29 de junio del 2018

•        Hora de inicio del evento: 10:00 horas

•        Hora de término del evento: 12:30 horas

•        Uso del equipo: Asociado a la sala de Inmersión

Café y galletas.

**Comment by Nayita** [comment]
Información del issue #918

Crear una carpeta en la siguiente ruta: ENTREGAS/cid_unam/insumos
Donde estarán todos los manuales y protocolos necesarios para presentaciones en anfiteatro.
Escribir un listado de requisitos de la plantilla de diapositivas para la presentación. Este archivo llamado requisitos_diapositivas quedará en esta ruta, una vez que se termine.

Los documentos contenidos en la carpeta son:
Protocolo de logística
Manual para ajustar el tamaño de slides generadas en PowerPoint a la resolución del Anfiteatro
Plantillas de presentaciones y guiones
Acciones de photoshop

Actividades terminadas producto de la reunión:
Archivos de lista de asistencia y minuta agregados a la carpeta de insumos
Documento de requisitos de diapositivas corregido y terminado
Vinculo generado y enviado para compartir la carpeta cid-unam a los encargados de la presentación
Correo enviado para notificarles el envío del vínculo y pedir confirmación

**Comment by Nayita** [comment]
Ya quedaron los slides al tamaño Anfiteatro en la siguiente liga ENTREGAS/cid_unam/plataforma/slides

**Comment by Nayita** [comment]
La Dra. Cecilia avisó que va a modificar el guion. Lo ponen en la siguiente ruta mañana a las 9:00 am
 ENTREGAS/cid_unam/plataforma

**Comment by Nayita** [comment]
La Dra. Cecilia envió el guion incompleto y los slides sin el tamaño adecuado. Están haciendo las correcciones.
Se acordó que vendrán a las 12:00 para hacer el guión en conjunto y entender el funcionamiento el Anfiteatro

**Comment by Nayita** [comment]
Se envió un correo a la Dra. Cecilia para notificar quién les dará la bienvenida por parte de LANCIS. También se solicitó nos informara el nombre de los asistentes a la presentación.

**Comment by Nayita** [comment]
En espera de respuesta.

**Comment by edithvilla** [comment]
@Nayita 
La lista de asistencia se encuentra en:
/PRESENTACIONES/pr_otras/pr_externas/asistencia_simise_29jun2018

**Comment by Nayita** [comment]
Ya está la orden del día en:
/PRESENTACIONES/pr_otras/pr_externas/pr_simise_29jun2018/asistencia_simise_29jun2018.pdf

Se hizo un nuevo link para que la Dra. Cecilia pueda tener acceso a los slides porque quiere hacer un respaldo

Concluido

**Comment by Nayita** [comment]
Lista de asistencia y minuta de la presentación del 29 de mayo de 2019 guardada en la siguiente ruta: PRESENTACIONES/pr_otras/pr_externas/pr_simise_29may2019

**Comment by Nayita** [comment]
Concluida por el momento
