### ISSUE TITLE
Recopilar catálogo de probatorios del APC a partir de formulario #organización

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#922]
Propuesta de reunión: martes 26 de junio a las 11 am.

**Comment by edithvilla** [comment]
Estoy encargada de hacer el formulario que alimentará la base de datos de códigos

**Comment by edithvilla** [comment]
Estoy preparando el formulario (27 de jun, 2018)

**Comment by edithvilla** [comment]
Se hizo un formulario de google para crear el banco de datos con las siguiente preguntas:
Sección 1
1. Nombre del código
2. Descripción general
3. Fecha de creación
4. Ubicación
5. Autor
Sección 2
6. Se cuenta con imágen
7. Se cuanta con la licencia
8. Indica el nivel de avance del readme
9. Indica el nivel de avance de la documentación del código
10. ¿El código cuenta con datos de prueba?
11. ¿Se cuenta en repositorios públicos?
12. ¿Se siguió la guía de estilo de programación?
13. Prioridad de atención


El formulario se envía por correo electrónico compartiendo la liga a los colaboradores (Fidel, Alejandra, Yosune y Víctor

**Comment by edithvilla** [comment]
@paola-gp  Liga del formulario:
https://docs.google.com/forms/d/e/1FAIpQLSdItXYX1aXY2R9RN85IiI1VMDuJrCtB_EAl8zy4T5NtThJi1g/viewform?usp=sf_link

**Comment by edithvilla** [comment]
@vichdzgeo @serranoycandela @yosunemiquela @aleestrada 

Esta es la liga para llenar el formulario del catálogo (código, software, script)

https://docs.google.com/forms/d/e/1FAIpQLSdItXYX1aXY2R9RN85IiI1VMDuJrCtB_EAl8zy4T5NtThJi1g/viewform?usp=sf_link

**Comment by edithvilla** [comment]
solo para recordarles:

@vichdzgeo @serranoycandela @yosunemiquela @aleestrada

Esta es la liga para llenar el formulario del catálogo (código, software, script)

https://docs.google.com/forms/d/e/1FAIpQLSdItXYX1aXY2R9RN85IiI1VMDuJrCtB_EAl8zy4T5NtThJi1g/viewform?usp=sf_link

**Comment by edithvilla** [comment]
solo para recordarles:

@vichdzgeo @serranoycandela @yosunemiquela @aleestrada

Esta es la liga para llenar el formulario del catálogo (código, software, script)

https://docs.google.com/forms/d/e/1FAIpQLSdItXYX1aXY2R9RN85IiI1VMDuJrCtB_EAl8zy4T5NtThJi1g/viewform?usp=sf_link

**Comment by edithvilla** [comment]
solo para recordarles que necesitamos tener un catálogo de códigos, por lo tanto es necesario llenar el siguiente cuestionario

@vichdzgeo @serranoycandela @yosunemiquela @aleestrada @iaga 

Esta es la liga para llenar el formulario del catálogo (código, software, script)

https://docs.google.com/forms/d/e/1FAIpQLSdItXYX1aXY2R9RN85IiI1VMDuJrCtB_EAl8zy4T5NtThJi1g/viewform?usp=sf_link

**Comment by edithvilla** [comment]
Los códigos con su respectiva documentación se ubicarán en las siguientes carpetas del dropbox:
1. Para códigos de **R**:
/ORGANIZACION_APC/apc_repositorio_r

2. Para códigos de **python**:
/ORGANIZACION_APC/apc_repositorio_python

**Comment by edithvilla** [comment]
solo para recordarles que necesitamos tener un catálogo de probatorios, por lo tanto es necesario llenar el siguiente cuestionario

@vichdzgeo @serranoycandela @yosunemiquela @aleestrada @iaga

Esta es la liga para llenar el formulario del catálogo 
https://goo.gl/forms/f6c8xJ6OLdBtvxUn1

**Comment by edithvilla** [comment]
@iaga @JosueMA @AlfMedina 

por favor prueben esta liga para llenar el formulario de códigos

https://goo.gl/forms/OARo7mq6EeuEQHxC2

**Comment by iaga** [comment]
Gracias Edith, no tenemos acceso. Iremos mañana a sacar la cuenta del instituto para tener acceso al formulario.

**Comment by edithvilla** [comment]
solo para recordarles que necesitamos tener un catálogo de probatorios, por lo tanto es necesario llenar el siguiente cuestionario

@vichdzgeo @serranoycandela @yosunemiquela @aleestrada @iaga

Esta es la liga para llenar el formulario del catálogo
https://goo.gl/forms/f6c8xJ6OLdBtvxUn1

**Comment by edithvilla** [comment]
solo para recordarles que necesitamos tener un catálogo de probatorios, por lo tanto es necesario llenar el siguiente cuestionario

@vichdzgeo @serranoycandela @yosunemiquela @aleestrada @iaga

Esta es la liga para llenar el formulario del catálogo
https://goo.gl/forms/f6c8xJ6OLdBtvxUn1

**Comment by edithvilla** [comment]
solo para recordarles que necesitamos tener un diagnóstico de los códigos, script que tenemos en el laboratorio y en qué estado se encuentra, por lo tanto es necesario que llenen el siguiente cuestionario para tener conocimiento 

@vichdzgeo @serranoycandela @yosunemiquela @aleestrada @iaga

Esta es la liga para llenar el formulario del catálogo
https://goo.gl/forms/f6c8xJ6OLdBtvxUn1

**Comment by edithvilla** [comment]
se cierra este issue hasta nuevo aviso
