### ISSUE TITLE
Enlistar necesidades de papelería y cómputo #APC

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#936]
@vichdzgeo @Nayita @yosunemiquela @serranoycandela @paola-gp @AbrilKirikou @13Emilio @aleestrada @iaga @rociobrito @dpedroza74 

Colocar en este issue sus necesidades de papelería y cómputo, gracias

**Comment by edithvilla** [comment]
1. Grabadoras con entrada usb (2)
2. Post it
3. Aire comprimido
4. Cuadernos forma francesa
5. Caja de lápices no. 2
6. Caja de bolígrafos color negro
7. Hubs

**Comment by vichdzgeo** [comment]
1.- Candado para laptop dell precision 3520 
Datos específicos del candado -> Manufacturer Part:K9T4D Dell Part: A7112559

**Comment by iaga** [comment]
1.- TECLADO INALÁMBRICO LOGITECH K270 o bien TECLADO ALÁMBRICO LOGITECH K120
2.- Paquete de hojas blancas tamaño carta

**Comment by yosunemiquela** [comment]
1. Thunderbolt a HDMI
2. Paquete de hojas blanca ecológico
3. regla
4. tijeras
5. corrector líquido
6. tres paquetes de puntillas de 0.5
7. tinta negra para HP número 96

**Comment by yosunemiquela** [comment]
Paquete de folders manila tamaño carta

**Comment by 13Emilio** [comment]
Sony - Grabadora Digital ICD-PX470 (grabadora con entrada USB; sólo la encontré en bestbuy)
1 juego de pilas recargables AA
1 juego de pilas recargables AAA

**Comment by 13Emilio** [comment]
Para la Dra Escalante:
MONITOR LED DELL E2216H 21.5 PULGADAS / 1920 X1080 / 60 HZ / VGA / DISPLAY PORT
Magic Keyboard con teclado numérico, Español, Gris espacia
Ratón Apple Magic Mouse 2 - Inalámbrico - Gris - Bluetooth -MAC - Rueda de desplazamiento táctil - Simétrico

**Comment by edithvilla** [comment]
esta es la última llamada para cerrar la lista de papelería, mañana se cierra el issue.
