### ISSUE TITLE
Hacer compilación de información para auditoría #GENERAL

### ISSUE THREAD

**Issue by Nayita** [lancis-apc/planeacion-colaborativa#952]
@paola-gp aquí está el issue para tus instrucciones. 
La información quedará en la siguiente liga ADMIN/admin_apc/auditoria_ecosus

**Comment by paola-gp** [comment]
Hoja membretada para hacer oficio de entrega de productos para auditoría:
carpetas trabajo\pgpriego\entrega/ecosus_membretada

**Comment by Nayita** [comment]
Hacer oficios por cada producto para la auditoría con dos días anteriores a la fecha de factura. Verificar que sean días hábiles.

Terminado el producto de la plataforma. Liga en la página de GitHub del formulario

- [ ] Desarrollo de algoritmos (shells Marco)
- [ ] Formato y edición de contenidos (página de LANCIS-OFICIO)
- [ ] Preparación de protocolos (protocolos)

**Comment by Nayita** [comment]
@paola-gp 
En el siguiente enlace están los cuatro oficios para que los cheques y firmes para que así queden en las carpetas de los productos
CARPETAS_TRABAJO/nruiz/auditoria

**Comment by paola-gp** [comment]
oficios, CD y acuses listos para entrega. Se cierra issue
