### ISSUE TITLE
Elaborar insumos para propuesta # FOMIX

### ISSUE THREAD

**Issue by dpedroza74** [lancis-apc/planeacion-colaborativa#953]
Revisar los documentos de la convocatoria (archivos pdf) que se encuentran en el dropbox
ADMIN/admin_propuestas/conacyt/fomix_yucatan_2018/insumos/convocatoria

Elaborar un párrafo con su semblanza, considerando en qué actividades participarán en el proyecto. Colocarlas en la carpeta para revisión el lunes 20
ADMIN/admin_propuestas/conacyt/fomix_yucatan_2018/insumos/semblanzas

Les pido que también incluyan en el documento su CURP y que actualicen su CVU en el sistema de CONACYT

**Comment by AbrilKirikou** [comment]
listo

**Comment by edithvilla** [comment]
Creamos la carpeta: "manejo_banco_datos" en 
ADMIN/admin_propuestas/conacyt/fomix_yucatan_2018/insumos/semblanzas

En esta carpeta colocamos el párrafo correspondiente a este tema y los protocolos asociados.

**Comment by iaga** [comment]
Hecho

**Comment by aleestrada** [comment]
Listo, se subió semblanza

**Comment by aleestrada** [comment]
Se colocó un archivo, en la misma carpeta,  sobre el análisis de microdatos.

**Comment by Nayita** [comment]
listo semblanza...

**Comment by vichdzgeo** [comment]
listo semblanza

**Comment by vichdzgeo** [comment]
Del objetivo V:
- Desarrollar la parte de ISO9001 y protocolos. - Nadia
- Describir en qué consiste la parte de mantenimiento. - Fidel y Victor
- Describir en que consiste las posibles contingencias - Fidel y Victor

**Comment by Nayita** [comment]
@dpedroza74 
Ya está el párrafofinal del objetivo V en la siguiente ruta: ADMIN/admin_propuestas/conacyt/fomix_yucatan_2018/insumos/propuesta?preview=propuesta_objespV_fomix_pgpv1_vhd.docx

**Comment by edithvilla** [comment]
semblanza lista

**Comment by edithvilla** [comment]
Ya quedó la actualización del protocolo de recepción de activos de información:
ADMIN\admin_propuestas\conacyt\fomix_yucatan_2018\insumos\semblanzas y parrafos\manejo_banco_datos\lancis_fed_pcr.pdf

**Comment by JosueMA** [comment]
Listo (Semblanza, CURP y CVU).

**Comment by Nayita** [comment]
PDF del protocolo de organización de activos de información listo en:
ADMIN/admin_propuestas/conacyt/fomix_yucatan_2018/insumos/semblanzas%20y%20parrafos/manejo_banco_datos?preview=protocolo_org_activ_info.pdf
CVU actualizado
