### ISSUE TITLE
Dar acceso a Bertha a las carpetas socio-institucionales de MEGADAPT en Dropbox

### ISSUE THREAD

**Issue by heakin** [lancis-apc/planeacion-colaborativa#954]
Hola Paola; encontramos una seria de archivos que Bertha necesita subir a Dropbox. Le puede dar acceso para que pueda completar este trabajo? 

Gracias (Ojala estoy haciendo esto bien -- primera vez usando el "issue" en GitHub

**Comment by paola-gp** [comment]
reasignada a @edithvilla

**Comment by edithvilla** [comment]
21ago2018
Mandé vinculo por correo electrónico a Bertha con copia a Hallie y Paola de la carpeta del dropbox
Archivos_Socio_Institucional

**Comment by edithvilla** [comment]
@paola-gp ya intenté compartir carpetas, crear vínculos de las carpetas, y no puede tener acceso. Qué puedo hacer?

**Comment by edithvilla** [comment]
@heakin necesitamos tu autorización para quitar el acceso a los usuarios de la carpeta "Archivos_Socio_Institucional" para poder solucionar la visualización de los archivos.

**Comment by edithvilla** [comment]
@heakin sigo en espera de tu autorización para quitar acceso a los usuarios de la carpeta "Archivos_Socio_Institucional" para poder solucionar la visualización de los archivos.

**Comment by heakin** [comment]
Si por supuesto.

**Comment by edithvilla** [comment]
Se le dio a Bertha acceso a las carpetas del Dropbox con éxito, ella puede entrar mediante vínculos.

@heakin  te compartí las carpetas, puedes acceder a ellas o no? y otra pregunta, quién tiene que tener acceso a esas carpetas? te lo pregunto para saber a quién tengo que invitar.

**Comment by heakin** [comment]
Por favor invita a Rebecca Shelton. Ella es la única otra persona ahora que lo necesita. Gracias.

**Comment by edithvilla** [comment]
Listo, ya esta invitada. Solo puede ver los archivos y descargar, no puede editar nada
