### ISSUE TITLE
Digitalizar la ubicación de los mercados sobre ruedas

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#957]
Tareas:
1. Crear una tabla en open office con la siguiente estructura: id / ruta / dia / direccion (la ruta, día y dirección se encuentra en la hoja con los datos de los mercados sobre ruedas, en la transcripción de la dirección es importante NO poner el signo de coma).

2. Digitalizar mediante la herramienta de Geocoding de QGIS
    Es importante agregar en el panel de capas de QGIS la capa de Google Street
**Nota: Guardar cada 2 o 3 nodos agregados**

3. Guardar la capa como: tp_mercados_ruedas_v1 (la versión va a cambiar cada vez que guardas nodos nuevos).

4. Una vez que se guarde la capa hay que agregar las columnas de id, ruta, dia, direccion

**Comment by edithvilla** [comment]
Ruta para guardar los archivos
\MEGADAPT\mega_procesamiento\banco_datos\mercados

**Comment by edithvilla** [comment]
Tenemos una base de datos georreferenciada de los mercados sobre ruedas de la delegación Álvaro Obregón

\MEGADAPT\mega_insumos\agosto2018\mercados_ruedas_alvaro_obregon\tianguis_alvaro_obregon.csv

Esta base de datos se unirá a la de la Ciudad de Mexico,

**Comment by Nayita** [comment]
@vichdzgeo Esta es la ruta de los archivos
\MEGADAPT\mega_procesamiento\banco_datos\mercados 
También te puse la tabla que hice con id / ruta / dia / direccion en open office

**Comment by Nayita** [comment]
Ya se terminó de hacer capas parciales de los puntos de mercados sobreruedas por rutas. Se está buscando la herramienta para unir las capas.

**Comment by vichdzgeo** [comment]
las capas parciales se unieron en una sola, se asigno el ID correspondiente al AGEB. la capa entregable esta en la siguiente ruta de DropBox: \SIG\desarrollo\megadapt\procesamiento\mercados_ruta\

El nombre de la capa es el siguiente:
tp_mercados_ruedas_ageb

**Comment by Nayita** [comment]
@vichdzgeo 
Ya está el README de la capa en la ruta que me indicaste SIG\desarrollo\megadapt\procesamiento\mercados_ruta\

**Comment by Nayita** [comment]
Metadatos hechos. Se concluye la actividad
