### ISSUE TITLE
Asignar el identificador a las colonias de la base de encharcamientos #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#963]
Asignar el identificador "col_id" a las colonias de la base de datos de encharcamientos 2009-2017. Por el momento solo se hará para las bases de datos de los años 2015, 2016 y 2017.

Insumos: 
1. ENCHARCAMIENTOS 2009 AL 2017.xlsx (este archivo fue proporcionado por SACMEX)

Ruta:
\SIG\desarrollo\megadapt\procesamiento\encharcamientos_2015_2017\insumos

Producto: 
Base de datos con el identificador del "col_id". Colocar es producto en esta ruta:
\SIG\desarrollo\megadapt\procesamiento\encharcamientos_2015_2017\insumos

**Comment by aleestrada** [comment]
#972 Vinculo el issue con la documentación del código asignado a @iaga, @AlfMedina  y @JosueMA

**Comment by aleestrada** [comment]
El documento final al que se le asignó el COL_ID a cada una de las colonias de los reportes de encharcamientos para los años 2015-2017, se encuentra en la careta indicada, en formato .CSV con el nombre:
bd_MEGADAPT_ench_15_17_colid.csv

**Comment by aleestrada** [comment]
@JosueMA y @AlfMedina  entregar por favor a @edithvilla los metadatos de la base de datos generada.
- Especificar procesamiento de los datos
- Especificar a qué se refiere cada uno de los campos de la base de datos.
