### ISSUE TITLE
Calcular número de pozos por ageb #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#965]
### Calcular el número de pozos por AGEB

Responsable: Edith Villa

Fecha: 13 de septiembre de 2018

Capas de insumo: C:\Dropbox (LANCIS)\SIG\desarrollo\megadapt\procesamiento\pozos_ageb\insumos
     mega1912PozGas17.shp
     ageb_utm.shp

Ubicación de trabajo: C:\Dropbox (LANCIS)\SIG\desarrollo\megadapt\procesamiento\pozos_ageb

Procesamiento:

1. En QGIS mediante la herramienta Vectorial/Herramientas de análisis/Contar puntos de polígonos se realizó el cálculo de pozos por AGEB.

Parámetros
- Polígonos: ageb_utm.shp
- Puntos: mega1912PozGas17.shp
- Nombre de campo de cuenta: frec_pozos
- Se crea una capa temporal

2. Se guarda la capa nueva: **pozos_ageb.shp**

En esta capa se encuentran los *campos ageb_id* y *frec_pozos*, el segundo campo se refiere al número de pozos que se encuentran por AGEB.

**Comment by edithvilla** [comment]
@iaga @aleestrada 
Ya está lista la capa de número de pozos por ageb.
C:\Dropbox (LANCIS)\SIG\desarrollo\megadapt\procesamiento\pozos_ageb

También se encuentra la información del gasto del pozo por mes para los años 2010 al 2017.
C:\Dropbox (LANCIS)\SIG\desarrollo\megadapt\procesamiento\pozos_ageb\insumos

Los insumos originales de los pozos se encuentran en:
\MEGADAPT\mega_insumos\abril2018\SACMEX\1 GASTOS 2010 AL 2017 CON DIRECCION.xls
y el procesamiento de esta base de datos se encuentra en:
\MEGADAPT\mega_procesamiento\banco_datos\gastos

**Comment by iaga** [comment]
La carpeta con la ubicación de la capa de pozos se encuentra ubicada en la ruta:
\SIG\desarrollo\sig_megadapt\entregables\pozos_ageb
