### ISSUE TITLE
Preparar talleres y reuniones Mérida 25-29 septiembre #Papiit & #Fomix

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#966]

**Comment by paola-gp** [comment]
Lo relacionado con los talleres y reuniones del viaje disponible en: PAPIIT\pap_talleres\merida\pap_merida25_29sep2018

**Comment by edithvilla** [comment]
### Preparación de insumos de información:

1. Hacer el modelo multicriterio de amenaza issue #967 está asignado a Victor

**Comment by edithvilla** [comment]
### Logística de talleres (materiales, equipo)

- [ ] Preparar formatos de salida del equipo de cómputo
- [ ] Pedir cañón
- [ ] Cargar grabadoras (2)
- [ ] Extensiones (2)
- [ ] Multicontactos (2)

**Comment by edithvilla** [comment]
Ya terminé de pasar el modelo de amenazas y está en:
\PAPIIT\pap_talleres\merida\pap_merida25_29sep2018\modelo_vulnerabilidad_costera.sdmod

**Comment by edithvilla** [comment]
se regresó todo el material
