### ISSUE TITLE
Documentar los códigos utilizados para asignar el COL_ID a las colonias de la base de datos de SACMEX

### ISSUE THREAD

**Issue by aleestrada** [lancis-apc/planeacion-colaborativa#972]
Carpeta: MEGADAPT\mega_procesamiento\input_modelos\modelo_escasez\scripts

Tareas: Documentar los scripts de Python y R, que se utilizaron para asignar el COL_ID a las colonias de las bases de datos de SACMEX.

**Comment by aleestrada** [comment]
Les comparto la liga con el protocolo de software que se tiene en LANCIS:
https://github.com/sostenibilidad-unam/protocolos/blob/master/protocolo_software.md

**Comment by iaga** [comment]
Se utilizan dos filtros:

1.- Script de Python. El objetivo de dicho script es limpiar los errores ortográficos de la base de datos original. Se utiliza el paquete flashtext https://github.com/vi3k6i5/flashtext, basado en el algoritmo publicado en el paper:

Title: |   | Replace or Retrieve Keywords In Documents at Scale
-- | -- | --
Authors: |   | Singh, Vikash
Publication: |   | eprint arXiv:1711.00046
Publication Date: |   | 10/2017
Origin: |   | ARXIV
Keywords: |   | Computer Science - Data Structures and Algorithms
Bibliographic Code: |   | 2017arXiv171100046S

2.- Script de R. El script de R mide la distancia entre palabras utilizando la distancia de Levenshtein, a partir del paquete RecordLinkage.

**Comment by iaga** [comment]
Los archivos (asociados al script de python) se encuentran temporalmente en la carpeta:
\CARPETAS_TRABAJO\igrave\MEGADAPT\scripts\filtro_bd

1. Script: filtro1.py
2. Markdown: filtro1.md

**Comment by AlfMedina** [comment]
El archivo de documentación de la parte del pre-procesamiento de la base original (script de R) se encuentran temporalmente en la carpeta: \CARPETAS_TRABAJO\amedina\MEGADAPT

**Comment by JosueMA** [comment]
El archivo de documentación de la parte de la asignación de `COL_ID` a la base de datos de encharcamientos se encuentran temporalmente en la carpeta: \CARPETAS_TRABAJO\jmendoza\MEGADAPT

**Comment by AlfMedina** [comment]
El script del pre-procesamiento y el segundo filtro se encuentran en el markdown: `asignacion_col_id.Rmd`. Este y el archivo del primer filtro están temporalmente en la carpeta:  \CARPETAS_TRABAJO\amedina\MEGADAPT

**Comment by JosueMA** [comment]
El producto final es una carpeta con los siguientes scripts (que contienen código y documentación):

* `extraccion_datos.Rmd`.- Ilustra cómo extraer datos de manera ordenada de archivos `.xlsx` proporcionados por SACMEX y generar un archivo `.csv` fácil de manipular para análisis posteriores.

Si se busca asignar identificadores a nivel colonia, para agregar posteriormente información geográfica, se sugiere usar los scripts restantes en el orden en que se enlistan:

* `filtro_python.py`.- Teniendo como insumo una bae de datos ordenada y limpia (`.csv`, con formato rectangular; como el producto del script `extraccion_datos.Rmd`), permite reescribir la columna MUNICOLO, que contiene la delegación y colonia a la que pertenece cada observación, eliminando palabras que no están registradas en la base de datos que contiene el identificador de cada MUNICOLO. Esto permite hacer la asignación con menos errores.

* `asignacion_col_id.Rmd`.- Una vez que se tiene una base de datos con la columna MUNICOLO 'limpia' (i.e., donde ya fue utilizado el script `filtro_python.py`), este script agrega una columna a la base de datos donde se asigna el identificador de cada MUNICOLO, a través de comparar el MUNICOLO escrito en el reporte con cada MUNICOLO en la base de datos que contiene los identificadores; asignándole el identificador del MUNICOLO que "más se parece" (calculando un coeficiente de similitud). 

Además, con el fin de correr los scripts de manera ordenada, se incluyen las siguientes carpetas:

* insumos: En esta carpeta se guardan los principales insumos de cada script (se especifica dentro de cada uno). Debe de contener, por lo menos: 
i) La base de datos de la cual se busca extraer información (en el ejemplo expuesto es `ENCHARCAMIENTOS  2009 al 2017.xlsx`).
ii) La base de datos que contiene el identificador correspondiente a cada MUNICOLO (`col_id.dbf`).

* intermedio: En esta carpeta se almacenan los archivos que solo se generan para ser insumo de otro script; por ejemplo, si se planea utilizar el script `filtro_python.py` después de `extraccion_datos.Rmd`, ahí se almacenaría la base de datos que resulta del primer script y que serviría de insumo para el segundo.

* productos: Es donde se gurdarán la base de datos generada después de utilizar todos los scripts (en el ejemplo es el archivo `bd_charcos_2015_2017.csv` generado por el script `asignacion_col_id.Rmd` después de haber usado los dos script anteriores.

Esta carpeta fue elaborada por @AlfMedina y @JosueMA y se encuentra en la siguiente ruta:
CARPETAS_TRABAJO/jmendoza/entregables/asignacion_col_id
