### ISSUE TITLE
Capacitar al equipo técnico de Mérida #fomix & papiit

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#973]
La presentación de la capacitación se ubica en:
\PAPIIT\pap_talleres\merida\pap_merida25_29sep2018\pr_capacitacion_25-26sep2018.pptx

Página de LANCIS-CU
https://lancis-apc.github.io/planeacion-colaborativa/

**Comment by paola-gp** [comment]
reportar avances y diagnóstico

**Comment by vichdzgeo** [comment]
Reporte del día 25/09/2018

Tiempo de capacitación:  8 horas.

- Se presenta el protocolo de activos de información.
- Se presenta el protocolo de manejo de información geográfica.
- Se presenta git-hub 
- Se presenta la estructura y el sistema de almacenamiento (dropbox)
- Se presenta la plataforma para la creación de metadatos geográficos.

Diagnóstico.

| Herramientas | Nivel de capacitación requerido |
| --- | --- |
| Dropbox | Bajo |
| Github | Alto |
| Qgis | Medio:  |
| Python | Alto |
| Atom | Medio |
| Geonetwork | Alto |
| Hojas de cálculo | Bajo |


**Bajo**: Los técnicos conocen y han usado la herramienta. La capacitación requerida solo es para cumplir los protocolos y estándares dentro de LANCIS para el trabajo colaborativo.
**Medio**: Los técnicos no conocen la herramienta pero han usado algunas similares.
**Alto**: Los técnicos no han usado la herramienta.

**Comment by vichdzgeo** [comment]
Reporte del día 26/09/2018

- Identificación de proveedores y fuentes oficiales de las capas necesarias para el modelo de vulnerabilidad costera (Mérida). tiempo estimado de actividad: 3 horas.

- Ejercicio de práctica: Generación de capas con Qgis y creación de los metadatos. tiempo estimado de actividad: 4.0 horas
