### ISSUE TITLE
Gestionar facturas, gastos y reembolsos de viáticos #general 

### ISSUE THREAD

**Issue by paola-gp** [lancis-apc/planeacion-colaborativa#974]

**Comment by paola-gp** [comment]
- [ ] Generar un repositorio @Nayita 

- [ ] Crear archivo para ingreso de datos con listas despegables- Paola

- [ ] Crear "protocolo" de reglas de operación.

**Comment by Nayita** [comment]
@paola-gp @dpedroza74 @edithvilla @serranoycandela @aleestrada @vichdzgeo 
Les envío la ruta donde pueden guardar las facturas a reembolsar: /ADMIN/admin_apc/admin_reembolso/merida_25sep2018

**Comment by Nayita** [comment]
@paola-gp @dpedroza74 @edithvilla @serranoycandela @aleestrada @vichdzgeo 
Ya se migró el archivo de registro de ingreso de datos a la siguiente ruta: /ADMIN/admin_apc/admin_reembolso/merida_25sep2018  para que completen su información en ese archivo.

**Comment by edithvilla** [comment]
listo ya ingresé mis facturas

**Comment by edithvilla** [comment]
@rociobrito

**Comment by paola-gp** [comment]
Por instrucciones de Luis, el mecanismo propuesto de integrar un banco de datos de reembolsos queda descartado. Cada quien deberá mandar via correo electrónico o whatsapp los comprobantes de los gastos generados, montos a reembolsar y cuanto tiempo pueden esperar para recibir el reembolso.

**Comment by Nayita** [comment]
Ya no se hará el protocolo de reglas de operación de viaje. Sólo "check list" de procedimientos a seguir.

**Comment by Nayita** [comment]
Por indicación de Paola, se borra el repositorio creado, y se cierra el issue.

**Comment by paola-gp** [comment]
ver #981
