### ISSUE TITLE
Hacer lista de inventario de material cómputo en el APC #organización

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#983]
Hacer lista de materiales de cómputo y papelería

FALTA:
1. Multicontacto (1)
2. Cables para monitores: VGA macho a HDMI macho (2)
3. Cable para monitor: VGA macho a VGA macho (3)
4. Cables para monitores: D-Port a HDMI macho (2) 
5. Cables para monitores: DVI-D  a  HDMI (2)
6. Proyector: 
     Acer - Proyector portátil C200, 
    Acer - Proyector X1123H SVGA - Negro, 
    Acer - Proyector X1223H XGA - Negro
7. Mouse inalámbrico, Logitech M570 (3) 
8. Discos duros externos capacidad de 2TB  (3) 
9. Post it (10)
10. Cuadernos forma francesa (10)
11. Caja de lápices no. 2 (2)
12. Caja de bolígrafos color negro (2)
13. Hubs (2)
14.- TECLADO INALÁMBRICO LOGITECH K270 o bien TECLADO ALÁMBRICO LOGITECH K120
15. Paquete de hojas blanca ecológico
16. Regla (1)
17. Tijeras (1)
18. Corrector líquido (1)
19. Puntillas de 0.5 (3)
20. Paquete de folders manila tamaño carta
21. Juego de pilas recargables AAA
22. Tinta HP 950XL negro NC045AL
23. Tinta HP 950XL cyan NC046AL
24. Tinta HP 950XL magenta NC047AL
25. Tinta HP 950XL amarillo NC048AL
26. Candados con llave (1)

@paola-gp esta es la lista final del material.

**Comment by vichdzgeo** [comment]
## Software

- Acronis
Software para la automatización de copias de seguridad para los datos almacenados en dropbox.
costo de licencia única:
1 equipo 49.99 USD
3 equipos 79.99 USD
5 equipos 99.99 USD

![image](https://user-images.githubusercontent.com/38017509/46554824-14459c00-c8a7-11e8-9786-ce298cdb0e01.png)

Propuesta para el procedimiento de respaldos automatizados:
Con la siguiente propuesta solo se requiere una 
- Sincronizar dropbox localmente en una máquina.
- Programar por día los respaldos de las carpetas separandolos por días y por dispositivo de almacenamiento (discos duros externos). 
- Verificar en el sistema si las copias fueron creadas correctamente.


- Camtasia 
Software para grabar la pantalla y edición de video. El objetivo de este software es la creación de contenido multimedia como tutoriales / cursos para la capacitación.
costo de licencia única que permite la actualización en dos máquinas:
- 249 USD precio público general
- 169 USD precio Educación

@paola-gp

**Comment by paola-gp** [comment]
@Nayita 
Generar cartas de proveduría UNAM: 
ADMIN\admin_apc\admin_papiit/presupuesto_software_papiit_!1_10_18

**Comment by Nayita** [comment]
Certificados de no venta de software obtenidos en el DGTIC descargados y enviados por correo a la administración de APC.
Actividad concluida

**Comment by paola-gp** [comment]
Al contrario de lo que encontré en otro foro, no podemos aumentarle la memoria a esas pc 
http://www.crucial.com/usa/en/compatible-upgrade-for/Dell/vostro-420-tower

**Comment by edithvilla** [comment]
@rociobrito por favor podrías indicarme en donde están las listas de las últimas compras de papelería y cómputo

**Comment by edithvilla** [comment]
Inventario de equipo de cómputo:

**Comment by edithvilla** [comment]
Descripción | Cantidad | Proveedor | Asignados
-- | -- | -- | --
HP   Adaptador HDMI a VGA | 4 | LUMEN |  
Mouse Logitech M170 | 1 | LUMEN |  
Monitores   SAMNSUNG | 3 | Cómputo coyoacan | Paola G., Víctor H. y Fidel S.
Teclados Logitech K270 | 3 | Cómputo   coyoacan | Ileana   G, Víctor H. y Edith V.
Disco   duro seagate ADATA 2 TB | 6 | Cómputo coyoacan | Paola G., Yosune (datos clima) y   Nadia R., (Respaldos)
Disco duro seagate ADATA 4 TB | 1 | Cómputo   coyoacan | Paola   G.
Dv-port   a HDMI macho | 1 | Cómputo coyoacan |  
Adaptador thunderbolt 3 a HDMI doble | 1 | Cómputo   coyoacan |  
Cable   adaptador convertidor HDMI a VGA macho-hembra | 2 | Cómputo coyoacan |  
Cable HDMI | 2 | Cómputo   coyoacan |  
Cable   de video de 1.8m VGA macho | 4 | Cómputo coyoacan |  
Mouse Logitech M570 | 2 | Cómputo   coyoacan |  
Candados   con llave | 7 | Cómputo coyoacan |  
Multicontacto | 4 | Steren |  
Cable   HDMI a DVI-D 3.6M | 2 | Steren |  
Adaptador de mini Display Port a VGA/HDM | 2 | Steren | Víctor   H.
Adaptador   USB C a HDMI / USB 3 / USB C | 1 | Steren |  
Pilas recargables AAA (paquete de 4) | 2 | Steren |  
Cable   HDMI | 2 | Steren |  
Cable VGA macho-macho | 2 | Steren |
