### ISSUE TITLE
ubicar archivo intermedio de encharcamiento con el dato de volumen #megadapt

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/planeacion-colaborativa#989]
ubicar en el procesamiento el archivo intermedio de encharcamiento con el dato de volumen

**Comment by edithvilla** [comment]
@iaga @aleestrada @serranoycandela @paola-gp 

el script y los archivos intermedios con los datos de frecuencia, volumen, volumen máximo se encuentran en la siguiente ruta en el dropbox:
\MEGADAPT\mega_procesamiento\banco_datos\encharcamientos_colonia

**Comment by iaga** [comment]
Las bases de datos con el volumen de encharcamientos sin procesar se encuentra en: CARPETAS_TRABAJO/ymiquelajauregui/megadapt/Inundaciones/Datos_EncharcamientosMagnitudColonia

El volumen mínimo asignado es: 

TIRANTE | LARGO | ANCHO
-- | -- | --
0.05 | 0.5 | 0.5
